### ISSUE TITLE
coverage/index.html file is blank

### ISSUE THREAD

**Issue by maurelian** [0xProject/0x-monorepo#1034]
I told @abandeali1 today that I'd run the `test:coverage` command successfully on the the contracts package, but that that html report was blank. 

It turns out that there's just an extraneous file in the root coverage directory. 

ie. 

![image](https://user-images.githubusercontent.com/23033765/44696730-bc657b00-aa46-11e8-9f39-e9275e83b6a7.png)

It's a very, very minor issue, but FYI.

**Comment by LogvinovLeon** [comment]
There are multiple coverage reporters.
* text (prints a table)
* html (generates `html` files in `coverage` subfolder)
* lcov (generates `*.lcov` files and (for whatever reason) html files in `coverage/lcov-report`)

On my machine - both reports are working and contain valid data.
I'll just close it for now, but feel free to reopen if it causes you any pain in future.
