### ISSUE TITLE
0x-connect@1.0.5: WebSocketOrderbookChannel is not exported in index.d.ts

### ISSUE THREAD

**Issue by wgan008** [0xProject/0x-monorepo#1049]
## Expected Behavior
To import `WebSocketOrderbookChannel` from 0x-connect

## Current Behavior

For `0x-connect v1.0.5`, `WebSocketOrderbookChannel` is not exported in `node_modules/@0xproject/connect/lib/src/index.d.ts` so it cannot be imported as `import { WebSocketOrderbookChannel } from '@0xproject/connect';`. 

Please suggest a way to import `WebSocketOrderbookChannel`.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.38.6  |
| `0x-connect` | v1      |

| Network |
| ------- |
| testrpc    |

-->

**Comment by fabioberger** [comment]
@wgan008 see: https://github.com/0xProject/0x-monorepo/blob/development/packages/connect/CHANGELOG.md#v100---july-20-2018
