### ISSUE TITLE
1.0 Document import { ZeroEx } from '0x.js' need to be modified

### ISSUE THREAD

**Issue by Xaber20110202** [0xProject/0x-monorepo#1062]
## Expected Behavior

ZeroEx can get just like 0x.js 0.x version

## Current Behavior

`ZeroEx` is undefined

## Possible Solution

I saw the code, 0x.js@1.0 above only export some utils from other packages, wouldn't export `ZeroEx` anymore, so I think that [document page](https://www.0xproject.com/docs/0x.js) should be modified.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 1.0.1  |
| `Exchange Contract` | v2     |

**Comment by dekz** [comment]
Docs should now be updated. Thanks for the report @Xaber20110202
