### ISSUE TITLE
ether token wrapper should provide ether token address on main net

### ISSUE THREAD

**Issue by generalpiston** [0xProject/0x-monorepo#1065]
The code below returns `undefined`:

```
const wrappers = new ContractWrappers(web3.currentProvider, {
  networkId: `
});
wrappers.etherToken.getContractAddressIfExists();
```

## Expected Behavior

I think: `0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2`.

## Current Behavior

Returns `undefined`.

## Possible Solution

`contract-wrappers/lib/src/artifacts/WETH9.json` contains:
```
"networks": {
  "3": {
    "address": "0xc778417e063141139fce010982780140aa0cd5ab",
    "links": {},
    "constructorArgs": "[]"
  },
  "42": {
    "address": "0xd0a1e359811322d97991e03f863a0c30c2cf029c",
    "links": {},
    "constructorArgs": "[]"
  },
  "50": {
    "address": "0x0b1ba0af832d7c05fd64161e0db78e85978e8082",
    "links": {},
    "constructorArgs": "[]"
  }
}
```

Maybe add main net config?

## Steps to Reproduce (for bugs)

1. `npm i 0x.js@latest`
2. Execute the following code:

```
const wrappers = new ContractWrappers(web3.currentProvider, {
  networkId: `
});
wrappers.etherToken.getContractAddressIfExists();
```

## Context

Upgrading Mobidex relayer. Can simply provide the address manually for now.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 1.0.1  |
| `@0xproject/contract-wrappers` | 1.0.1      |

| Network |
| ------- |
| mainnet    |

**Comment by fabioberger** [comment]
Thanks for the heads up @generalpiston. Adding this to our current sprint.

**Comment by michaelharrisonroth** [comment]
This appears to be the case for the `ZRXToken.json` artifact as well as `ERC20Token.json`.
