### ISSUE TITLE
Cannot compile using Typescript due to missing types in @0xproject/utils

### ISSUE THREAD

**Issue by dpyro** [0xProject/0x-monorepo#1066]
## Expected Behavior

Should compile. I can run a basic test suite for my own project fine using `ts-node` but it raises a compilation error if I try to compile ahead of time using `tsc`.

## Current Behavior

```
> tsc

node_modules/@0xproject/utils/lib/src/fetch_async.d.ts:3:63 - error TS2304: Cannot find name 'RequestInit'.

3 export declare const fetchAsync: (endpoint: string, options?: RequestInit, timeoutMs?: number) => Promise<Response>;
                                                                ~~~~~~~~~~~

node_modules/@0xproject/utils/lib/src/fetch_async.d.ts:3:107 - error TS2304: Cannot find name 'Response'.

3 export declare const fetchAsync: (endpoint: string, options?: RequestInit, timeoutMs?: number) => Promise<Response>;
```

## Possible Solution

Re-export `RequestInit` and `Request`

## Steps to Reproduce (for bugs)

Using any project that imports interesting things from `0x.js`:

```sh
npm install
npx tsc .
```

## Context

I was attempting to compile a project that uses various NodeJS libraries with Typescript definitions. It was previously working with 0x V1 (`0x.js` < 1)

I did a Github search for `RequestInit` in the monorepo but only found 1 hit: the code that causes the compilation error. I am not sure where this type is supposed to come from.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 1.0.1  |
| `@0xproject/types` | 1.0.1 |
| `ts-node` | 7.0.1 |
| `typescript` | 3.0.3 |

**Comment by fabioberger** [comment]
@dpyro the `RequestInit` type is defined in `@types/node` if I remember correctly. Can you try adding that dep and seeing if that solves it?

**Comment by fabioberger** [comment]
@dpyro Adding `dom` under `lib` in your `tsconfig.json` should fix this issue:

```
{
    "compilerOptions": {
        "lib": ["dom"],
        ...
```
