### ISSUE TITLE
0x.js has a massive deployment bundle size of ~8.4mb

### ISSUE THREAD

**Issue by mjdietzx** [0xProject/0x-monorepo#1068]
## Expected Behavior

The package size can be decreased dramatically (probably by an order of magnitude) by removing unnecessary contract json abis. looks like source code, byte code, runtime byte code, etc... are being included in these json files which probably isnt used. probably only need the abi right?

![image](https://user-images.githubusercontent.com/7217256/45387993-fbcfc200-b617-11e8-970f-638fb12c163c.png)

## Possible Solution

this helps: https://www.npmjs.com/package/webpack-bundle-analyzer

make sure only necessary contract jsons included. then strip down (only the abi). possibly even only use minimal interfaces with contract functions that are called? that could be overkill though

I'm also seeing some duplication `Exchange.json`, `ERC20.json`, etc are all included in package multiple times (3 times)?

8.4 mb is pretty brutal for a dependency.  https://bundlephobia.com/result?p=0x.js@1.0.1
## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.25.0  |
| `Exchange Contract` | v1      |

| Network |
| ------- |
| NAME    |

**Comment by fabioberger** [comment]
Thanks for pointing this out @mjdietzx. We are aware of this issue and now that V2 is deployed, feel it's a good time to tackle this issue. Will add it to our next sprint.

**Comment by pkieltyka** [comment]
hey guys — this is a pretty outrageous oversight... please fix it and please optimize as its adding massive bloat to our release

the major culprit here are the compiled json files, which are including bytecode, ast, source, etc. none of which are needed for the frontend client to interact with a contract, it just needs the abi

here is a script I've written that we post-process after contract compilation and put into a "abi" folder, https://gist.github.com/pkieltyka/1646a6f26e4c589e8f050e715e760e4b

**Comment by mjdietzx** [comment]
Awesome, thanks @fabioberger !

**Comment by pkieltyka** [comment]
neat service: https://bundlephobia.com/result?p=0x.js@1.0.1

**Comment by fabioberger** [comment]
Sorry about this oversight guys, fixing right away.

**Comment by pkieltyka** [comment]
@fabioberger awesome thanks. confirmed it reduced our bundle from 8MB to 2MB (ungzipped).. Gzipped its now 675kb

**Comment by aakilfernandes** [comment]
Hey, want to reping this since its unclear to me what the difference between @0xproject and @0x is. @0xproject sizes are reasonable but @0x are still huge (order-utils around 2mb)

**Comment by aakilfernandes** [comment]
https://bundlephobia.com/result?p=@0x/order-utils@7.1.1

It looks like the artifacts made their way back into the repo for some reason. Can we reopen @fabioberger ?

**Comment by fabioberger** [comment]
Thanks for the heads up @aakilfernandes, you are absolutely correct. I will make sure we tackle this, there is quite a bit of low hanging fruit here.

**Comment by dekz** [comment]
#1747
