### ISSUE TITLE
calling exchangeWrapper.cancelOrderAsync() without gasLimit results in error

### ISSUE THREAD

**Issue by labsterx** [0xProject/0x-monorepo#1071]
I'm getting errors when calling exchangeWrapper.cancelOrderAsync() on orders created by myself. The code was using 0x.js version 1.0.1 and was run on the Kovan testnet. Below is my code:

const txHash = await contractWrappers.exchange.cancelOrderAsync(signedOrder)

and the error is "Error: Contract call failed (returned null)".

However, if I add a gasLimit option "{gasLimit: 100000}" as the second parameter to the function, there's no more error. 

I guess the function shouldn't generate error if no gasLimit is specified. Also, I'm not sure how to estimate a gasLimit grammatically.

**Comment by dekz** [comment]
We `estimateGas` for cancelOrder, which returns X. 
When submitting the tx with X gasLimit the tx will fail with `out of gas`. 
When submitting with gasLimit of X+Y the tx will succeed and only spend X gas. 

So at this stage we need a buffer amount of gas added to the call.

`cancelOrder` don't do any storage clears or refunds in cancelOrder so it's difficult to determine the exact reason for the incorrect gas estimation
