### ISSUE TITLE
awaitTransactionMinedAsync returns transaction receipt while still pending (Parity Only)

### ISSUE THREAD

**Issue by cavanmflynn** [0xProject/0x-monorepo#1076]
`getTransactionReceiptAsync`, and therefore `awaitTransactionMinedAsync`, return a pending transaction receipt when using a Parity node. It may be purposeful for `getTransactionReceiptAsync` to return the pending transaction receipt as that is the behavior of the client, but it causes `awaitTransactionMinedAsync` to exit prematurely.

### Call

`const receipt = await this._web3Wrapper.awaitTransactionMinedAsync('0xb0d3179b95093f9de689f03b340a985d5b413b37c194d65412d72fb53ee008df');`

#### Node
`Geth/v1.8.13-patched-infura-omnibus-b59d4428/linux-amd64/go1.9.2`:

#### Immediate Output
`None - Tx is pending`

#### Node
`Parity//v1.10.6-stable-bc0d134-20180605/x86_64-linux-gnu/rustc1.26.1`

#### Immediate Output
```
{  
   "blockHash":null,
   "blockNumber":null,
   "contractAddress":null,
   "cumulativeGasUsed":"0xb808",
   "gasUsed":"0xb808",
   "logs":[  
      {  
         "address":"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
         "blockHash":null,
         "blockNumber":null,
         "data":"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
         "logIndex":null,
         "topics":[  
            "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
            "0x00000000000000000000000015fdb20d7629cc87fa719234b26bbf580bdb8958",
            "0x0000000000000000000000002240dab907db71e64d3e0dba4800c83b5c502d4e"
         ],
         "transactionHash":null,
         "transactionIndex":null,
         "transactionLogIndex":null,
         "type":"pending"
      }
   ],
   "logsBloom":"0x00000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000042002000000080000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000008000000000000000000400000000000000000010000000000000000000010200000000000000000000000000000000000000000000000000000000000",
   "root":null,
   "status":1,
   "transactionHash":"0xb0d3179b95093f9de689f03b340a985d5b413b37c194d65412d72fb53ee008df",
   "transactionIndex":"0x0"
}
```

## Expected Behavior

`awaitTransactionMinedAsync` does not exit until the transaction is mined regardless of client.

## Current Behavior

`awaitTransactionMinedAsync` exits immediately when using Parity.

## Possible Solution

Check for a blockNumber inside `awaitTransactionMinedAsync` if the transaction receipt exists:

`if (!receipt || (receipt && receipt.blockNumber === null)) return null;`

## Steps to Reproduce (for bugs)

```
1. Call `awaitTransactionMinedAsync` with a pending transaction hash against a Parity node.
2. `awaitTransactionMinedAsync` will exit with the pending transaction receipt immediately.
```

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 1.0.2  |
| `Exchange Contract` | v2      |

| Network |
| ------- |
| mainnet    |

**Comment by fabioberger** [comment]
Thanks for the heads up @cavanmflynn. Will try and reproduce and fix this ASAP.

**Comment by fabioberger** [comment]
@cavanmflynn fixed and published!
