### ISSUE TITLE
Getting errors when calling httpClient.getOrderConfigAsync() (0x V2)

### ISSUE THREAD

**Issue by labsterx** [0xProject/0x-monorepo#1078]
## Expected Behavior

httpClient.getOrderConfigAsync() (0x V2) should return order config without error

## Current Behavior

I ran into some errors when using httpClient.getOrderConfigAsync() to call SRA's "GET /v2/order_config" endpoint. The error is: "Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body." 

## Possible Solution

When I looked at the code for getOrderConfigAsync() (https://github.com/0xProject/0x-monorepo/blob/development/packages/connect/src/http_client.ts, line 150), there was a payload in httpRequestOpts and the request is a get. Maybe that's what the error message is complaining about? Moving info from payload to params could potentially fix the error.

## Steps to Reproduce (for bugs)

I got this error when calling this function from an internal web app. Unfortunately I can't share the code.

## Your Environment

`0x.js` | 1.0.3
`@0xproject/connect` | 2.0.1
`Exchange Contract` | v2
| kovan |

**Comment by fragosti** [comment]
@labsterx the request is being changed to a POST in #1091 so hopefully that fixes it.
