### ISSUE TITLE
isValidSignatureAsync does not normalize addresses

### ISSUE THREAD

**Issue by IncentiveLoop** [0xProject/0x-monorepo#1095]
When signing an order using `ecSignOrderHashAsync` the signer address is [normalized](https://github.com/0xProject/0x-monorepo/blob/82b51db17ee0f5bb7cd02f19cf942b525f96c0b4/packages/order-utils/src/signature_utils.ts#L213), however when attempting to [recover the signer](https://github.com/0xProject/0x-monorepo/blob/82b51db17ee0f5bb7cd02f19cf942b525f96c0b4/packages/order-utils/src/signature_utils.ts#L25) using `isValidSignatureAsync` the address is not normalized. 

This can lead to invalid address recovery, it would be great if addresses were normalized in `isValidSignatureAsync` too.

**Comment by fabioberger** [comment]
Thanks for the report @IncentiveLoop! Fix will go out in the next package release!
