### ISSUE TITLE
Add changelog when releasing new packages

### ISSUE THREAD

**Issue by cbovis** [0xProject/0x-monorepo#1100]
## Expected Behavior
When new package releases are made I would expect to have release notes describing the changes in https://github.com/0xProject/0x-monorepo/releases which would then feed into other tooling such as Renovate & Greenkeeper.

## Current Behavior
No release notes are attached to package releases. I've found minor/patch updates to be trustworthy however major version updates require digging through source code to ensure compatibility. Take for example this update of @0xproject/utils from v1 to v2 - https://github.com/0xTracker/0x-tracker-worker/pull/31.

## Possible Solution
Start using a commit message convention and take advantage of https://github.com/semantic-release/semantic-release to automate the creation of release notes.

**Comment by fabioberger** [comment]
@cbovis we actually be include release notes: https://github.com/0xProject/0x-monorepo/releases/tag/monorepo%40ac14dd2

However they currently get smothered by annotated tags created by [Lerna](https://github.com/lerna/lerna)'s publishing tool we currently use. There doesn't seem a way to get rid of these or at least make them not annotated (which causes them to show up under "releases").

Each package also has a [CHANGELOG.md](https://github.com/0xProject/0x-monorepo/blob/development/packages/base-contract/CHANGELOG.md) for further inspection.

Where I do think we could improve is adding CHANGELOG entries in upstream package's when changes implemented in lower-level packages affect it's interface by transitivity.

We have been discussing the move to Semantic Releases and have decided to give it a try. We just haven't had the bandwidth to do it just yet.
