### ISSUE TITLE
subproviders pkg: dependency is breaking dist builds targetting es5

### ISSUE THREAD

**Issue by pkieltyka** [0xProject/0x-monorepo#1110]
the `0xproject/subproviders` package uses `"web3-provider-engine": "14.0.6"` and unfortunately, this dependency in its dist/ files breaks es5 compatibility as it does not transpile the `const` keywords from its distribution files. As a result, this breaks distribution of my app that uses it.

Another thought is to get rid of web3-provider-engine and standardize on ethers

**Comment by fabioberger** [comment]
@pkieltyka thanks for opening the issue. We already know about this limitation and have contemplated dropping `web3-provider-engine`, however it hasn't been high-pri enough for us. 

Even if we dropped it, there are other packages that also don't have ES5 compatibility in the ecosystem (e.g [EthereumJS/RLP](https://github.com/ethereumjs/rlp)).

It is not as easy as "get rid of providerEngine and standardize on ethers". Ethers.js providers don't provide the same middleware-type cascading behavior of several subproviders. It doesn't have the same compos-ability. If we were to get rid of providerEngine, we would replace it with something very similar.

Please let me know if I'm missing some information about hows Ethers providers work, etc...

**Comment by pkieltyka** [comment]
The middleware subproviders and cascading composeable stuff should be a pretty small amount of code to make that happen. I’ll check but I think ethers has a fallback but perhaps it’s not a middleware approach if the interfaces are not consistent, could be wrapped or augmented. I’ll have a look at this tomm. 

Es5 issues can be solved upstream too, which is where they should be solved. But generally I feel those mistakes are just an example of the sloppiness of those libs.

**Comment by fabioberger** [comment]
Hm, ok, looked a bit into Ethers provider and see what you mean. Let me know if you can point me in the right direction on how you would do about wrapping/augmenting it.

Yeah, agreed. I guess we could fork `web3-provider-engine`, compile it to ES5 and point our dep to the compiled version. Is that what you mean by fixing it upstream?

**Comment by pkieltyka** [comment]
@fabioberger hey man, I was distracted at ETHSF/CESC the last few days, but back at it. Have you tried the FallbackProvider from ethers? For the composable providers, do you want to cascade down for retries in case one fails, or do you want to have a group of middlewares ahead to build a request? lmk and I'll try to draft something.

also, for upstream, I meant the maintainers of web3-provider-engine should be fixing the es5 compatibility issue. Forking it is one solution too, but it then becomes another dep you need to keep track of which isn't ideal
