### ISSUE TITLE
ethers v4.0.1 is out

### ISSUE THREAD

**Issue by pkieltyka** [0xProject/0x-monorepo#1111]
hey all, just sending a note that ethers v4 is out of beta and now at v4.0.1

**Comment by pkieltyka** [comment]
btw, once you guys upgrade everything to ethers v4, what do you think about making it a peer dependency for tiny versions?

**Comment by LogvinovLeon** [comment]
Hi, @pkieltyka. Thanks for a heads up. Will migrate. Could you please explain why would we use peerDependencies? Our packages are using ethers.js directly. As far as I understand peerDependencies are mostly for plugins. I agree with allowing patch versions though.

**Comment by pkieltyka** [comment]
@LogvinovLeon hey man. great you set the patch version. The thinking with moving ethers to a peerDependency is that the top-level app would "bring-their-own" ethers dependency, so they could control the version. But, after some thought, I think you setting "~4.0.4" for ethers at dep level, I believe this will achieve the same thing to resolve to the most up-to-date but compatible ethers version for apps too. Thanks!

**Comment by fabioberger** [comment]
@pkieltyka need us to prioritize publishing a new version to NPM?

**Comment by pkieltyka** [comment]
All good but thanks very much for asking :)
