### ISSUE TITLE
Old Version of bignumber.js

### ISSUE THREAD

**Issue by pointtoken** [0xProject/0x-monorepo#1136]
## Current Behavior

0x-monorepo/packages/types/ uses "bignumber.js": "~4.1.0". This is a very old version of the bignumber library and is not forward compatible with the latest bignumber.js "7.2.1". If a project has a dependency a more recent version, it wreaks havoc on the code.
## Possible Solution

Upgrade the types package to the latest bignumber.js.

**Comment by WyseNynja** [comment]
8.0.1 is out now.

https://github.com/MikeMcl/bignumber.js/blob/master/CHANGELOG.md

**Comment by fabioberger** [comment]
Hm... should we even stay with BigNumber? Looks like Ethers.js and a lot of other Ethereum tools use BN.js. This is a larger discussion, but any thoughts on migrating away from BigNumber.js entirely?

**Comment by fabioberger** [comment]
Allocating time in our next sprint for this upgrade.
