### ISSUE TITLE
main.ts:14:2 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

### ISSUE THREAD

**Issue by senzacionale** [0xProject/0x-monorepo#1167]
## Expected Behavior

Should compile. I can run a basic test suite for my own project fine using ts-node but it raises a compilation error if I try to compile ahead of time using tsc main.ts.

## Current Behavior

My tsconfig.json

`{
    "compilerOptions": {
      "module": "commonjs",
      "declaration": false,
      "noImplicitAny": false,
      "removeComments": true,
      "noLib": false,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "target": "es6",
      "sourceMap": true,
      "allowJs": true,
      "outDir": "./dist",
      "lib": [ "es2015", "dom" ]
    },
    "exclude": [
      "node_modules",
      "**/*.spec.ts"
    ]
  }`

`main.ts:14:2 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

14 (async () => {
    ~~~~~~~~~~~~~
`

## Possible Solution

<!--- Not obligatory, but suggest a fix/reason for the bug, -->

<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)

<!--- Provide a link to a live example, or an unambiguous set of steps to -->

<!--- reproduce this bug. Include code to reproduce, if relevant -->

Using any project that imports interesting things from 0x.js:

File:
https://files.fm/u/d9kvsmaq

```
1. npm install
2. npm tsc
3. tsc main.ts
4. node .\main.js
```

## Context

<!--- How has this issue affected you? What are you trying to accomplish? -->

<!--- Providing context helps us come up with a solution that is most useful in the real world -->

I was attempting to compile a project that uses various NodeJS libraries with Typescript definitions

## Your Environment

<!--- Include as many relevant details about the environment you experienced the bug in -->

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | latest  |

| Network |
| ------- |
| MAINNET or TESTNET|

<!-- For example:
| mainnet |
| kovan |
| testrpc |
-->

**Comment by fabioberger** [comment]
Any update on this @senzacionale? When did this happen? When trying to compile the monorepo? Can you please host your project and send us a Github link? We don't download zips.
