### ISSUE TITLE
Create a reliable stream of events for consumers when sender contracts/forwarding contracts are used

### ISSUE THREAD

**Issue by labsterx** [0xProject/0x-monorepo#1171]
## Expected Behavior

A taker (let's call him/her the original taker) may fill an order directly using the 0x exchange contract or using the forwarding contract or the sender contract. In all these cases, the log events should have the original taker's address recorded for trade history lookup.

## Current Behavior

When forwarding contracts are used to fill an order, the takerAddress recorded in the log fill events is the address of contract account instead of the original taker's address. The original taker's address is not recorded and hard to retrieve. This makes trade history lookup for the original taker difficult.

## Possible Solution

Add the original taker's address to the event log and return this address in the 0x.js helper functions.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 1.0.8  |
| `Exchange Contract` | v2      |

| Network |
| mainnet |
| Ropsetn |
| kovan |
| testrpc |

**Comment by abandeali1** [comment]
For sender contracts, the actual taker address should be correctly recorded. Forwarder contracts are a bit different in that they technically _are_ the taker for the order. We can add extra events in any Forwarder contracts to account for this, but ultimately that might be hard to standardize.

You can also parse all of the `Transfer` logs associated with a fill from the Forwarder (if Fill.senderAddress == Forwarder.address, the `_to` address of the final `Transfer` log should be the taker). Does that fully solve the issue @labsterx ?

**Comment by labsterx** [comment]
@abandeali1 Thanks for your reply! Thank you @dekz for the explanation.

For relayers, one must-have feature is to list a trade history for the user and the history should include all kinds of trades (the user as maker, as taker as well as trades executed by forwarding contracts). 

To accomplish this (before turning on forwarder token buying), we have been using a cronjob which keeps calling the exchangeWrapper.getLogsAsync() function provided by 0x.js to pull out all "fill" events and save the info in our backend database for quick lookup. 

In order to turn on forwarder token buying, we need to save the new type of trade in our DB but currently the exchangeWrapper.getLogsAsync() doesn't include the needed info. We hope the same function can return the new type of trade data as well so that we don't have to do complicated digging and parsing ourselves. 

For the time being, probably we can use the way @abandeali1 has recommended --- "parse all of the Transfer logs associated with a fill from the Forwarder (if Fill.senderAddress == Forwarder.address, the _to address of the final Transfer log should be the taker)." However, I'm still a little confused about how to do it step-by-step using the exchangeWrapper.getLogsAsync() function without having to interact with the blockchain directly. If you can provide some more detailed instruction, that'd by really helpful! Thanks!

**Comment by dwbauschlicher** [comment]
Isn't it possible that there are multiple forwarder contract transfers in a single block? How would I be able to distinguish the transfer I am looking for specifically?
