### ISSUE TITLE
OTC page just spins in Firefox with MetaMask.

### ISSUE THREAD

**Issue by MicahZoltu** [0xProject/0x-monorepo#1191]
[This order](https://www.0xproject.com/portal/fill?order={%22signedOrder%22:{%22senderAddress%22:%220x0000000000000000000000000000000000000000%22,%22makerAddress%22:%220x7a1009d352fe8529d30cb1e6b5bad23b8ed76cf3%22,%22takerAddress%22:%220x0000000000000000000000000000000000000000%22,%22makerFee%22:%220%22,%22takerFee%22:%220%22,%22makerAssetAmount%22:%22529000000000000000000%22,%22takerAssetAmount%22:%22687700000000000000000%22,%22makerAssetData%22:%220xf47261b000000000000000000000000061327ca77fc98c0b0d44e357e37ffeefe8518bc4%22,%22takerAssetData%22:%220xf47261b00000000000000000000000001985365e9f78359a9b6ad760e32412f4a445e862%22,%22expirationTimeSeconds%22:%221540958880%22,%22feeRecipientAddress%22:%220x0000000000000000000000000000000000000000%22,%22salt%22:%2220276517628850720779204324849933898800153675250276281654849436652214186591870%22,%22signature%22:%220x1c7091422a444d96a9bca346501289441ade1c86c61c958e68f920a54f1996800d22cbdf462af43c749c3c1ffdff041da9c649979df08720db4060f3ef852d485a03%22,%22exchangeAddress%22:%220x4f833a24e1f95d70f028921e27040ca56e09ab0b%22},%22metadata%22:{%22makerToken%22:{%22name%22:%22Bastill%20round%2015%20Invalid%22,%22symbol%22:%22B15I%22,%22decimals%22:18},%22takerToken%22:{%22name%22:%22Reputation%22,%22symbol%22:%22REP%22,%22decimals%22:18}}}) just causes Firefox to display spinners forever when I load it.  I have tried other orders, same behavior.  

## Expected Behavior

Page loads eventually.

## Current Behavior

Page displays a spinner in the top right (account or network drop-down I presume) and a spinner in the middle of the page.

## Steps to Reproduce (for bugs)

```
1. Open Firefox 62.0.3 (64-bit) on Windows 10 with MetaMask 4.9.2
2. Open a new InPrivate browser window (to ensure clear cache/cookies).
3. Navigate to above link.
4. Wait forever.
```

## Context

Unable to use 0x OTC tool.  I wanted to trade.

## Your Environment

Windows 10
Firefox 62.0.3 (64-bit)
MetaMask 4.9.2 (not logged in)

**Comment by fabioberger** [comment]
@MicahZoltu might be related to: https://github.com/0xProject/0x-monorepo/pull/1190. Will deploy this fix to staging. Could you give it a try when I do?

**Comment by fabioberger** [comment]
Should be fixed now @MicahZoltu. Mind clearing your browser cache and retrying?

**Comment by burdakovd** [comment]
It seems not quite related. Micah sees the issue on wider set of orders, and on earlier stage.

I.e. this is the timeline:
1) Page loads and spinner spins <-- this is where Micah gets stuck
2) 0x portal offers to start tracking the tokens offered
3) JS exception happens and page goes blank <-- this is what I experienced

I couldn't repro issue of Micah myself.

@MicahZoltu if you still see it, do you mind opening JS debug console and telling whether/which errors you see (or taking a screenshot)

**Comment by fabioberger** [comment]
I see. Tried to repro (Firefox, Metamask, OSX) but was unable to.

**Comment by MicahZoltu** [comment]
My problem appears to also be fixed.
