### ISSUE TITLE
validateOrderFillableOrThrowAsync swallows errors and returns incorrect RevertReason

### ISSUE THREAD

**Issue by prettymuchbryce** [0xProject/0x-monorepo#1218]
## Expected Behavior

Calling `zeroExContractWrappers.exchange.validateOrderFillableOrThrowAsync` should return an accurate `RevertReason`, or throw a relevant error if the underlying Ethereum node is unreachable. 

## Current Behavior

Instead `validateFillOrderBalancesAllowancesThrowIfInvalidAsync` in `order_validation_utils` will swallow any connectivity errors and instead return the revert reason as `TRANSFER_FAILED`.

https://github.com/0xProject/0x-monorepo/blob/development/packages/order-utils/src/order_validation_utils.ts#L109

## Possible Solution

Don't swallow errors, and don't ignore the possibility of connectivity issues when dealing with requests over a network. Check the type of error and return an accurate error to the client so that the client can decide how to handle the error.

## Context

We see this when there is any sort of connectivity issue, we have no way to discern it from a legitimate TRANSFER_FAILED error. It potentially could cause clients to mark an order as unfillable when in fact there was just a temporary connection issue.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | ^1.0.7  |

| Network |
| ------- |
| mainnet |

**Comment by fabioberger** [comment]
Thanks for the report @prettymuchbryce, will look into fixing this now.

**Comment by fabioberger** [comment]
@prettymuchbryce we've fixed this issue and published a new version of `@0x/contract-wrappers`.
