### ISSUE TITLE
Metamask provider not wrapped in MetamaskSubprovider error - EIP712

### ISSUE THREAD

**Issue by MarcZenn** [0xProject/0x-monorepo#1223]
## Expected Behavior

Per the examples provider here - https://github.com/0xProject/0x-monorepo/issues/1169, I've setup the following `MetamaskSubprovider` implementation:

```
import { MetamaskSubprovider, RPCSubprovider, SignerSubprovider,  Web3ProviderEngine } from '@0x/subproviders';

const engine = new Web3ProviderEngine();
const signer = new MetamaskSubprovider(web.currentProvider);
const rpcProvider = new RPCSubprovider(nodeUrl);

// Add the signer first, all account based requests are handled by the signer
engine.addProvider(signer);

// Add the data provider, all logs, data fetching are handled by the rpcProvider
engine.addProvider(rpcProvider);

const web3Wrapper = new Web3Wrapper(engine);
const contractWrappers = new ContractWrappers(engine, { networkId });
```
This should display order data in the Metamask signing prompt when an order is signed via the following 0x.js signature utils method: 

```
import { signatureUtils } from '0x.js';

try {
     await signatureUtils.ecSignTypedDataOrderAsync(engine, order, makerAddress);
 } catch (error) {
     console.log(error);
}
```

## Current Behavior

At the moment that method when invoked is producing an error that when logged outputs `Error: MetaMask provider must be wrapped in a MetamaskSubprovider (from the '@0x/subproviders' package) in order to work with this method.` to the console. 

This is accompanied by `MetaMask - RPC Error: TypeError: e.toLowerCase is not a function chrome-at L extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js` type error. 

## Possible Solution

Unsure of a solution but passing `MetamaskSuprovider` directly to `ecSignTypedDataOrderAsync` i.e. 
`signatureUtils.ecSignTypedDataOrderAsync(new MetamaskSuprovider(web.currentProvider, order, makerAddress)` works as expected.

## Steps to Reproduce (for bugs)

I will post up a minimal repo as soon as I can. 

## Environment

0x.js 2.0.0
@0x/subproviders 2.1.0
@0x/web3-wrapper 3.1.0
metamask plugin 5.0.0
node 8.9.0

**Comment by dekz** [comment]
hey @MarcZenn 

`MetaMask - RPC Error: TypeError: e.toLowerCase is not a function ` might be an indication to an underlying problem.

I've quickly forked the [codesandbox to use provider engine](https://codesandbox.io/s/vj1qylwm65). It should popup a signing window on load. Which I've just tested locally on Metamask 5.0.0.

Can you confirm whether you see the same errors in this code sandbox?

**Comment by MarcZenn** [comment]
Hmm the signing window appears in the codesandbox and works as expected.

**Comment by dekz** [comment]
Can you JSON stringify the order and signerAddress/makerAddress you are using in your example?

**Comment by MarcZenn** [comment]
JSON stringifying results in a type error `Error: Expected order to conform to schema /orderSchema`.

**Comment by MarcZenn** [comment]
I've found the cause of my issue! 

There was a method in my code overriding the `MetamaskSubprovider` wrapped provider with the injected web3 provider...hence the error. :man-facepalming:

want me to close the issue?
