### ISSUE TITLE
Cannot install 0x-monorepo with yarn

### ISSUE THREAD

**Issue by robpal1990** [0xProject/0x-monorepo#1245]
## Expected Behavior

I tried to build the repo with all packages using yarn but it fails.
I have installed the suggested version `1.9.4`, I also have the version `8.12.0` of nodejs.

## Current Behavior

`yarn install` works fine.
`yarn build` fails with the following stacktrace

@0x/instant
 | ℹ ｢atl｣: Checking started in a separate process...
 | ✖ ｢atl｣: Checking finished with 1 errors
 | Hash: b56b68fc54f5ae1f350e
 | Version: webpack 4.25.1
 | Time: 55190ms
 | Built at: 11/11/2018 10:56:29 PM
 |  76 assets
 | Entrypoint main = main.bundle.js main.bundle.js.map
 |   [2] packages/utils/lib/src/index.js 1.26 KiB {0} [built]
 |   [6] packages/types/lib/index.js 9.42 KiB {0} [built]
 |   [9] packages/instant/(webpack)/buildin/global.js 489 bytes {0} [built]
 |  [11] packages/json-schemas/lib/src/index.js 401 bytes {0} [built]
 |  [12] packages/assert/lib/src/index.js 4.67 KiB {0} [built]
 |  [23] packages/order-utils/lib/src/index.js 3.19 KiB {0} [built]
 |  [37] packages/instant/(webpack)/buildin/module.js 497 bytes {0} [built]
 |  [78] packages/order-utils/lib/src/order_hash.js 2.67 KiB {0} [built]
 |  [80] packages/order-utils/lib/src/types.js 809 bytes {0} [built]
 | [108] packages/utils/lib/src/configured_bignumber.js 1.77 KiB {0} [built]
 | [111] packages/order-utils/lib/src/eip712_utils.js 3.58 KiB {0} [built]
 | [147] packages/utils/lib/src/address_utils.js 1.88 KiB {0} [built]
 | [168] packages/json-schemas/lib/src/schemas.js 5.31 KiB {0} [built]
 | [174] packages/order-utils/lib/src/signature_utils.js 27.2 KiB {0} [built]
 | [668] packages/instant/src/index.umd.ts + 95 modules 314 KiB {0} [built]
 |       | packages/instant/src/index.umd.ts 2.76 KiB [built]
 |       | packages/instant/src/constants.ts 1.43 KiB [built]
 |       | packages/instant/src/index.ts 139 bytes [built]
 |       | packages/instant/src/util/assert.ts 2.89 KiB [built]
 |       | packages/instant/src/types.ts 1.5 KiB [built]
 |       | packages/instant/src/style/theme.ts 1.51 KiB [built]
 |       | packages/instant/src/util/asset.ts 3.64 KiB [built]
 |       | packages/instant/src/style/media.ts 2.34 KiB [built]
 |       | packages/instant/src/style/util.ts 299 bytes [built]
 |       | packages/instant/src/containers/available_erc20_token_selector.ts 759 bytes [built]
 |       | packages/instant/src/containers/latest_buy_quote_order_details.ts 536 bytes [built]
 |       | packages/instant/src/style/z_index.ts 181 bytes [built]
 |       | packages/instant/src/util/error_flasher.ts 922 bytes [built]
 |       | packages/instant/src/containers/latest_error.tsx 1.53 KiB [built]
 |       | packages/instant/src/containers/selected_asset_buy_order_progress.ts 304 bytes [built]
 |       |     + 81 hidden modules
 |     + 654 hidden modules
 | 
 | ERROR in [at-loader] packages/instant/./src/style/theme.ts:3:53 
 |     TS2459: Type 'typeof import("/home/robert/Downloads/0x-monorepo/node_modules/styled-components/typings/styled-components")' has no property 'createGlobalStyle' and no string index signature.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | ERROR: "build:umd:prod" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`yarn build` failed with exit code 1
Stopping 36 active children
Aborted execution due to previous error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Possible Solution

I read that `0x/instant` is still under development and might not work and thus make the build fail. However, I'm completely new to JS/TS and have no idea how to fix it (remove from the build).

## Your Environment

Ubuntu 16.04
NodeJS 8.12.0
Yarn 1.9.4
 0x code: `development` branch of the current 0x-monorepo

**Comment by steveklebanoff** [comment]
We ran a `yarn build` with the node 8.12.0 and yarn 1.9.4 on both my mac and @feuGeneA's Ubuntu 14.04, and the build succeeded.

Can you try running `yarn clean` and `yarn remove_node_modules` and trying again?  If this is still breaking for you, we can dive deeper.
