### ISSUE TITLE
HOWTO, use the UMD module in V2 

### ISSUE THREAD

**Issue by cohabo** [0xProject/0x-monorepo#1268]
When using the umd library downloaded here [https://github.com/0xProject/0x-monorepo/releases/tag/monorepo%40fe1b7f1](url) in a html application i get an 

> Uncaught TypeError: ZeroEx.Zero is not a constructor.

I include it in my html file and do not use any requires, like this:

`	<script charset="utf-8" src="./lib/0x.js/zeroex.min.js" type="text/javascript"></script>
	<script charset="utf-8" src="./lib/0x.js/zeroex.js" type="text/javascript"></script>`

I proceed to use its instance like this
`

		if (typeof web3 !== 'undefined') {
			console.log('Web3 Detected! ' + web3.currentProvider.constructor.name)
			web3 = new Web3(web3.currentProvider);
		} else {
			// set the provider you want from Web3.providers
			console.log('No Web3 Detected... using HTTP Provider')
			web3 = new Web3(new Web3.providers.HttpProvider("https://ropsten.infura.io/d0342720ca304468ab0e1075e581eea9d0342720ca304468ab0e1075e581eea9"));
		}

		console.log(web3.currentProvider);

		// INIT ZEROEX INSTANCE
		var web3Wrapper = new ZeroEx.Web3Wrapper(web3.currentProvider);

		`console.log(web3.currentProvider);`
`

**Comment by LogvinovLeon** [comment]
@cohabo 
1. You shouldn't include it twice. Use either minified version or unminified one but not both.
2. `Web3Wrapper` is not exported from `0x.js` package. It's exported from [`@0x/web3-wrapper`](https://0xproject.com/docs/web3-wrapper) package.
3. It's super strange that you've got an error `ZeroEx.Zero is not a constructor.` as you're not calling `Zero` in your code. Are you sure it's not `Uncaught TypeError: ZeroEx.Web3Wrapper is not a constructor`? That's what I'm getting. And it seams reasonable as Web3Wrapper is not exported from that package.
