### ISSUE TITLE
[order-watcher] How should I watch v1 orders?

### ISSUE THREAD

**Issue by WyseNynja** [0xProject/0x-monorepo#1284]
## Expected Behavior

It looks like the latest version of order-watcher can only watch v2 orders. I hope that all the exchanges will upgrade to the new protocol, but until they do, what is the best way to watch v1 orders?

## Possible Solutions

1. Run a seperate process with order-watcher v1.0.5? That seems like it might have some bugs in it though. Is it under the @0x namespace, or is v1 before the move from @0xProject?

2. Add an addOrderAsyncV1 function so I can keep running a single daemon.

3. Change addOrderAsync to check the order type and watch V1 or V2 depending. Same pros/cons as 2.

I'm not sure how easy 2 and 3 are since the functions to connect to the V1 contracts might not exist anymore. I'm not familiar enough with the code yet to know.

## Context

I initially got my code working on [RadarRelay](https://developers.radarrelay.com/sra/v2/) and they have v2 support. Now I have started looking at [The Ocean's docs](https://docs.theocean.trade/) and noticed that the orders are v1.

**Comment by fabioberger** [comment]
@WyseNynja unfortunately there was an Ethereum JSON RPC bug that was not fixed back when OrderWatcher was used for V1 orders. 

The Ocean should be upgrading to V2 soon. In the mean time, consider integrating other relayers that are already on V2 (e.g All the ones listed in Portal: https://0xproject.com/portal)
