### ISSUE TITLE
Clarify lower-case usage of addresses throughout 0x

### ISSUE THREAD

**Issue by liamzebedee** [0xProject/0x-monorepo#1285]
## Expected Behavior
Hex-encoded Ethereum addresses can have both upper and lowercase alphabetic symbols. It would be expected that 0x supports both or explicitly mentions only supporting lowercase in the docs.

## Current Behavior
Currently, addresses are just assumed to be lower case, and also translated at test-time ([example](https://sourcegraph.com/github.com/0xProject/0x-monorepo/-/blob/packages/contract-wrappers/src/contract_wrappers/erc20_token_wrapper.ts#L319:55)).

The regex for validating addresses also only assumes lowercase.

## Possible Solution
Add a note somewhere appropriate in the docs, or fund a Gitcoin issue to make it case-agnostic ;) 

## Your Environment
0x.js usage in V2 of the protocol.

**Comment by fabioberger** [comment]
@liamzebedee we purposefully only support lowercase addresses. Which method call did not throw a helpful error message when passed a checksummed address? We would definitively want the caller to be notified if they supply an incorrectly formatted address.

**Comment by liamzebedee** [comment]
@fabioberger in that case, please "add a note somewhere appropriate in the docs" - caught me by surprise and had to correct it in a couple places / educate the team

**Comment by fabioberger** [comment]
@liamzebedee can you tell me which method you called that did not throw a helpful error message?

**Comment by liamzebedee** [comment]
Might be able to find it later, but it was about two weeks ago :P

**Comment by fabioberger** [comment]
Ah ok, please do let me know if it shows up. We try to be good about giving developers helpful error messages that are informative and educational.
