### ISSUE TITLE
validateOrderFillableOrThrowAsync Race Condition

### ISSUE THREAD

**Issue by prettymuchbryce** [0xProject/0x-monorepo#1286]
Hello,

We have come across a race condition with `validateOrderFillableOrThrowAsync`.

One minor nit first, the comment here is slightly misleading:
https://github.com/0xProject/0x-monorepo/blob/c41622c20aea8ba89dc9899ff8b3ab6f22f53503/packages/order-utils/src/order_validation_utils.ts#L132

It states "If supplied, this call will make sure this amount is fillable. If it isn't supplied, we check if the order is fillable for a non-zero amount"

Technically this is true, but more a accurate description might be "we check if the order is fillable for the remaining taker amount".

https://github.com/0xProject/0x-monorepo/blob/c41622c20aea8ba89dc9899ff8b3ab6f22f53503/packages/order-utils/src/order_validation_utils.ts#L167

The real issue here is that there appears to be a race condition in `validateOrderFillableOrThrowAsync` in order-utils.

Suppose `expectedFillTakerTokenAmount` is not specified, and between calling `getFilledTakerAmountAsync`, and `validateFillOrderBalancesAllowancesThrowIfInvalidAsync`, a block is mined wherein some of the order was filled. If that's the case then we could throw `FailureReason.Balance` if the maker now has too little balance to fill the order. This is a race condition, and likely not the behavior that the caller was expecting.

I believe the only way to accurately gauge if the maker has sufficient remaining balance corresponding to the remaining taker amount atomically is to do so in a contract on-chain.

## Expected Behavior

`FailureReason.Balance` is thrown if the maker does not a balance >= the remaining maker amount.

## Current Behavior

`FailureReason.Balance` is thrown when the maker _does_ have a balance >= the remaining maker amount.

## Possible Solution

Write this behavior into a contract that can be called by the 0x library.

That is – check atomically that the maker has balance/allowance >= the remaining maker amount in the order.

## Context

This could cause orders to be incorrectly pruned from an orderbook.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 2.0.2  |

| Network |
| ------- |
| mainnet    |

**Comment by dekz** [comment]
Thanks for the report @prettymuchbryce. 

We've started doing exactly what you mention, have a [contract able to fetch everything atomically](https://github.com/0xProject/0x-monorepo/blob/development/packages/contracts/contracts/extensions/OrderValidator/OrderValidator.sol#L91)rather than making multiple `eth_call`s over various block numbers. This will likely be extended to support some additional query fetching as well.

Our plan is to ultimately refactor our libraries to make use of this contract so it's on our Roadmap!

**Comment by prettymuchbryce** [comment]
Sounds great. Looking forward. Thanks @dekz
