### ISSUE TITLE
Publish contracts/ package so we can import IExchange

### ISSUE THREAD

**Issue by liamzebedee** [0xProject/0x-monorepo#1293]
Is there a reason why the @0x/contracts package is private? Currently building 0x on a private chain, using the `IExchange` type for a filter contract on orders - it would be useful to be able to import as so in Solidity:

```
import "@0x/contracts/contracts/protocol/Exchange/interfaces/IExchange.sol";
import "@0x/contracts/contracts/contracts/utils/LibBytes/LibBytes.sol";
import "@0x/contracts/contracts/contracts/protocol/Exchange/libs/LibOrder.sol";
```

**Comment by fabioberger** [comment]
Yep, that is on our roadmap. Will keep this issue open to add more info as we progress on this.

**Comment by fabioberger** [comment]
@liamzebedee we did end up publishing our contracts in several packages. The protocol contracts are in https://www.npmjs.com/package/@0x/contracts-protocol.

Hope this helps!

**Comment by liamzebedee** [comment]
Cheers @fabioberger !
