### ISSUE TITLE
[0x-watcher] UnhandledPromiseRejectionWarning: TypeError: totalTakerAssetAmount.minus is not a function

### ISSUE THREAD

**Issue by WyseNynja** [0xProject/0x-monorepo#1315]
## Current Behavior

My 0x-watcher code (https://github.com/WyseNynja/0x-order-watcher) got this error while watching some orders. It's happening pretty reliably, and it is luckily not crashing the app.

```
(node:475) UnhandledPromiseRejectionWarning: TypeError: totalTakerAssetAmount.minus is not a function
    at OrderStateUtils.<anonymous> (/usr/src/myapp/node_modules/@0x/order-utils/lib/src/order_state_utils.js:264:53)
    at step (/usr/src/myapp/node_modules/@0x/order-utils/lib/src/order_state_utils.js:32:23)
    at Object.next (/usr/src/myapp/node_modules/@0x/order-utils/lib/src/order_state_utils.js:13:53)
    at fulfilled (/usr/src/myapp/node_modules/@0x/order-utils/lib/src/order_state_utils.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:475) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
```

## Steps to Reproduce (for bugs)

Not sure, but my app (https://github.com/WyseNynja/0x-order-watcher) is pretty simple so it should be easy. I think partial fills cause this but haven't done much investigation yet. 

## Your Environment

I just ran `yarn upgrade` and my package.json has:
```
  "dependencies": {
    "@0x/order-watcher": "^2.2.4",
    "@0x/utils": "^2.0.2",
```

| Package | Version |
| ------: | :------ |
|             `"@0x/order-watcher` | 2.2.5   |

| Network |
| ------- |
| mainnet |

**Comment by fabioberger** [comment]
@WyseNynja are the amounts within the Orders you submit to the OrderWatcher converted to BigNumbers, or are they strings? My hunch is that they are strings and that is why you are getting this error. 

We should add better assertions to make sure this doesn't happen to others.

**Comment by WyseNynja** [comment]
I have a “convertToBigNumber” function that I’m calling on the received order JSON. Maybe it is missing a key?

It’s at the bottom of https://github.com/WyseNynja/0x-order-watcher/blob/master/src/index.js

**Comment by WyseNynja** [comment]
Aha! my code was originall for v1 and was converting "makerTokenAmount" instead of "makerAssetAmount"
