### ISSUE TITLE
SignerSubprovider loses precision and causes reverts

### ISSUE THREAD

**Issue by prettymuchbryce** [0xProject/0x-monorepo#1394]
## Expected Behavior

Subproviders should _never_ convert Hex Values (gas, gasPrice, value) into JavaScript Numbers as they are floating point values, and thus imprecise.

## Current Behavior

There are a number of places where I see a function used called [convertHexToNumber](https://github.com/0xProject/0x-monorepo/blob/e5cfc94cd243b339376fa6eb73209790c91c73f2/packages/web3-wrapper/src/utils.ts#L9), specifically in this function [unmarshalTxData](https://github.com/0xProject/0x-monorepo/blob/e5cfc94cd243b339376fa6eb73209790c91c73f2/packages/web3-wrapper/src/marshaller.ts#L121). I notice that this function converts hex representations of value, gas, and gasPrice into Javascript Number values.

This is obviously bad, for example lets say we want to send a TX with an ETH value of `0x2b5e3af16b1897cdc`, 

```javascript
> var bn = require('bignumber.js');
undefined
> var x = new bn('0x2b5e3af16b1897cdc');
undefined
> x.toString()
'50000000000000097500'
> x.toNumber()
50000000000000100000
````

The above is actually a sunny case where we might send more ETH than required by a contract call, but often it's possible that we send less which would certainly cause the transaction to revert on-chain, and the caller to have wasted gas.

## Possible Solution

Lets not represent gasPrice, gasAmount, or transaction values as JavaScript Numbers.

## Steps to Reproduce (for bugs)

Use web3 provider engine with the `SignerSubprovider`, or `MetamaskSubprovider` and provide a value that is above `Number.MAX_SAFE_INTEGER` (9007199254740991).

I also see a reference in `trace_collection_subprovider` within the `sol-cov` package, but I'm not exactly sure what this is used for.

## Context

This has caused a lot of head scratching for us, and resulted in many transactions being reverted on-chain for users.

## Your Environment

| Package | Version |
| --- | --- |
| `@0x/subproviders` | ^2.1.0 |

| Network |
| ------- |
| mainnet |
| kovan |
| testrpc |

**Comment by fabioberger** [comment]
Thanks for the report @prettymuchbryce, that's what we get for adapting badly written code from `web3-provider-engine`. Will prioritize getting a fix out for this ASAP.

**Comment by fabioberger** [comment]
Just to confirm that we are on the same page,

**Comment by prettymuchbryce** [comment]
@fabioberger Sounds good. Thank you. Did you intend to close this issue?

**Comment by fabioberger** [comment]
Sorry @prettymuchbryce, no that was a mistake, re-opened and working on a fix now.

**Comment by fabioberger** [comment]
@prettymuchbryce a new version of `@0x/web3-wrapper` was published with the requested fix: https://github.com/0xProject/0x-monorepo/issues/1316. Thanks again for the heads up!

**Comment by prettymuchbryce** [comment]
Thanks for the quick fix @fabioberger 👏
