### ISSUE TITLE
Error via filling order

### ISSUE THREAD

**Issue by vidyaevoleg** [0xProject/0x-monorepo#1406]
Hi ! 
I faced some problem with fillOrderAsync function.   
When I called fillOrderAsync for buy order on Kovan network I got that error
  https://imgur.com/eZufyfy
But when I did same operation on Main network I got more readable error, but it also didn’t help to understand what I did wrong.
https://imgur.com/iGvd88Q

What does it look like?

## Expected Behavior

Transaction creating

## Current Behavior

  https://imgur.com/eZufyfy
https://imgur.com/iGvd88Q

## Environment
Kovan , Mainnet

`0x` version 2.0.4

**Comment by fabioberger** [comment]
@vidyaevoleg the `TRANSFER_FAILED` error message means that the the transfer sender either did not have a sufficient allowance or balance to complete their part of the trade. To get a better error message, use https://0xproject.com/docs/contract-wrappers#ExchangeWrapper-validateFillOrderThrowIfInvalidAsync.

**Comment by vidyaevoleg** [comment]
Thanks!
