### ISSUE TITLE
0x Instant (buy_button.ts) Unhandled Promise Rejection

### ISSUE THREAD

**Issue by hewigovens** [0xProject/0x-monorepo#1433]
Hi

We tested 0x Instant on a mobile wallet (Trust) and found an error in `buy_button.ts` when canceling an order, below is the screenshot:

![screen shot 2018-12-14 at 09 55 49](https://user-images.githubusercontent.com/360470/49979133-a2fe2580-ff88-11e8-8365-85b6ac711683.png)

We find that `BuyButton` only handles specific error messages, like `AssetBuyerError.SignatureRequestDenied` (https://github.com/0xProject/0x-monorepo/blob/f076cdb8329693e9d7351ec88d2ac01ad42a2a3a/packages/instant/src/components/buy_button.tsx#L85)

And if we change the error message to `SIGNATURE_REQUEST_DENIED`, we can cancel the order correctly, but not every dApp browser emits the same error message.

## Expected Behavior

0x Instant should cancel the order when an error occurred

## Current Behavior

please check the screenshot above, it gets stuck at "Placing Order..."

## Possible Solution

- configurable error messages
- add a default error handler

## Steps to Reproduce (for bugs)

https://0x-instant-test.surge.sh/

```
1. Open Trust Wallet and navigate to the test website
2. Place a order then cancel it
```

## Context

User may also use 0x Instant in mobile wallets

## Your Environment

| Package | Version |
|---------|--------|
| 0x Instant | https://instant.0xproject.com/instant.js |

| Network |
|---------|
| mainnet  |

**Comment by BMillman19** [comment]
@hewigovens thanks for the report, will be looking into it today

**Comment by BMillman19** [comment]
@hewigovens try this link out: http://0x-instant-staging.s3-website-us-east-1.amazonaws.com/

**Comment by BMillman19** [comment]
@hewigovens btw, can we rely on `TrustWeb3Provider` as a stable constructor name for us to identify the provider as trust wallet or is there some recommended way?

**Comment by hewigovens** [comment]
@BMillman19 Yes, `TrustWeb3Provider` is also used in MyCrypto.com to identify Trust Wallet

**Comment by hewigovens** [comment]
And thanks for the fix, It works!

**Comment by BMillman19** [comment]
hey @hewigovens what error do you guys throw when the signature gets denied?

**Comment by hewigovens** [comment]
@BMillman19 right now only a simple "cancelled"

**Comment by BMillman19** [comment]
@hewigovens this should be fixed!
