### ISSUE TITLE
Forwarding Contract Is Not Verified On Etherscan

### ISSUE THREAD

**Issue by pointtoken** [0xProject/0x-monorepo#1460]
The forwarding contract is not verified on Etherscan: https://etherscan.io/address/0x5468a1dc173652ee28d249c271fa9933144746b1

Even worse, the contract name displays a series of wingdings.

All of this adds doubt to users who are inspecting the contract. 

This is radically different from the experience with the Exchange contract, https://etherscan.io/address/0x4f833a24e1f95d70f028921e27040ca56e09ab0b which has lots of custom properties that give users confidence in the contract.

**Comment by dekz** [comment]
YES GOT IT!

https://etherscan.io/address/0x5468a1dc173652ee28d249c271fa9933144746b1#code.

Now onto discussing the weird Ascii characters showing up.
