### ISSUE TITLE
Upgrade to solidity ^0.5.0?

### ISSUE THREAD

**Issue by WyseNynja** [0xProject/0x-monorepo#1477]
What are the plans for upgrading the solidity version?

It's a big undertaking (https://solidity.readthedocs.io/en/v0.5.2/050-breaking-changes.html), but there are some tools to help automate it (https://mudit.blog/tool-refactor-your-solidity-0-4-x-code-to-solidity-0-5-x-code/).

Truffle and OpenZepplin both have branches that support 0.5, but it doesn't look like they are fully released yet.

**Comment by dekz** [comment]
Thanks for the links @WyseNynja. We will likely look to use 0.5.x in newer versions of the contracts, but previously deployed versions will remain the same. Our tooling will be updated soon to support 0.5.x.

**Comment by LogvinovLeon** [comment]
We're blocked on [that](https://github.com/ethereum/solc-js/issues/321) solc-js bug

**Comment by LogvinovLeon** [comment]
Ok, it was our fault. PR's comming
