### ISSUE TITLE
How to build 0x smart contracts?

### ISSUE THREAD

**Issue by bojan96** [0xProject/0x-monorepo#1483]
I have problem building 0x smart contracts. 

I tried using these commands as specified by the docs:

```
yarn install
PKG=@0x/contracts yarn build
```
but I get: 

```
yarn run v1.12.3
$ wsrun build $PKG --fast-exit -r --stages --exclude-missing
Warning: packages/contracts is a directory, but has no package.json
Warning: packages/devnet is a directory, but has no package.json
Warning: packages/forwarder-helper is a directory, but has no package.json
Warning: packages/sra-report is a directory, but has no package.json
Warning: packages/verdaccio is a directory, but has no package.json
Stopping 0 active children
Done in 2.16s.

```
No contracts are built.

**Comment by fabioberger** [comment]
@bojan96 the contracts package has been refactored into multiple smaller packages nested under the top-level `contracts` directory. Please try `PKG=@0x/contracts-protocol yarn build`

**Comment by LogvinovLeon** [comment]
@bojan96 Which docs? Could you please post a link so I can fix them?

**Comment by bojan96** [comment]
@fabioberger Note I am trying to build contracts from master branch, I assumed it contains stable v2 protocol code(Am I wrong?). Also note I am trying to build it from Git Bash terminal on Windows.
@LogvinovLeon [README.md](https://github.com/0xProject/0x-monorepo/blob/master/README.md), on master branch.

**Comment by fabioberger** [comment]
@bojan96 can you try `development` branch?

**Comment by bojan96** [comment]
@fabioberger  I switched to `development `branch and ran `PKG=@0x/contracts-protocol yarn build` as you suggested but result is same:

```
yarn run v1.9.4
$ wsrun build $PKG --fast-exit -r --stages --exclude-missing
Warning: packages/contracts is a directory, but has no package.json
Warning: packages/devnet is a directory, but has no package.json
Warning: packages/verdaccio is a directory, but has no package.json
Stopping 0 active children
Done in 1.40s.
```

**Comment by bojan96** [comment]
Well I managed to build all packages including smart contracts on `master ` branch, by using Windows Subsystem for Linux, I ran `yarn install` followed by `yarn build`, same procedure does not work on Windows when tried from Git Bash.
