### ISSUE TITLE
Consider using prettier-solidity

### ISSUE THREAD

**Issue by fvictorio** [0xProject/0x-monorepo#1486]
Hi, I'm a contributor in the [solidity plugin for prettier](https://github.com/prettier-solidity/prettier-plugin-solidity). The project is in a very early stage, but I think it's close to a beta. Given that, it would be very helpful to have some projects like this give it a try.

Since you already use prettier, and since it seems that tooling is important to you (as authors of `sol-cover` and others), maybe you are interested in giving it a try? If that's the case, I could make a PR with it (after solving some pending issues we have).

Thanks!

**Comment by LogvinovLeon** [comment]
We have actually tried it before but there were some issue we've run into (already reported on your repo). We'd be happy to give it a second try when those are solved.
