### ISSUE TITLE
Forwarder transferERC721Token back reverted

### ISSUE THREAD

**Issue by han0110** [0xProject/0x-monorepo#1505]
## Expected Behavior

When I call Forwarder `marketBuyOrdersWithEth` to buy an order with CryptoKitties as makerAsset, I only need sufficient ETH balance to fill the order and get that asset.

## Current Behavior

The transaction is reverted.

After order filled, Forwarder calls `transferFrom` to CryptoKitties contract, but this internal transaction is reverted.

The reason reverted is because CryptoKitties' `transferFrom` requires `msg.sender` to be approved even if `msg.sender` is the owner.

```solidity
// CryptoKitties contract
// https://etherscan.io/address/0x06012c8cf97bead5deae237070f9587f8e7a266d#code

// line 523
function _approvedFor(address _claimant, uint256 _tokenId) internal view returns (bool) {
    return kittyIndexToApproved[_tokenId] == _claimant;
}

...

// line 605
function transferFrom(
    address _from,
    address _to,
    uint256 _tokenId
)
    external
    whenNotPaused
{
    ...
    require(_approvedFor(msg.sender, _tokenId));
    ...

    _transfer(_from, _to, _tokenId);
}
```

## Possible Solution

Make the function `transferERC721Token` In `0x-monorepo/contracts/extensions/contracts/Forwarder/MixinAssets.sol` support different logics flow of function `transferFrom` in different ERC721 contracts.

```solidity
// 0x-monorepo/contracts/extensions/contracts/Forwarder/MixinAssets.sol
// https://github.com/0xProject/0x-monorepo/blob/6c22594882c94146519ec6e3b24d558127bd092c/contracts/extensions/contracts/Forwarder/MixinAssets.sol#L122

function transferERC721Token(
    bytes memory assetData,
    uint256 amount
)
    internal
{
    require(
        amount == 1,
        "INVALID_AMOUNT"
    );
    // Decode asset data.
    address token = assetData.readAddress(16);
    uint256 tokenId = assetData.readUint256(36);

    // Currently we perform transferFrom directly
    // Perform transfer.
    // IERC721Token(token).transferFrom(
    //     address(this),
    //     msg.sender,
    //     tokenId
    // );

    // Possible solution
    // Perform raw approve first
    token.call(abi.encodeWithSelector(
        ERC721_APPROVE_SELECTOR,
        address(this),
        tokenId,
    ));
    // Then perform raw transferFrom
    bool success = token.call(abi.encodeWithSelector(
        ERC721_TRANSFER_FROM_SELECTOR,
        address(this),
        msg.sender,
        tokenId,
    ));
    // Check return data
    assembly {
        if returndatasize {
            success := 0
            if eq(returndatasize, 32) {
                // First 64 bytes of memory are reserved scratch space
                returndatacopy(0, 0, 32)
                success := mload(0)
            }
        }
    }
    require(
        success,
        "TRANSFER_FAILED"
    );
}
```

## Your Environment

| Network |
| ------- |
| mainnet |

**Comment by dekz** [comment]
This is due to CryptoKitties not following the ERC721 spec correctly. Excerpt from the spec:

```
/// @dev Throws unless `msg.sender` is the current owner, an authorized
///  operator, or the approved address for this NFT. Throws if `_from` is
///  not the current owner. Throws if `_to` is the zero address. Throws if
///  `_tokenId` is not a valid NFT.
function transferFrom(address _from, address _to, uint256 _tokenId) external payable;
```

I think the best options are:
* Encourage CryptoKitties to fully support ERC721
* Deploy a custom CK Forwarder for this work around until they are ERC721 compliant

Charle's from Boxswap has also been digging around this issue so I'll ping him to join this conversation.

**Comment by han0110** [comment]
Thank you for replying! Totally agree, I think the most practical way now to handle custom ERC721 spec is to deploy custom Forwarders, which call `transfer` directly or call `approve` + `transferFrom`. But still wondering if there is any possibility to realize a "universal" Forwarder to help buy any ERC721.

**Comment by dekz** [comment]
`transfer` is not part of the ERC721 spec, only `transferFrom` and `safeTransferFrom` are defined. So simply calling `transfer` would not work with any token that implements ERC721. I think a custom forwarder is our only option.

**Comment by han0110** [comment]
Yeah, but I tried the work calling `approve` first, then found some NFT like Axie, will revert if we `approve` to current owner. Things will work but the transaction on etherscan looks not good. It seems to be too many situations to handle🤦‍♂️. 

I think I will just call custom Forwarder calling `transfer` for legacy NFT like CK, CryptoFighters, and call 0x Forwarder for NFT which follows ERC721 spec to avoid extra gas cost. After all, trending NFTs not following ERC721 spec are minority.

Thanks!

**Comment by charlesmarino** [comment]
I'm also for custom forwarder for each NFT spec over a universal one. IMO universal would be harder to manage, more buggy, and more gas-cost.

**Comment by han0110** [comment]
Got it, thanks for these suggestions! I will go for custom Forwarders for legacy NFTs. close this issue.

**Comment by pointtoken** [comment]
It is worth noting that you can use the exchange contract to transfer cryptokitties. It means that you have to have the buyer approve WETH to complete the transfer, but it works. @han0110  if you create a forwarding contract for cryptokitties, can you share the address so others can use it? thx
