### ISSUE TITLE
Dev tools don't work with Ganache

### ISSUE THREAD

**Issue by LogvinovLeon** [0xProject/0x-monorepo#1520]
0x Dev tools currently don't work with ganache because of a couple of issues.
This is a meta-issue to track progress on those:

- [x] https://github.com/trufflesuite/ganache-core/issues/280

**Comment by davidmurdoch** [comment]
Hey there, stalebot! Don't close this 😀

**Comment by LogvinovLeon** [comment]
Update https://github.com/trufflesuite/ganache-core/issues/280 is fixed in the newest Ganache and I was just able to successfully use @0x/sol-trace on a truffle project with Ganache.

**Comment by LogvinovLeon** [comment]
Update:
I was able to work around https://github.com/trufflesuite/ganache-core/issues/277 and as soon as https://github.com/0xProject/0x-monorepo/pull/1647 gets in - all the dev tools will support Ganache.

**Comment by WyseNynja** [comment]
This is great @LogvinovLeon ! Having sol-trace against my own ganache instance has been super helpful.

It looks like the next step is updating the docs at https://sol-trace.com/ and the other sites.

**Comment by 0xGabi** [comment]
Hi, do I need to build it myself or is available from npm module? Also do I need to have the `solc` version that I pass to `TruffleArtifactAdapter` installed in my machine. Thanks for the help

**Comment by fabioberger** [comment]
Dev tools now work with Ganache.

**Comment by fabioberger** [comment]
@0xGabi if you are still having issues, please open a new issue.
