### ISSUE TITLE
Error while using sol-coverage: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by hoytech** [0xProject/0x-monorepo#1530]
Basically as the title says. There's some ridiculous java-esque stack trace, here is the top:

<pre>
TypeError: Cannot read property 'range' of null
    at ASTVisitor._shouldIgnoreExpression (XXX-contract/node_modules/@0x/sol-tracing-utils/src/ast_visitor.ts:182:29)
    at ASTVisitor._visitStatement (XXX-contract/node_modules/@0x/sol-tracing-utils/src/ast_visitor.ts:165:18)
    at ASTVisitor.ExpressionStatement (XXX-contract/node_modules/@0x/sol-tracing-utils/src/ast_visitor.ts:92:14)
</pre>

I was able to fix it by adding:

<pre>    if (ast === null) return true;</pre>

to the top of the `_shouldIgnoreExpression` method in `ast_visitor.ts`.

Not sure if I have some weird solidity or something. It's possible, but I don't think I have anything that unusual.

After that change the report was generated OK and it looks pretty cool, so thanks!

**Comment by LogvinovLeon** [comment]
Thanks for reporting. Could you please attach the example contract where it happens? I'd like to know if it should be fixed on our side or on the AST parser side.

**Comment by hoytech** [comment]
If I have some time in the future I'll try to build up a minimal test-case for this, but a bit busy at the moment.

**Comment by hoytech** [comment]
Thank you for addressing all these, I'll report back if I find any issues. Cheers!
