### ISSUE TITLE
sol-trace error a bit confusing

### ISSUE THREAD

**Issue by hoytech** [0xProject/0x-monorepo#1531]
Basically I was running sol-coverage and I messed up and was deploying a different bytecode than was compiled with sol-compiler. I saw some errors like `Unknown contract creation transaction` and `Transaction to an unknown address: ...` which of course I just ignored.

Took me a while to figure out why it couldn't match the bytecode because those messages above took place after the contracts were successfully loaded by the `SolCompilerArtifactAdapter` (or so I thought).

Anyway I would've figured this out way faster if `getContractDataIfExists` warned that it couldn't find a bytecode.

**Comment by hoytech** [comment]
After thinking about this one a bit more, I don't think there's really anything you can do, it was my screw-up. Maybe changing those "Transaction to an unknown address" to say *why* the address is unknown? Ideally it would say "sol-coverage: Was unable to find matching bytecode for contract creation 0xXYZ, ignoring..." or something.

**Comment by LogvinovLeon** [comment]
Agree, I would make an error message better and more visible. Ideally, it should never happen when you develop unless you call some contracts you don't have the artifacts for (which is a marginal use-case).
