### ISSUE TITLE
sol-compiler is slow

### ISSUE THREAD

**Issue by hoytech** [0xProject/0x-monorepo#1532]
I guess it uses the emscripten version of the solidity compiler?

With the same number of optimizer runs, sol-compiler takes 15 seconds on a file, compared to the native `solc` which takes 2 seconds.

Do you guys for real develop like that, or is there a way to make it use `solc`?

**Comment by LogvinovLeon** [comment]
I just realized that we really do. We've had it on the backlog for ages, but never done that. Now, this tool is public and we have much more contracts so I will prioritize getting that feature in. Thanks for pointing it out.
