### ISSUE TITLE
0x Instant orderSource not support raw JSON

### ISSUE THREAD

**Issue by robinpan1** [0xProject/0x-monorepo#1540]
0x Instant currently not support to pass raw JSON orders to `orderSource`.

 If I do so, I will get an error message on 0x Instant after selecting a token and typing in the amount to buy:

> **Error fetching price, please try again.**

 
To fix this, one needs to include BigNumber and converts the orders into the right types specifically:

  `<script src="https://unpkg.com/bignumber.js@4.1.0/bignumber.js"> </script>`

```
const signedOrders = [
  {
    ...
    "exchangeAddress": "0x35dd2932454449b14cee11a94d3674a936d5d7b2",
    "makerAssetAmount": new BigNumber("1000000000000000000"),
    "takerAssetAmount": new BigNumber("400000000000000000"),
    ...
  }]
```

Since the result signedOrders generated by 0x.js are raw JSON, it is more convenient that `orderSource` can support it that way.

**Comment by fragosti** [comment]
Hi @RobinPan-TW, we are actually working on this right now so watch out for the next instant update! However, not sure what you are referring to when you are referring to `signedOrders`, our `SignedOrder` type does use `BigNumber`. https://0x.org/docs/0x.js#types-SignedOrder

**Comment by ogsalman** [comment]
![](https://cdn.discordapp.com/attachments/436256771175088148/543224816719757354/unknown.png)
I'm getting this issue even though I'm using BigNumbers properly where they should be used...

![image](https://user-images.githubusercontent.com/10134851/52451709-1f872d80-2b0e-11e9-9dda-824dc4e7ae3a.png)

**Comment by ogsalman** [comment]
@fragosti please help!

**Comment by BMillman19** [comment]
@ogsalman the issue is with how the salt is going from bignumber to string, looks like it is being converted into scientific notation

As @fragosti mentioned, we are working on expanding the interface to make this use case easier and you should be able to just pass in strings, we will ping this issue when the fix is deployed

**Comment by fragosti** [comment]
@ogsalman this should be fixed now. let me know what you're seeing.
