### ISSUE TITLE
Order watcher websocket server: required information not available

### ISSUE THREAD

**Issue by virtualmotion** [0xProject/0x-monorepo#1564]
When connecting to the 0x order watcher web socket server it is not possible to determine three required variables -- (1) if the order watcher has successfully connected to a node, (2) if it is syncing properly with the node and (3) the health of that node (getting the latest block number, for example).

**Comment by fabioberger** [comment]
@virtualmotion, we have a `GET_STATS` method that currently just returns the number of orders being watched. We could extend it to also return the latest block number and any other stats you would like. Let's figure out what you need and then you could either submit a PR or someone from the core team could implement it.

**Comment by fabioberger** [comment]
@virtualmotion any update on this?
