### ISSUE TITLE
Can't call into contract method taking an array of structs

### ISSUE THREAD

**Issue by feuGeneA** [0xProject/0x-monorepo#1574]
## Expected Behavior

Be able to call `Exchange.marketBuyOrders()` without raising an exception.

## Current Behavior

Making this call results in an exception: `ValueError: No matching entries for 'tuple' in encoder registry`.  (Interestingly, this is the same exception given when there is no tuple support.)

## Solution

The problem is that our fork of web3.py isn't supporting arrays of tuples.  We need to modify `web3._utils.abi.get_abi_inputs()` to be able to detect arrays of tuples in addition to single tuples.

## Steps to Reproduce

Add the following line to `zero_ex.contract_demo.test.test_exchange.test_get_order_info()`:

```
    fill_results = FillResults(*exchange.call().marketBuyOrders([order], 1, b""))
```

## Context

Discord user frak, working for CoinAlpha, contacted me about this problem.  They are getting signedOrders from RadarRelay and trying to fill them using `marketBuyOrders`.  They have a workaround, calling `fillOrder` multiple times.

But this problem is more general than just supporting `marketBuyOrders`.  The problem affects all methods that take or return arrays of structs.  Skimming our contract docs, that's about 10 methods on the `Exchange` contract.

**Comment by benjyz** [comment]
@officialcryptomaster if its a deal-breaker I want to signal my support here, so that we can grow the python ecosystem. apparently this relates to web3.py and hopefully can be fixed there

https://github.com/0xProject/0x-protocol-specification/blob/master/v2/v2-specification.md#batchfillorkillorders

**Comment by michaelhly** [comment]
I agree with everyone here. Without tuple support, you can't do anything with an array of orders in python.

**Comment by feuGeneA** [comment]
To be clear, the place to implement this support is in the Ethereum foundation's web3.py library.  We can implement it in our fork, to get things working sooner rather than later, but ultimately, in order to make life easy, we need full tuple support (including support for arrays of them) in the mainline web3.py library. See https://github.com/ethereum/web3.py/issues/829

**Comment by officialcryptomaster** [comment]
@feuGeneA Any workaround you can suggest would be great because honestly this is a pretty major roadblock for the python eco-system and we are very motivated to have some sort of workaround as python web3 moves too slow...

**Comment by feuGeneA** [comment]
@officialcryptomaster @michaelhly @benjyz I've released a new version of the `0x-web3` package on PyPI, which includes support for tuple arrays, and you can go ahead and use that, without waiting for resolution of this Issue (or the linked PR).

The PR does contain one additional useful change, adding to order utils a dependency on `0x-web3` rather than `web3`, which should help manage the dependencies better when first installing it.

**Comment by officialcryptomaster** [comment]
@feuGeneA This is great news! thank you!
