### ISSUE TITLE
python exchange test and web3 issue

### ISSUE THREAD

**Issue by virtualmotion** [0xProject/0x-monorepo#1577]
https://github.com/0xProject/0x-monorepo/blob/development/python-packages/contract_demo/test/test_exchange.py#L48

I get an error on line 48 when I try to run this: 
AttributeError: module 'web3.utils.datatypes' has no attribute 'Contract'

Upon looking up web3.utils.datatypes, it does not appear to have Contract.
https://github.com/ethereum/web3.py/blob/master/web3/_utils/datatypes.py

**Comment by feuGeneA** [comment]
I have seen that message before, as a warning or linter error or something, but that code runs regularly as part of our continuous integration test suite, so I'm relatively confident that it works. Can you provide any more context to help diagnose?
