### ISSUE TITLE
order utils - tuple encoding

### ISSUE THREAD

**Issue by benjyz** [0xProject/0x-monorepo#1588]
running the example test_exchange.py I get:
 
`ValueError: No matching entries for 'tuple' in encoder registry
`

see https://github.com/ethereum/web3.py/issues/1065

**Comment by benjyz** [comment]
can be fixed by installing eth-utils 1.4.0 (and removing 1.4.1)

**Comment by fabioberger** [comment]
This should be fixed now that Web3.py merged support for this right @feuGeneA?

**Comment by feuGeneA** [comment]
@fabio I don't think that's relevant here.  This message can be avoided by either using that latest Web3.py or by using `0x-order-utils` and its underlying `0x-web3` fork.

This error message indicates to me that the `0x-order-utils` package hasn't been installed properly. 
 Uninstalling and reinstalling would likely help.

However, @benjyz, I believe you're up and running and this isn't actually a problem for you anymore; is that right?  Closing this Issue for now; please re-open if it's really still an outstanding problem.
