### ISSUE TITLE
sol-compiler getCompilerOutputsAsync looks for artifacts unnecessarily

### ISSUE THREAD

**Issue by frangio** [0xProject/0x-monorepo#1597]
I'm writing a program that only uses `getCompilerOutputsAsync`, i.e. it never writes to disk any artifacts. Yet, on every run a log `Artifact for Foo does not exist` is printed.

Could there be any way to disable looking for artifacts or logging when they're not found?

**Comment by LogvinovLeon** [comment]
I can disable logging, but are you sure you want to disable looking for artifacts too?
If you run your program twice in a row you probably want the second run to be faster and not recompile the stuff that had not changed.

**Comment by frangio** [comment]
The thing is, as far as I can tell, if I'm always using `getCompilerOutputsAsync` there are never any artifacts created. If the logging is disabled then I wouldn't mind it if the library looked for artifacts.
