### ISSUE TITLE
Forwarding Contract Has WingDings on Etherscan

### ISSUE THREAD

**Issue by pointtoken** [0xProject/0x-monorepo#1598]
The forwarding contract https://etherscan.io/address/0x5468a1dc173652ee28d249c271fa9933144746b1 has these suspicious looking wingdings when browsed to on etherscan:

```

  | �y� #DEFAULT_FUNCTION_WETH_CONTRAC... (�y� #DEFA...)

```
This makes users browsing the contract suspicious of its trustworthiness.

**Comment by fabioberger** [comment]
Thanks for letting us know. I forwarded this issue to the Etherscan team.
