### ISSUE TITLE
python exchange test: network id

### ISSUE THREAD

**Issue by benjyz** [0xProject/0x-monorepo#1599]
here an invalid network id is returned (e.g. net version  1549593381851). replacing with 42 or some valid network id works(?)

https://github.com/0xProject/0x-monorepo/blob/development/python-packages/contract_demo/test/test_exchange.py#L39

**Comment by feuGeneA** [comment]
What you're describing is a problem with `web3.py`, not any 0x code.  That is, if `web3_instance.net.version` is returning `1549593381851` then that's outside of our purview.  Please re-open if I've misunderstood.
