### ISSUE TITLE
python: order utils sign order

### ISSUE THREAD

**Issue by benjyz** [0xProject/0x-monorepo#1606]
order_utils doesn't have a sign_order function afaics. it would be helpful to introduce an abstraction somewhere similar to radar relay SDK

**Comment by benjyz** [comment]
something like helps
```

def prepare_order(order):
    """ prepare the order for submit """
    order_struct = jsdict_order_to_struct(order)    
    sig = sign_order(order_struct)
    order_struct["signature"] = sig
    js_order = order_to_jsdict(order_struct)
    js_order["exchangeAddress"] = exchangeAddress
    return js_order
```

**Comment by feuGeneA** [comment]
Signing an order really just means signing a hash of the order.

To get a hash of the order, you can either use [generate_order_hash_hex()](http://0x-order-utils-py.s3-website-us-east-1.amazonaws.com/#zero_ex.order_utils.generate_order_hash_hex), which will do it all in-process in Python, or you can call [the smart contract method `Exchange.getOrderInfo()`](https://0x.org/docs/contracts#Exchange-getOrderInfo), whose return value includes the hash.

Once you have the hash, you can get a signature of the hash via [`sign_hash()`](http://0x-order-utils-py.s3-website-us-east-1.amazonaws.com/#zero_ex.order_utils.sign_hash), and then you can plug that signature into the order dict just like you showed in your last comment.

Feel free to re-open if this doesn't clarify things for you.
