### ISSUE TITLE
sol-compiler: Lock compiler version

### ISSUE THREAD

**Issue by liamzebedee** [0xProject/0x-monorepo#1640]
I couldn't find this in the documentation or the code, but it would be great to know how to lock the version of solc used in sol-compiler. 

## Expected Behavior
`"solcVersion": "0.5.0"` in `compiler.json` uses the 0.5.0 tag of solc and only downloads if it wasn't cached previously.

## Current Behavior
Not downloading the compiler per that version.

## Possible Solution
 - update docs if option already exists

## Your Environment
```
"@0x/sol-compiler": "^3.0.3",
```

**Comment by LogvinovLeon** [comment]
@liamzebedee This option already exists and it's called `solcVersion`. It's documented [here](https://0x.org/docs/sol-compiler#types-CompilerOptions)

**Comment by LogvinovLeon** [comment]
I will close this. But feel free to reopen if you have any more questions about that

**Comment by liamzebedee** [comment]
Ah - I definitely misunderstood the option then.

**Comment by liamzebedee** [comment]
Is it possible to cache the most recent compiler version downloaded? Can't compile without wifi on the train 🚝

**Comment by LogvinovLeon** [comment]
@liamzebedee It is. You need to set `isOfflineMode` option to true in `compiler.json`
