### ISSUE TITLE
sol-compiler requires file name be same as contract

### ISSUE THREAD

**Issue by frangio** [0xProject/0x-monorepo#1642]
There is a weird design decision in `sol-compiler` to require files to be named like the contract they include. Would you mind explaining why this was decided?

I think the restriction should be removed as it's not a language constraint, even if it is common practice.

**Comment by LogvinovLeon** [comment]
This makes things simpler for us. I think it's a good practice. Why do you want it removed? I've just tried to compile the openzeppelin repo with sol-compiler and it compiled successfully.

**Comment by frangio** [comment]
I'm trying to build a tool that should work on other projects, and I don't want the tool to break for users in this scenario. I ended up running solc manually along with resolver-engine. Thanks for the reply!

**Comment by LogvinovLeon** [comment]
I don't think there is anything stopping us from supporting it technically, but it's some additional work. If you'd like to contribute - I'm happy to review. But if not - I don't think that's high enough on my priority list as of now.

**Comment by frangio** [comment]
> I've just tried to compile the openzeppelin repo with sol-compiler and it compiled successfully.

Actually, @LogvinovLeon, are you sure about this? We do have some auxiliary Solidity files we use for testing that don't following this file naming convention. For example [`SafeERC20Helper`](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/mocks/SafeERC20Helper.sol).

I wouldn't expect the OpenZeppelin repo to compile correctly unless those files are being ignored somehow. And then if it does compile correctly, there would be missing artifacts that are needed in the test suite.
