### ISSUE TITLE
Cannot read property undefined in sol-compiler

### ISSUE THREAD

**Issue by PaulRBerg** [0xProject/0x-monorepo#1645]
## Expected Behavior

Contracts should be compiled correctly when the `compilerSettings` are set in `compiler.json`.

## Current Behavior

The following error is returned:

> TypeError: Cannot read property 'Numbers' of undefined

## Possible Solution

Well, if I remove the `compilerSettings` from `compiler.json` or the config file altogether, everything works fine. Perhaps tweaking the way the settings are interpreted would solve this issue.

## Steps to Reproduce

```
1. git clone git@github.com:PaulRBerg/sol-compiler-bug.git
2. cd sol-compiler-bug
3. npx @0x/sol-compiler
```

## Context

This has originally occurred in the [AZTEC][aztec-monorepo] repo, in the "protocol" package on the "feat-coverage" branch, but the behaviour is exactly the same in the [bug repo][bug-repo] I created.

## Your Environment

| Tool | Version |
| :--------: | :--------: |
| @0x/sol-compiler | 3.1.0 |
| npm | 6.7.0 |
| node | 10.15.0 |

[aztec-monorepo]: https://github.com/AztecProtocol/AZTEC/tree/feat-coverage
[bug-repo]: https://github.com/PaulRBerg/sol-compiler-bug/tree/bug-cyclical

**Comment by LogvinovLeon** [comment]
Thanks for a repro. I'm able to repro. Looking into it

**Comment by LogvinovLeon** [comment]
Ok. So there are two things here:
1. You should use `Numbers.sol` instead of `contracts/Numbers.sol` in compiler.json
2. The bug on our end: https://github.com/0xProject/0x-monorepo/pull/1652
