### ISSUE TITLE
Cyclical dependency in solidity causes maximum call stack size exceeded

### ISSUE THREAD

**Issue by PaulRBerg** [0xProject/0x-monorepo#1648]
## Expected Behavior

Contracts should be compiled correctly even if they have cyclical dependencies.

## Current Behavior

The following error is thrown:

> RangeError: Maximum call stack size exceeded

Which is confusing because this error is normally caused by [using too many variables][stackexchange-answer] within a function.
 

## Possible Solution

Prevent the contracts from infinitely importing each other. Not sure how Truffle accomplishes this, but cyclical dependencies work fine there.

## Steps to Reproduce

```
1. git clone git@github.com:PaulRBerg/sol-compiler-bug.git
2. cd sol-compiler-bug
3. git checkout bug-cyclical
4. npx @0x/sol-compiler
```

## Context

This has originally occurred in the [AZTEC][aztec-monorepo] repo, in the "protocol" package on the "feat-coverage" branch, but the behaviour is exactly the same in the [bug repo][bug-repo] I created.

The last commit on AZTEC though nuked all cyclical dependencies, so do not go there if you want to reproduce this bug.

## Your Environment

| Tool | Version |
| :--------: | :--------: |
| @0x/sol-compiler | 3.1.0 |
| npm | 6.7.0 |
| node | 10.15.0 |

[aztec-monorepo]: https://github.com/AztecProtocol/AZTEC/tree/feat-coverage
[bug-repo]: https://github.com/PaulRBerg/sol-compiler-bug/tree/bug-cyclical
[stackexchange-answer]: https://ethereum.stackexchange.com/questions/23720/usage-of-memory-storage-and-stack-areas-in-evm/23722#23722

**Comment by LogvinovLeon** [comment]
To be honest - I will most probably not have time to look into that for the next couple of weeks because of other projects and aggressive deadlines, but if you would find time to submit a PR - I will review, merge and publish it.

**Comment by PaulRBerg** [comment]
Thank you, we ended up removing the cyclical dependency altogether, so I reported this just to signal the existence of the problem. If I'll find some spare time though, I'll have a look as I wanted to play around with TypeScript for a while.

**Comment by akuanti** [comment]
I would really like to use this tool, but I'm running into this issue as well.

**Comment by fabioberger** [comment]
@akuanti are you able to remove the cyclical dependency?

**Comment by akuanti** [comment]
@fabioberger unfortunately, that isn't an option at the moment.

**Comment by ochikov** [comment]
I am running into this issue too. Is there an option to solve it ?
