### ISSUE TITLE
[sol-cov] Coverage is not working for versions ^0.5.1 of solidity

### ISSUE THREAD

**Issue by PaulRBerg** [0xProject/0x-monorepo#1650]
## Expected Behavior

The coverage report should be generated for versions 0.5.1 and above of solidity.

## Current Behavior

The coverage report is blank:

![@0x/sol-coverage][bug-img-url]

If you bump the solidity version to 0.5.2, 0.5.3 or 0.5.4 (state-of-the-art as of 26th Feb 2019), nothing changes. If you revert to 0.5.0 in `truffle-config` and the contract's pragmas, everything works okay.

## Steps to Reproduce

```
1. git clone git@github.com:PaulRBerg/sol-coverage-bug.git
2. cd sol-coverage-bug
3. npm install
4. npm run coverage
```

## Context

This has originally occurred in the [AZTEC][aztec-monorepo] repo, in the "protocol" package on the "feat-coverage" branch, but the behaviour is exactly the same in the [bug repo][bug-repo] I created.

## Your Environment

| Tool | Version |
| :--------: | :--------: |
| @0x/sol-coverage | 2.0.4 |
| solidity | 0.5.1 |
| npm | 6.7.0 |
| node | 10.15.0 |

[aztec-monorepo]: https://github.com/AztecProtocol/AZTEC/tree/feat-coverage
[bug-img-url]: https://i.imgur.com/cJ7wLp1.png
[bug-repo]: https://github.com/PaulRBerg/sol-coverage-bug

**Comment by LogvinovLeon** [comment]
I've cloned your repo. Ran coverage. Saw a bunch of warnings from sol-coverage not being able to match bytecode.
<img width="908" alt="screen shot 2019-02-26 at 3 32 45 pm" src="https://user-images.githubusercontent.com/6204356/53454370-c9eec400-39db-11e9-920c-8d22a5a0b76a.png">

Started looking into that:
* Compiler contracts with truffle using `truffle compile`.
* Compiler contracts with remix.
* Compiled contracts with sol-compiler.

It looks like truffle produces a different bytecode.
I don't know where does it come from, but:
Sol-compiler and remix produce that:
`0x608060405234801561001057600080fd5b5060e38061001f6000396000f3fe6080604052600436106043576000357c010000000000000000000000000000000000000000000000000000000090048063c2985578146048578063dc80035d146070575b600080fd5b348015605357600080fd5b50605a60a7565b6040518082815260200191505060405180910390f35b348015607b57600080fd5b5060a560048036036020811015609057600080fd5b810190808035906020019092919050505060ad565b005b60005481565b806000819055505056fea165627a7a7230582083aa0851849d4fd41fe8eaf6ce1a9946a504bb21308acf62dfb3905c5bd9024e0029`

While truffle produces that:
`0x608060405234801561001057600080fd5b5060ca8061001f6000396000f3fe6080604052600436106042577c01000000000000000000000000000000000000000000000000000000006000350463c298557881146047578063dc80035d14606b575b600080fd5b348015605257600080fd5b5060596093565b60408051918252519081900360200190f35b348015607657600080fd5b50609160048036036020811015608b57600080fd5b50356099565b005b60005481565b60005556fea165627a7a72305820ba922a07ff8ca9ed31dca7bb36adc114dcfef3805342d15136ee10af54e4956f0029`

So it seems like a truffle issue to me.
I know that the last couple of bytes of bytecode is the solidity compiler metadata and you can't just compare them by strict equality. We use fuzzy comparasion in sol-coverage. But those differ not in the last couple of bytes.

**Comment by LogvinovLeon** [comment]
Somehow sol-compiler doesn't pick up the info that the optimizer is enabled. Working on a fix

**Comment by LogvinovLeon** [comment]
Ok. It was caused by a breaking change in `truffle.json` format.
Before it had `solc` key, but now it's nested under the `compilers.solc`.
WIll release the fix soon.

**Comment by ochikov** [comment]
I am still getting issue with coverage. The coverage.json file is empty. No matter if I change the version of solidity to be 0.5.0, the file is empty. I use @PaulRBerg repository. Thank you.
