### ISSUE TITLE
order-utils: Order Interface can't handle large salts

### ISSUE THREAD

**Issue by aakilfernandes** [0xProject/0x-monorepo#1670]
## Expected Behavior

Create an order interface with a salt of 2^256 - 1

## Current Behavior

`Validation errors: instance.salt is not any of [subschema 0],[subschema 1]`

## Possible Solution

Replace Order interface to accept hex strings (alternatively, use BN.js which I believe can handle numbers that large)

## Your Environment
node v10.0.0

| Package | Version |
|             `0x.js` | 6.0.3   |

**Comment by aakilfernandes** [comment]
Come to think of this, this probably effects all BigNumber interfaces. Not just the salt

**Comment by fabioberger** [comment]
@aakilfernandes have you tried passing it in as a string rather then as a number type? That should work, although I agree that it's inelegant.

**Comment by aakilfernandes** [comment]
@fabioberger you mean a hexadecimal encoding? The typescript interface only allows for bignumbers

**Comment by fabioberger** [comment]
@aakilfernandes which method call and order is giving you this error? Mind posting both of them here?

**Comment by aakilfernandes** [comment]
https://github.com/GuildCrypt/makerfacility/blob/master/test/setSignatures.js#L29-L33

The error only shows up for large salts

> Validation errors: instance.salt is not any of [subschema 0],[subschema 1]

**Comment by fabioberger** [comment]
I see you are using your own BigNumber dep. Do you configure it with:

```
BigNumber.config({
    // By default BigNumber's `toString` method converts to exponential notation if the value has
    // more then 20 digits. We want to avoid this behavior, so we set EXPONENTIAL_AT to a high number
    EXPONENTIAL_AT: 1000,
});
```

?
