### ISSUE TITLE
Problem importing 'assert_valid'

### ISSUE THREAD

**Issue by StephenFiser** [0xProject/0x-monorepo#1687]
I have run `pip install 0x-order-utils`, and I'm on version 1.1.1

When I try to `import zero_ex.order_utils` I get:

`ImportError: cannot import name 'assert_valid' from 'zero_ex.json_schemas' (unknown location)`

I tried to install json schemas, but that didn't fix anything. Is there something else I'm missing?

**Comment by feuGeneA** [comment]
Seems to work fine for me:

```
$ mkdir tmp && virtualenv tmp && tmp/bin/pip install 0x-order-utils && tmp/bin/python -c 'import zero_ex.order_utils' && echo $?
Using base prefix '/home/gene/.pythonz/pythons/CPython-3.7.2'
New python executable in /home/gene/dev/tmp/bin/python
Installing setuptools, pip, wheel...
done.
Collecting 0x-order-utils
[...]
Successfully installed 0x-contract-addresses-2.0.1 0x-contract-artifacts-2.0.0 0x-json-schemas-1.0.0 0x-order-utils-1.1.1 0x-web3-4.8.2.1 attrdict-2.0.1 attrs-19.1.0 certifi-2019.3.9 chardet-3.0.4 cytoolz-0.9.0.1 eth-abi-1.3.0 eth-account-0.3.0 eth-hash-0.2.0 eth-keyfile-0.5.1 eth-keys-0.2.1 eth-rlp-0.1.2 eth-typing-2.1.0 eth-utils-1.4.1 hexbytes-0.1.0 hypothesis-4.11.5 idna-2.8 jsonschema-3.0.1 lru-dict-1.1.6 mypy-extensions-0.4.1 parsimonious-0.8.1 pycryptodome-3.7.3 pyrsistent-0.14.11 requests-2.21.0 rlp-1.1.0 six-1.12.0 stringcase-1.2.0 toolz-0.9.0 urllib3-1.24.1 web3-4.8.2 websockets-6.0
0
```

Can you provide any further context to help diagnose?  Can you try to uninstall and reinstall `0x-order-utils`?  Can you try to reproduce in a clean virtualenv, like I did above?

**Comment by StephenFiser** [comment]
Hi again. I had to uninstall everything and reinstall and now it works 👍 

`pip uninstall 0x-contract-artifacts`
`pip uninstall 0x-json-schemas`
`pip uninstall 0x-order-utils`
`pip uninstall 0x-contract-addresses`

`pip install 0x-order-utils==1.1.0`
`pip install 0x-json-schemas==1.0.0`
`pip install 0x-contract-artifacts==2.0.0`
`pip install 0x-contract-addresses==2.0.0`
