### ISSUE TITLE
0x Instant Continues To Hit SRA Endpoint After Being Closed

### ISSUE THREAD

**Issue by pointtoken** [0xProject/0x-monorepo#1694]
If you open up a web console and watch network traffic on any implementation of 0x Instant, the browser starts hammering the SRA server endpoint, even after the 0x instant UI is closed, pinging the orderbook every 5 seconds. What is going on here?

You can witness this on the MyCrypto implementation: https://www.mycrypto.com/swap/0x

**Comment by fragosti** [comment]
Hi @pointtoken thanks for raising the issue. Instant pinging for the orderbook every 5 seconds is definitely expected. It does so to keep the quote price up to date. However, it should not be doing that on close and we will address this in the next release.

**Comment by pointtoken** [comment]
Thanks @fragosti  -- how does one know when instant releases happen to the CDN?

**Comment by fragosti** [comment]
We try to announce releases like that in our Discord. We will have a fix by end of next week if not earlier.

**Comment by BMillman19** [comment]
@pointtoken we just deployed a new version!
