### ISSUE TITLE
OrderWatcher - when OrderState IsValid, OrderRelevantState is not returned

### ISSUE THREAD

**Issue by pointtoken** [0xProject/0x-monorepo#1708]
## Expected Behavior
When using the OrderWatcher, when the callback receives a message and OrderState is valid, the OrderRelevantState property should have a value.

## Current Behavior

When using the OrderWatcher, when the callback receives a message and OrderState is valid, the OrderRelevantState property is null.

## Possible Solution
Not sure why it is null -- we need the order on a valid transaction so we can calculate the remaining available balance in the order for our own purposes.

**Comment by dekz** [comment]
Hmm this sounds strange. It should definitely be populated to tell you the remaining amount. Can you put in some console.logs so we can get some insight into what you're seeing?

**Comment by pointtoken** [comment]
Hmm, things seem to be working!  Closing...
