### ISSUE TITLE
ABI-Encoded strings can have incorrect length header

### ISSUE THREAD

**Issue by gkaemmer** [0xProject/0x-monorepo#1723]
## Expected Behavior

When I use `utils.AbiEncoder.String.prototype.encodeValue("👴🏼")`, the encoded string should have a `length` header of `8`, which is the length of `Buffer.from("👴🏼")` (but not `"👴🏼".length`, which is only 4).

The key problem is that `Buffer.from(string).length` is not always equal to `string.length`.

## Current Behavior

Currently the string encoder uses the string's `.length` property to determine the number of bytes in the encoded value. This number is used as the length header, which causes the EVM to drop characters at the end of strings containing non-ascii characters.

## Possible Solution

Pretty simple fix here: https://github.com/0xProject/0x-monorepo/blob/development/packages/utils/src/abi_encoder/evm_data_types/string.ts#L32

Instead of using `value.length`, this method should use `valueBuf.length`, which always expresses the correct number of bytes in the string.

## Steps to Reproduce (for bugs)
```
import { AbiEncoder } from "@0x/utils";

AbiEncoder.String.prototype.encodeValue("👴🏼").toString("hex");
// Returns:
// 0000000000000000000000000000000000000000000000000000000000000004f09f91b4f09f8fbc000000000000000000000000000000000000000000000000
// Should return: 
// 0000000000000000000000000000000000000000000000000000000000000008f09f91b4f09f8fbc000000000000000000000000000000000000000000000000
```

**Comment by hysz** [comment]
@gkaemmer Thanks for the detailed issue - should be fixed on the `development` branch now.
