### ISSUE TITLE
expirationTimeSeconds of 0

### ISSUE THREAD

**Issue by aakilfernandes** [0xProject/0x-monorepo#1725]
Hey, I'm wondering what the behavior is when expirationTimeSeconds being set to 0. Does it indicate an order that should never expire? Or is it a useless order because the expiration time has already passed?

**Comment by BMillman19** [comment]
I believe it will not be fillable but I'm not 100% sure cc @abandeali1. If you want to create an order that doesn't expire use the max uint256 value

**Comment by abandeali1** [comment]
The `expirationTimeSeconds` is the timestamp for which an order expires, so an order with an `expirationTimeSeconds` would always be expired an unfillable.
