### ISSUE TITLE
Getting wrong value for V (from VRS)

### ISSUE THREAD

**Issue by StephenFiser** [0xProject/0x-monorepo#1741]
Hi there.

I'm trying to get `zero_ex.order_utils.sign_hash()` to work, and I'm getting the following:

```
"Signature returned from web3 provider is in an unknown format."
```

I've tried to walk through the function step-by-step, and I used exactly the example provided:

```
sign_hash(
    ...     provider,
    ...     Web3(provider).personal.listAccounts[0],
    ...     '0x34decbedc118904df65f379a175bb39ca18209d6ce41d5ed549d54e6e0a95004',
    ... )
```

That gave me the same thing I was getting before.

Then I ran

```
maker = Web3(provider).personal.listAccounts[0]
web3.eth.sign(maker, hexstr='0x34decbedc118904df65f379a175bb39ca18209d6ce41d5ed549d54e6e0a95004'.replace("0x", "")).hex()
```

and that gave:
```0x2209d0dd955352a9373a436b68c7ff5b639a31ab746e009073a163b025b634e24c00d9b94ff7f3ff238cfbd857d71bae9579e229ba1084664fb36b5c63d5856c1c```

I set that equal to `sig` and ran `zero_ex.order_utils._parse_signature_hex_as_vrs(sig)` which gave me:

```
{
  'v': 34, 
  'r': '09d0dd955352a9373a436b68c7ff5b639a31ab746e009073a163b025b634e24c', 
  's': '00d9b94ff7f3ff238cfbd857d71bae9579e229ba1084664fb36b5c63d5856c1c'
}
```
Can you shed any light on what might be going on with this?

**Comment by StephenFiser** [comment]
Hi again.

Nevermind. I tried `zero_ex.order_utils._parse_signature_hex_as_rsv(sig)` and got 28. Just realized there were two different functions. Must be a different problem.

**Comment by feuGeneA** [comment]
@StephenFiser Please be wary of using those functions directly.  Note that they have a leading underscore, which indicates that they are implementation details, which means we may make backwards-incompatible changes to them without properly bumping semantic version numbers.

**Comment by StephenFiser** [comment]
@feuGeneA will do. I was just digging into it trying to understand what was going wrong on my end. It looks like `is_valid_signature` was failing because my node was out of sync.
