### ISSUE TITLE
ABIEncoderV2 Bug Exposure

### ISSUE THREAD

**Issue by aakilfernandes** [0xProject/0x-monorepo#1746]
https://blog.ethereum.org/2019/03/26/solidity-optimizer-and-abiencoderv2-bug/

Looks like the Exchange uses abiEncoderV2. 

https://github.com/0xProject/0x-monorepo/blob/master/packages/contracts/contracts/protocol/Exchange/Exchange.sol#L20

Has the dev team done an audit to make sure existing contracts are still secure?

**Comment by abandeali1** [comment]
Yep, the Exchange contract is unaffected by this bug.

**Comment by aakilfernandes** [comment]
Great!
