### ISSUE TITLE
Error: EXPIRED

### ISSUE THREAD

**Issue by aakilfernandes** [0xProject/0x-monorepo#1756]
## Expected Behavior

Should validate order as fillable

## Current Behavior
Error: EXPIRED

## Possible Solution
¯\_(ツ)_/¯

## Steps to Reproduce (for bugs)

```
// used JSON instead of actual object for readability
const zeroExOrder = {
  "exchangeAddress": "0x4f833a24e1f95d70f028921e27040ca56e09ab0b",
  "expirationTimeSeconds": "4294967295",
  "feeRecipientAddress": "0x0000000000000000000000000000000000000000",
  "makerAddress": "0xd5e60fdeec9b7d5043ca6aefa430b749e6ca5222",
  "makerAssetAmount": "10000000000000000000",
  "makerFee": "0",
  "makerAssetData": "0xf47261b00000000000000000000000006e87624b3bc434cd708c2ca517541ddc89c7d5b3",
  "takerAddress": "0x0000000000000000000000000000000000000000",
  "takerAssetAmount": "500",
  "takerAssetData": "0xf47261b000000000000000000000000083ebd2b0e093920242cd452d5f781a86ffc8b5a8",
  "takerFee": "0",
  "salt": "535399161",
  "senderAddress": "0x0000000000000000000000000000000000000000",
  "signature": "0x1ca994aa2ee991330707dceb7cc1a5ad437eeee17459103ac6dd4e5fe3c3e70d4b21d0b4a821741f14b45cefe67f6ab7dab1633d970830d7751c372b40cd97e44502"
}
await zeroExContractWrappers.exchange.validateOrderFillableOrThrowAsync(zeroExOrder)

```
## Your Environment

| Package | Version |
| ------: | :------ |
|0x.js      |6.0.5   |

| Network |
| ------- |
| Rinkeby    |

**Comment by aakilfernandes** [comment]
The source of the error is here:
https://github.com/0xProject/0x-monorepo/blob/78da0334411d601d2d1bb92c9c34983343f58b78/packages/order-utils/src/order_validation_utils.ts#L109-L113

I'm able to see the inputs are correct, but for some reason the `isLessThan` returns true when it should be false. Where is `isLessThan` defined? The objects are Bignumbers but `isLessThan` is not on the Bignumber api

**Comment by aakilfernandes** [comment]
Ah, I'm using an older version of BigNumber

**Comment by fabioberger** [comment]
@aakilfernandes to avoid these types of issues in the future, you can use `import { Bignumber } from "@0x/utils";`.
