### ISSUE TITLE
Guide for deploying on a local chain for testing

### ISSUE THREAD

**Issue by aakilfernandes** [0xProject/0x-monorepo#1764]
Is there a guide for deploying zero ex contracts on a local chain?

**Comment by feuGeneA** [comment]
Have you seen the README at https://github.com/0xProject/0x-monorepo/tree/development/packages/migrations ?

**Comment by aakilfernandes** [comment]
Haven't seen that before, I'll check it out. Thanks!

**Comment by aakilfernandes** [comment]
Hey @feuGeneA was able to get the snapshot, however how do I actually "load" the snapshot?

**Comment by feuGeneA** [comment]
Give the `--db $SNAPSHOT_NAME` argument to ganache-cli.  See example [here](https://github.com/0xProject/0x-monorepo/blob/02f7064953b7ff2c82a972bb84901c8cc368bb90/packages/migrations/Dockerfile#L14).

**Comment by aakilfernandes** [comment]
Ah it has to be passed in while zipped. I had unzipped it. Thanks!
