### ISSUE TITLE
Approval question

### ISSUE THREAD

**Issue by aakilfernandes** [0xProject/0x-monorepo#1765]
Hey, I have a generic question.

In an ERC20 <-> ERC20 exchange, which contracts need to be approved?
1. Exchange?
2. ERC20 Proxy?
3. Both?
4. More?

**Comment by LogvinovLeon** [comment]
Just the asset proxy you use. In that case `ERC20Proxy`.

**Comment by aakilfernandes** [comment]
Great, thanks
