### ISSUE TITLE
Does fillOrKill throw when the transaction fails?

### ISSUE THREAD

**Issue by aakilfernandes** [0xProject/0x-monorepo#1769]
I'm submitting an order and based on the `filled` result, it doesn't look like the order was filled (its still 0). However the transaction was mined succesfully with a status of 1. Is this expected behavior?

**Comment by dekz** [comment]
@aakilfernandes have you got more info on this transaction so we can debug further?

**Comment by dekz** [comment]
Closing this issue, if you have more information to help debug feel free to open a new one.
