### ISSUE TITLE
Building contracts requires Docker and to be ran as root (or as user with effectively root level access)

### ISSUE THREAD

**Issue by c2h5oh** [0xProject/0x-monorepo#1776]
## Expected Behavior

It's possible to install dependencies and build contracts without Docker or being privileged user

## Current Behavior

`PKG=@0x/contracts-exchange yarn build` fails on `@0x/contracts-utils` step with log messages indicating that you need docker running and your current user can access docker without sudo (which is a VERY BAD idea - see https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface )

```
$ sol-compiler
 | (node:26076) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
 | Compiling 9 contracts contracts/utils/(src/Address.sol,src/LibBytes.sol,src/Ownable.sol,src/ReentrancyGuard.sol,src/SafeMath.sol,src/interfaces/IOwnable.sol,test/TestConstants.sol,test/TestLibAddressArray.sol,test/TestLibBytes.sol) with Solidity v0.5.7...
 | docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///contracts/utils/var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
 | See 'docker run --help'.
 | { Error: Command failed: docker run contracts/utils/ethereum/solc:0.5.7 --version
 | docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///contracts/utils/var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
 | See 'docker run --help'.
```

## Possible Solution

Use solcjs as default, make dockerized solc an option behind a flag

## Steps to Reproduce (for bugs)

run `PKG=@0x/contracts-exchange yarn build` without docker installed or with default docker setup (requiring sudo to access docker daemon) on vast majority of Linux distros

## Context

1. Current build process has a dependency that isn't mentioned in the docs.
2. It requires insecure and actively discouraged config of that dependency as per Docker docs

Given that npm still has no support for signed releases, package security model being weak in general with malicious releases making it to npm every now and then a requirement to give `yarn build` effectively root access to developer system is at best reckless. 

## Your Environment

Arch Linux
head of development branch of monorepo at the time of testing: c78a60299053f0ec825bf34dd3ea0cea7bb9365b

**Comment by dekz** [comment]
@c2h5oh Thanks for the github issue.

As you might be aware the `compiler.json` file contains an option for changing the behaviour `"useDockerisedSolc": false,`. We would be happy to accept a pull request that can override this behaviour with an environment variable.

**Comment by albrow** [comment]
@c2h5oh I also wanted to point out that modern docker installations do not require `sudo` to use. Depending on your operating system, you might need to [take some additional steps to enable non-root access](https://docs.docker.com/install/linux/linux-postinstall/). (Personally, I used to be on an older version of Docker on MacOS and upgrading resolved the issue).

**Comment by c2h5oh** [comment]
> I also wanted to point out that modern docker installations do not require sudo to use

Docker daemon ALWAYS runs as root. This is literally the first line at the link I've provided in the issue description: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface

`docker` is just a cli to control that daemon - if you can run docker commands without sudo, that means you can effectively run commands as root without sudo - again see the article above.


> I also wanted to point out that modern docker installations do not require sudo to use. 

No, they don't. Literally never if Docker is running natively, because of security implications.

Sudo is only not required when running Docker on OSX or on Windows, because Docker runs in VM on those systems and has no root equivalent access to entire system, just the VM.


> As you might be aware the compiler.json file contains an option for changing the behaviour "useDockerisedSolc": false,. We would be happy to accept a pull request that can override this behaviour with an environment variable.

More secure setting should be the default, not an option.
