### ISSUE TITLE
@0x/subproviders doesn't work with web3@beta (on sendTransaction)

### ISSUE THREAD

**Issue by mqklin** [0xProject/0x-monorepo#1791]
Error: `TypeError: web3CoreSubscriptions.NewHeadsSubscription is not a constructor`

Related web3 issue: https://github.com/ethereum/web3.js/issues/2722

Here is a repro: https://github.com/mqklin/web3-test

If I just remove `@0x/subproviders` from `package.json`, it works as expected.

Do you support web3@beta? 

Thanks

**Comment by dekz** [comment]
Web3@beta is unstable. Whilst we have added support for beta <= 39 we do not keep up to date with every breaking change. Once Web3 becomes stable we will ensure it is supported. Internally we still recommend the 0.20.x releases.

**Comment by fabioberger** [comment]
Another option is to use https://github.com/ethers-io/ethers.js/
