### ISSUE TITLE
connect: OrdersChannelSubscriptionOpts do not conform to SRA V2 spec 

### ISSUE THREAD

**Issue by PirosB3** [0xProject/0x-monorepo#1794]
## Expected Behavior

Based on the 0x SRA V2 spec, [subscribing to a category](https://github.com/0xProject/standard-relayer-api/blob/master/ws/v2.md#subscribe) of orders contains the following payload in data:
```
    "payload": {
        "makerAssetData": "0xf47261...",
        "takerAssetData": "0x0257179...",
        "networkId": 42,
    }
```
Using 0x connect, I am able to [subscribe](https://github.com/0xProject/0x-monorepo/blob/development/packages/connect/src/types.ts#L29) to SRA V2 events using a `OrdersChannelSubscriptionOpts`. As of today, [this struct](https://github.com/0xProject/0x-monorepo/blob/d0e43ebaf1f8749126d525d40a125b93db3cdcce/packages/types/src/index.ts#L334) contains parameters that are not part of the SRA V2 spec.

Implementation of `subscribe` can be found [here](https://github.com/0xProject/0x-monorepo/blob/development/packages/connect/src/ws_orders_channel.ts#L55)

## Current Behavior

Even if we subscribe to a particular market using `0x/connect`, we actually receive events from all markets, instead of a subset.

## Possible Solution

Change `OrdersChannelSubscriptionOpts` to conform to the SRA V2 spec.

## Steps to Reproduce (for bugs)

1. Follow the 0x connect tutorial and subscribe to the ETH/DAI market
2. Log all `makerAssetData` and `takerAssetData` that are outputted as events
3. Notice how not all orders are part of the ETH/DAI market.

**Comment by fabioberger** [comment]
@PirosB3 would appreciate a PR to fix this!

**Comment by amaurer** [comment]
Working on a PR now..

**Comment by dchambers** [comment]
️️️Hi, I've pushed a fix for this if somebody can take a look please?
