### ISSUE TITLE
order-watcher: callbacks taking 4 to 10 seconds between them.

### ISSUE THREAD

**Issue by valkyriaivan** [0xProject/0x-monorepo#1836]
## Expected Behavior

When the state of an order in the OrderWatcher changes, the callback is called. Supposedly, the time between callbacks should be quick. 

## Current Behavior

Instead, the callbacks are called with 4 to 10 seconds between them. I tried filling one order at a time: The first callback is done quick, but if I have more orders from the same maker, the callbacks called because the maker balance changed are spaced between them those 4 to 10 seconds.
I tried batch filling 5 orders:The result is the same, the first is called fast and the rest are spaced in time. 

## Steps to Reproduce (for bugs)

At first I thought maybe the whole backend was lagging the watcher, but later I created a simple Nodejs script to automate a test. The test consist of an interval which creates and signs 5 orders and immediately batch fills those. Then waits for the 5 callbacks to be done, record the unix time in ms and current block and save it. Then starts again, for 30 minutes.
The results can be found [here](https://pastebin.com/SzEkL6Fw).
The code for the script can be found [here](https://github.com/valkyriaivan/OrderWatcherTest/blob/master/index.js). _Don't mind the mess, it was coded in a rush._

I don't really know how to reproduce this problem since I don't really know what is causing it in the first place. There is no error logged in the console and I tried using Infura and Alchemy, both with the same results. I tried using 3 enviroment: local, remote host and google cloud. All three had the same results. Here you have screenshots of the logs for the rancher in a host and the google cloud. When an order calls the callback a dot is logged and then return if it is not a fill callback, so when the first order is filled, all the next dots are orders from the same maker calling the callback with the new maker balance. All having the same results as in local, 4 to 10 seconds between calls. [Rancher](https://gyazo.com/e67953a99f774a3efd8f85e1eef61e2b) - [Google cloud](https://gyazo.com/7c8bc50aec897b58a50d25d739b06357)

## Context

This is a big problem for me, since if an order is filled and the maker has more orders, it can take 2-3 minutes until other people orders reach the callback. So I'm trying to accomplish a faster orderWatcher since most of the functionality of the Relayer is based on a "fast" orderWatcher.

## Your Environment

| Package | Version |
| ------: | :------ |
|             `0x.js` | 6.0.9   |
| `@0x/order-watcher` | 4.0.11      |
| `@0x/subproviders` | 4.0.6      |
| `@0x/web3-wrapper` | 6.0.6      |

| Network |
| ------- |
| Ropsten    |
| Kovan |

**Comment by valkyriaivan** [comment]
After doing some tests I modified the script to just create and fill one order. Also I went into the code of the OrderWatcher to add some logs. After landing in the `OrderWatcher.prototype.removeOrder` I added a console log after the `this._orderByOrderHash[orderHash]`.
```
OrderWatcher.prototype.removeOrder = function (orderHash) {
        assert_1.assert.doesConformToSchema('orderHash', orderHash, json_schemas_1.schemas.orderHashSchema);
        var signedOrder = this._orderByOrderHash[orderHash];
        console.log("Signed order", signedOrder)
        if (signedOrder === undefined) {
            return; // noop
        }
        this._dependentOrderHashesTracker.removeFromDependentOrderHashes(signedOrder);
        delete this._orderByOrderHash[orderHash];
        this._expirationWatcher.removeOrder(orderHash);
        delete this._orderStateByOrderHashCache[orderHash];
    };
```
After running the script again I noticed that with only one order filled, the callback is called twice even after removing the order in the first callback.
![70ee83b26484ae6663739334a05f7963](https://user-images.githubusercontent.com/23335839/58471818-0fd73780-8145-11e9-9216-294a26b4c37f.png)

**Comment by fabioberger** [comment]
Spoke with @valkyriaivan on Discord about this issue. Currently not high-priority since we plan to deprecate OrderWatcher once [0x Mesh](https://github.com/0xProject/0x-mesh/) launches. Mesh ships with a more robust and performant OrderWatcher service. Benefits to the Mesh implementation:

- Highly optimized number of `eth_call` requests during validation (500 order validations per `eth_call`)
- Persisted to disk (rather then memory), starts back up where it left off after a crash
- Can start watcher at arbitrary block height
- Will be heavily battle-tested once Mesh network launches.

**Comment by fabioberger** [comment]
`@0x/order-watcher` is officially deprecated. Please use [0x Mesh](https://github.com/0xProject/0x-mesh) for all your order watching needs.
