### ISSUE TITLE
subproviders: Orders Signed By Trezor Returns INVALID_SIGNATURE

### ISSUE THREAD

**Issue by ravi2689** [0xProject/0x-monorepo#1838]
## Problem Description
I was signing the order.
Order
```
{
exchangeAddress: "0xbce0b5f6eb618c565c3e5f5cd69652bbc279f44e",
expirationTimeSeconds: BigNumber {s: 1, e: 12, c: Array(1)},
feeRecipientAddress: "0x0000000000000000000000000000000000000000",
makerAddress: "0x0d6841816bc98f892d3e10562149506a9f3234b3",
makerAssetAmount: BigNumber {s: 1, e: 18, c: Array(1)},
makerAssetData: "0xf47261b0000000000000000000000000175ac784563de645647c6350f0cfc577dcc7ee5b",
makerFee: BigNumber {s: 1, e: 0, c: Array(1)},
salt: BigNumber {s: 1, e: 76, c: Array(6)},
senderAddress: "0x0000000000000000000000000000000000000000",
takerAddress: "0x0000000000000000000000000000000000000000",
takerAssetAmount: BigNumber {s: 1, e: 19, c: Array(2)},
takerAssetData: "0xf47261b00000000000000000000000002d1420f4cee004c348d58e7b28869af8c5372323",
takerFee: BigNumber {s: 1, e: 0, c: Array(1)
}
```

using

`signedOrder = await signatureUtils.ecSignOrderAsync(provider, order, makerAddress);`

and I am keep getting this Error,
INVALID_SIGNATURE

and it is not returning proper Signed order.

I console it in node_modules ... the signature it was validating was

```
0xe19ebd5e9549f7d3f1e504427caa11f4aa0b811f4b56466117f69bf996d20507436bfd4ae5dfcedabe79b65284321a5cc0613225038e74220a036155106afd8d1c
```

So, 
```
assert_1.assert.doesConformToSchema('signature', signature, json_schemas_1.schemas.ecSignatureSchema);
```

this line is throwing the error
@0x/order-utils/ signature_utils.js

## Expected Behavior

I should return Signed order, with proper signature.

## Your Environment

| Package | Version |
--- | ---
| 0x.js | 6.0.8 |
| @0x/subproviders | ^4.1.0 |

Device: Trezor One, Firmware: 1.8.0

**Comment by fabioberger** [comment]
@ravi2689 thanks for opening this issue. I do not have a Trezor myself and so cannot repro this. Can you please print out the value of `signature` on line 402 in `signature_utils.ts`?

That might let me help you debug what is going on. @MarcZenn @NoahZinsmeister Have you guys run into this issue before? Are you also using firmware version 1.8.0?

**Comment by ravi2689** [comment]
File: signature_utils.js
function: ecSignHashAsync
case 2:
signature = _a.sent();  // line 468
console.log(signature);

```
0xe19ebd5e9549f7d3f1e504427caa11f4aa0b811f4b56466117f69bf996d20507436bfd4ae5dfcedabe79b65284321a5cc0613225038e74220a036155106afd8d1c
```

**Comment by ravi2689** [comment]
@fabioberger @MarcZenn  Is there any update regarding this issue. If not please let me know if there is another way to integrate trezor in 0x.

**Comment by rahul70392** [comment]
@MarcZenn @fabioberger guys any updates? We are kind of stuck in our implementation. Please find time to have a look.

**Comment by ravi2689** [comment]
I have solved the issue.
File: \node_modules\@0x\subproviders\lib\src\subproviders\trezor.js
Line 197:  `hex: false,`
hex must be true, because the data coming is in hex
Line 187: `assert_1.assert.isHexString('data', data);`

Please update the npm module by incorporating changes. Thanks guys

**Comment by fabioberger** [comment]
@ravi2689 can you please look at https://github.com/0xProject/0x-monorepo/pull/1867 and make sure it solves the issue? Thanks.
