### ISSUE TITLE
general: Supporting Goerli testnet?

### ISSUE THREAD

**Issue by icinsight** [0xProject/0x-monorepo#1849]
I wonder what is a good timing to have a  Goerli ("Görli") testnet implementation? No rush.

**Comment by fabioberger** [comment]
I like the idea. We should do it.

**Comment by mat7ias** [comment]
This issue is still relevant, possible to get it reopened? :heart:

**Comment by icinsight** [comment]
@mat7ias Feel free to post a new issue with the same title. It looks like I can't reopen it myself (I'm just a guest here).
