### ISSUE TITLE
instant: Forbidden

### ISSUE THREAD

**Issue by alessiofx** [0xProject/0x-monorepo#1866]
I have a problem with instant and safari (ios and macos),

if I browse on this site https://cas.casino/ everything works normally.
If I load this page https://cas.casino/buy  where there is instant,
when I return to the home page and browse the site it gives me error:
Forbidden
You don't have permission to access / on this server.
Additionally, a 403 error was encountered while trying to use an error document to handle the request.

why ?

I think there are problem with cookie.

The video of bug:
https://www.dropbox.com/s/9w0jg4o26bls22x/bug_istant_original.mp4?dl=0

**Comment by fragosti** [comment]
If it is the cookie causing the problem, I think the cookie is added by one of our third party analytics packages. I am not sure why your server does not like the cookies, but you can disable analytics in Instant with the `shouldDisableAnalyticsTracking` prop https://0x.org/wiki#Get-Started-With-Instant
