### ISSUE TITLE
sol-profiler: Unable to find the cause for -15000 gas.

### ISSUE THREAD

**Issue by hoytech** [0xProject/0x-monorepo#1884]
Just ran the profiler and it seems to work (generates valid-looking output which I can render with istanbul), but it prints the following:

    Unable to find the cause for -15000 gas. It's most probably an issue in sol-profiler. Please report on Github.
    ...
    Unable to find the cause for -60000 gas. It's most probably an issue in sol-profiler. Please report on Github.

So, I'm reporting on github, as requested. Let me know if you need any further info to debug. Thanks!

**Comment by fabioberger** [comment]
Thanks for submitting @hoytech. This is probably related to a miscalculation around gas refunds.
