### ISSUE TITLE
ethereum-types:  The Devdoc output doesn't cover possible valid output.

### ISSUE THREAD

**Issue by Freydal** [0xProject/0x-monorepo#1899]
## Expected Behavior

https://github.com/0xProject/0x-monorepo/blob/e20fa3a1bf3b801ef1748792d983fb79fccb1265/packages/ethereum-types/src/index.ts#L614-L626

Should cover all possible valid compiled output.

## Current Behavior
Typings cause issues when sol-compiler includes devdoc output.

## Possible Solution

The custom types we used to override
```
interface KosuDevDocOutput {
    title?: string;
    author?: string;
    methods?: {
        [signature: string]: {
            details?: string;
            params?: {
                [name: string]: string;
            };
            return?: string;
        };
    };
}
```

## Steps to Reproduce (for bugs)

```
1. Add devdocs to compiler.json outputSelection
1. Compile a contract missing some part of the devdocs required by the typing. 
1. Attempt to compile the typescript.
```

## Context
We are attempting to use Solidity devdocs to generate some documentation.  The types are requiring us to override artifacts.ts generated with contracts-gen

## Your Environment

| Package | Version |
| ------: | :------ |

| Network |
| ------- |
| NAME    |

**Comment by feuGeneA** [comment]
Thanks for reporting this.  I too hit this issue recently, and have fixed it in my #1878 , and it's also included in #1907 .  Whenever either of those merges, this will be fixed.
