### ISSUE TITLE
OrderValidator -> DevUtils

### ISSUE THREAD

**Issue by xianny** [0xProject/0x-monorepo#1909]
OrderValidator is now OrderValidationUtils, which is inherited by DevUtils (among many other useful functions). We should replace OrderValidator with DevUtils in `abi-gen-wrappers`, `contract-artifacts`, and anywhere else it might be lingering. 

Motivation: Solidity source code for OrderValidator has already been deleted and it won't be redeployed for V3. It currently exists only on the chain and as compiler output in `contract-artifacts`, which makes it hard to debug or develop on.

- [x] Compile DevUtils and add the artifact to `contract-artifacts`
- [x] Run migration script to deploy **only** DevUtils
- [x] Add deployed address to `contract-addresses`
- [x] Generate `DevUtils` wrapper in `abi-gen-wrappers`
- [ ] replace uses of `OrderValidator` throughout monorepo with `DevUtils`
- [ ] Remove `OrderValidator from `contract-addresses`, `contract-artifacts`, and `abi-gen-wrappers`

**Comment by xianny** [comment]
@abandeali1 is `OrderValidationUtils` or `DevUtils` deployed, and if so what is its address? I still see `OrderValidator` in `@0x/contract-addresses` : https://github.com/0xProject/0x-monorepo/blob/development/packages/contract-addresses/src/index.ts

**Comment by xianny** [comment]
@dekz @feuGeneA can I close this? Looks like you took care of it :)

**Comment by feuGeneA** [comment]
I'll let @dekz provide the authoritative answer, but it looks to me like we did everything except replacing uses of `OrderValidator`.
