### ISSUE TITLE
Prettify abi-gen

### ISSUE THREAD

**Issue by xianny** [0xProject/0x-monorepo#1917]
## Expected Behavior

`prettier` should be run as part of abi-gen. We are currently checking in `generated-wrappers` so that we can compare diffs when reviewing. Prettifying will minimise the amount of whitespace/formatting diffs and make reviews easier, and should be enforced immediately after generating wrappers. 

## Current Behavior

`prettier` must be run when building/as part of build scripts. We're doing extensive work on `abi-gen` right now and run into whitespace conflicts, huge unnecessary diffs, etc. 

## Possible Solution

Implement `prettier` within the `abi-gen` code generation script.

**Comment by feuGeneA** [comment]
Just one more quick note on motivation.  As much as possible, we should be generating not just _working_ code, but _good_ code.  It's not hard to use `prettier` within a run of `abi-gen`, so we should!
