### ISSUE TITLE
sol-cov: Line coverage missing with multiple modifiers

### ISSUE THREAD

**Issue by angus-hamill** [0xProject/0x-monorepo#1918]
## Expected Behavior
All lines that are covered show as covered within the report.

## Current Behavior
For a function with two or more modifiers, the `_;` line of the first modifier displays as uncovered.

## Steps to Reproduce (for bugs)

```
1. git checkout https://github.com/angus-hamill/solcov-exp.git
2. cd solcov-exp
3. truffle compile
4. truffle test --network coverage
5. istanbul report --include coverage/coverage.json --dir coverage html
```

**Comment by angus-hamill** [comment]
Is anyone looking at this?
It's a pretty annoying issue that's stopping me using sol-cover

**Comment by jalextowle** [comment]
I am currently working on updating `sol-coverage` for a few reasons. I'll keep this issue in mind as I work on it and work on fixing it. We've also run into this issue ourselves.

**Comment by ochikov** [comment]
I have the same problem, but on first modifier. Is anybody working on that?
