### ISSUE TITLE
Add `callAsync` to generated wrappers for stateful functions

### ISSUE THREAD

**Issue by xianny** [0xProject/0x-monorepo#1929]
Depending on the state mutability of a given Solidity function, `abi-gen` generates different methods for calling the function. If the function is `pure` or `view`, we generate a `callAsync` method. For other types of functions (where `constant = false`), we generate `sendTransactionAsync`. 

@jalextowle suggested that we include `callAsync` AND `sendTransactionAsync` for these non-constant functions. 

@jalextowle :
> The difference between the two is that `callAsync` will just simulate the tx locally, whereas `sendTransactionAsync` (if our libraries follow infura API endpoint conventions — I’m somewhat new to our libraries) will actually submit the tx to the blockchain to be executed. Furthermore, call will return the `returndata` of the call, whereas `sendTransactionAsync` will return the entire tx.logs (edited) 

===============

> it is often useful to see what the returndata of a stateful call would be, even if you do not change the associated state. One way in which it could be useful is to perform the calculation that a stateful function performs with *less* calls to infura. Consider the following:
>
> I want to know the matchedFillResults of matching two orders to verify that the match will be successful. If I have a very out of date notion of the orders that are current on the exchange, this could actually save some ETH in gas costs because you will avoid sending a tx that will just revert
>
> That may not be a good enough reason though, so I’ll keep thinking about it
>
> For me, it would be useful so that we can assert results in our simulations in tests. It is a test convenience, but I would say that it actually does significantly improve the quality of our tests.

EDIT: yes, let's do it.

**Comment by feuGeneA** [comment]
For what it's worth, @fabioberger and I decided that, for Python, we _should_ generate a `call` method (in addition to `sendTransaction`) even for stateful functions, and that's the way the Python wrapper generation is currently implemented.

**Comment by fabioberger** [comment]
Yes, we should always allow devs to execute a `call` instead of a `transaction` for stateful functions.
