### ISSUE TITLE
Expose forwarder order optimizations in `asset-buyer` 

### ISSUE THREAD

**Issue by xianny** [0xProject/0x-monorepo#1934]
Currently, `@0x/contract-wrappers` ForwarderWrapper optimizes orders before executing transactions by removing repetitive data. We should expose optimizer methods in `asset-buyer` and call them before executing transactions in the `abi-gen` wrapper

Part of #1911

**Comment by abandeali1** [comment]
FYI, we can actually remove these optimization completely (there is now a more efficient way to do this that is automatically handled by our abi-encoder implementation).
