### ISSUE TITLE
@0x/subproviders. Metamask provider rejecting non hex encoded data

### ISSUE THREAD

**Issue by marwan38** [0xProject/0x-monorepo#1936]
## Expected Behavior

~Calling `web3Wrapper.signMessage(address, 12345)` with `PrivateKeyWalletSubprovider` to work without throwing an error `Expected data to be of type HexString`.~ 

Calling `web3Wrapper.signMessage(address, 12345)` with `MetamaskSubprovider` should throw an error `Expected data to be of type HexString` to make it constant with all other providers.

## Current Behavior

~Calling `web3Wrapper.signMessage(address, 12345)` with `MetamaskSubprovider` works just as expected, no problems. On the other hand, calling `web3Wrapper.signMessage(address, 12345)` using `PrivatekeySubprovider` throws error `Expected data to be of type HexString`~

Calling `web3Wrapper.signMessage(address, 12345)` with `MetamaskSubprovider` without hashing the data works with no problems. On the other hand, calling `web3Wrapper.signMessage(address, 12345)` using `PrivatekeySubprovider` throws error `Expected data to be of type HexString`

## Context

I prompt users to sign the message with a generated nonce for backend authorization by simply calling `web3Wrapper.signMessage(address, <number|string>nonce)`.

## Your Environment
| `@0x/subproviders` | 4.1.0 |

**Comment by dekz** [comment]
Thanks @marwan38. As discussed in discord we should remove the ability for MM to accept anything other than hex encoded values. This makes it consistent with all other providers with no surprises.

**Comment by marwan38** [comment]
> 
> 
> Thanks @marwan38. As discussed in discord we should remove the ability for MM to accept anything other than hex encoded values. This makes it consistent with all other providers with no surprises.

Right, my mistake. I've updated the issue to reflect on this. Thanks @dekz.
