### ISSUE TITLE
Corner case when marketSellOrders/marketBuyOrders not works

### ISSUE THREAD

**Issue by k06a** [0xProject/0x-monorepo#1956]
##  Description

Since orders array is executed sequentially, not parallel (as discussed here https://github.com/0xProject/0x-monorepo/issues/851), there is some possible affecting of orders related to the same makers. I met this 2 orders in WETH-KNC orderbook on RadarRelay:
```
0:
exchangeAddress: "0x4f833a24e1f95d70f028921e27040ca56e09ab0b"
expirationTimeSeconds: t {_hex: "0x5d2269e1", _ethersType: "BigNumber"}
feeRecipientAddress: "0xa258b39954cef5cb142fd567a46cddb31a670124"
makerAddress: "0xd72fbae4b64079edd64969f760cdf240ec7533eb"
makerAssetAmount: t {_hex: "0xfa8a1b3f39df593c80", _ethersType: "BigNumber"}
makerAssetData: "0xf47261b0000000000000000000000000dd974d5c2e2928dea5f71b9825b8b646686bd200"
makerFee: t {_hex: "0x00", _ethersType: "BigNumber"}
orderTakerAssetFilledAmount: t {_hex: "0x00", _ethersType: "BigNumber"}
salt: t {_hex: "0x016bce6989b8", _ethersType: "BigNumber"}
senderAddress: "0x0000000000000000000000000000000000000000"
signature: "0x1b561c79992a8573dd4c3c54a513477b5f7271fad2bb3940a636af12c56afd79617afff2b4ab1de49734519311fb7bc915a98f4cdd45a8984caa0d462d1d8c9ee603"
takerAddress: "0x0000000000000000000000000000000000000000"
takerAssetAmount: t {_hex: "0x36a3cdf340c0d917", _ethersType: "BigNumber"}
takerAssetData: "0xf47261b0000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
takerFee: t {_hex: "0x00", _ethersType: "BigNumber"}
__proto__: Object

1:
exchangeAddress: "0x4f833a24e1f95d70f028921e27040ca56e09ab0b"
expirationTimeSeconds: t {_hex: "0x5d22692f", _ethersType: "BigNumber"}
feeRecipientAddress: "0xa258b39954cef5cb142fd567a46cddb31a670124"
makerAddress: "0xd72fbae4b64079edd64969f760cdf240ec7533eb"
makerAssetAmount: t {_hex: "0xf985a5a987164f4900", _ethersType: "BigNumber"}
makerAssetData: "0xf47261b0000000000000000000000000dd974d5c2e2928dea5f71b9825b8b646686bd200"
makerFee: t {_hex: "0x00", _ethersType: "BigNumber"}
orderTakerAssetFilledAmount: t {_hex: "0x3506706c3dacfff6", _ethersType: "BigNumber"}
salt: t {_hex: "0x016bce66d3da", _ethersType: "BigNumber"}
senderAddress: "0x0000000000000000000000000000000000000000"
signature: "0x1cd2f168a3f56de6ce9bedda925a1cdc15f9558c7d69c01d5f325db3dd3ea3903d1140cc8e12d46a49a69f3be0c970bade83326b14ca10b32b1c6082ebb299c3bd03"
takerAddress: "0x0000000000000000000000000000000000000000"
takerAssetAmount: t {_hex: "0x366e9dafbb17fb41", _ethersType: "BigNumber"}
takerAssetData: "0xf47261b0000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
takerFee: t {_hex: "0x00", _ethersType: "BigNumber"}
__proto__: Object
```

Each of them is valid and present volumes `4621 KNC` and `4602 KNC`, everything is fine except maker balance is `4738 KNC`. So sequential execution of this orders in `marketBuyOrders` or `marketSellOrders` leads to error.

##  Expected Behavior

I believe these two functions should respect makers `balance` and `allowance` before each order processing. Or at least check if maker of each order was presented in previous orders.

## Current Behavior

It reverts or throws, depending on token implementation.

## Possible Solution

Example of working `marketSellOrders`:

```Solidity
function marketSellOrders(
    address makerAsset,
    address zrxExchange,
    address zrxTokenProxy,
    uint256 takerAssetFillAmount,
    IZrxExchange.Order[] calldata orders,
    bytes[] calldata signatures
)
    external
    returns (IZrxExchange.FillResults memory totalFillResults)
{
    for (uint i = 0; i < orders.length; i++) {

        // Stop execution if the entire amount of takerAsset has been sold
        if (totalFillResults.takerAssetFilledAmount >= takerAssetFillAmount) {
            break;
        }

        // Calculate the remaining amount of takerAsset to sell
        uint256 remainingTakerAmount = takerAssetFillAmount.sub(totalFillResults.takerAssetFilledAmount);

        IZrxExchange.OrderInfo memory orderInfo = IZrxExchange(zrxExchange).getOrderInfo(orders[i]);
        uint256 orderRemainingTakerAmount = orders[i].takerAssetAmount.sub(orderInfo.orderTakerAssetFilledAmount);

        // Check available balance and allowance and update orderRemainingTakerAmount
        {
            uint256 balance = IERC20NonView(makerAsset).balanceOf(orders[i].makerAddress);
            uint256 allowance = IERC20NonView(makerAsset).allowance(orders[i].makerAddress, zrxTokenProxy);
            uint256 availableMakerAmount = (allowance < balance) ? allowance : balance;
            uint256 availableTakerAmount = availableMakerAmount.mul(orders[i].takerAssetAmount).div(orders[i].makerAssetAmount);

            if (availableTakerAmount < orderRemainingTakerAmount) {
                orderRemainingTakerAmount = availableTakerAmount;
            }
        }

        uint256 takerAmount = (orderRemainingTakerAmount < remainingTakerAmount) ? orderRemainingTakerAmount : remainingTakerAmount;

        IZrxExchange.FillResults memory fillResults = IZrxExchange(zrxExchange).fillOrder(
            orders[i],
            takerAmount,
            signatures[i]
        );

        addFillResults(totalFillResults, fillResults);
    }

    return totalFillResults;
}
```

## Context

We are building [1inch.exchange](https://1inch.exchange) which allows to aggregate liquidity among DEXes to achieve the best possible price inside single transaction.

**Comment by dekz** [comment]
Hey @k06a thanks for taking the time to dig in and open this issue.

As you determined, in isolation the orders are completely valid, the maker has sufficient balance/allowance to fill one of orders. It is only when the state of one of the orders changes, the other becomes unfillable.

It is also possible the user has a WETH/KNC order and a batch fill over the 3 orders can result in them all being valid and successfully filling.

There is a `marketSellOrdersNoThrow` variant that will handle the revert and continue on to the next order, this prevents a full revert unless `takerAssetFillAmount` is not satisfied.

Our libraries also perform an `eth_call` before a on-chain transaction to ensure the transaction at the time of sending was valid and would not revert, this is performed in our exchange wrapper contracts with the option (default) `shouldValidate: true`.

**Comment by k06a** [comment]
@dekz I suspect a few issues with `marketSellOrdersNoThrow` implementation:
1. It forwards all `gas` to `fillOrder()`, but some tokens can `throw` instead of `revert` and this will eat all tx gas.
2. Since orders are ordered by the price it will skip partially-possible orders and potentially will provide a worse rate than my implementation.

**Comment by dekz** [comment]
It can definitely be beneficial to reduce the takers spread over the orders. But it can also introduce dust orders which aren't worth the value to even fill. Imagine where the maker has `0.1 KNC` or even `0.0001 KNC` remaining after detecting their balance and allowance. It's hard to justify filling that order. Though a `0.0001 WBTC` would be worth it. 

In the case where the order provided have sufficient balance to not require the check, there's the added gas costs of making the balance+allowance check. I.e If a single market maker has more than sufficient balance+allowance for the provided orders the checks are redundant and add gas overhead. 

There is also the `batchFillOrders` function on 0x which allows the caller to specify the exact amounts they wish to fill per order. This also allows a sufficiently smart client to minimise their spread by being able to calculate the side effects of the previous fill.

**Comment by k06a** [comment]
@dekz, I mostly agree about gas consumption. What do you think of adding argument `orderMinMakerAmount` to skip filling small orders to at least avoid `fillOrder` call?

**Comment by k06a** [comment]
`batchFillOrdes` do not works for us, because any of orders could be changed before our tx also.

**Comment by dekz** [comment]
@k06a We're going to discuss this internally. We want a user friendly and simple market buy/sell option even if the gas cost is high from that inefficiencies.
