### ISSUE TITLE
fs.utimesSync doesn't work on Mac

### ISSUE THREAD

**Issue by xianny** [0xProject/0x-monorepo#2000]
There is a unit test in `abi-gen` that fails because `fs.utimesSync` doesn't work as expected:

```
should return false when output file exists but is older than abi file
```

It passes on CI, but not locally. 

To reproduce:
cd into `packages/abi-gen` and run `yarn build && yarn test`

**Comment by feuGeneA** [comment]
To clarify, it passes on Linux, not just CI.  I'm running Linux and it passes locally for me.
