### ISSUE TITLE
instant: modal page doesn't close

### ISSUE THREAD

**Issue by benjyz** [0xProject/0x-monorepo#2099]
## Expected Behavior

pressing the X button should close the modal 

## Current Behavior

nothing happens

## Possible Solution

implement close on the modal in overlay?

https://github.com/0xProject/0x-monorepo/blob/development/packages/instant/src/components/ui/overlay.tsx

## Context

0x instant javascript

## Your Environment

mainnet

**Comment by benjyz** [comment]
@fragosti  "you're going to have to be more specific with the repro steps as it seems to be working for me". 

I created a snippet from our react app. the UI is rendered to body. will try to debug more 

https://gist.github.com/benjyz/915c93618521c3e7dd3058e66d18804f

**Comment by benjyz** [comment]
surprisingly: closing the modal works by clicking beneath the area of "X", i.e. clicking on the area below it closes. so looks like some css issue

**Comment by pointtoken** [comment]
we've noticed that on mobile, the only way to get out of the experience is to navigate backward, which is suboptimal.

**Comment by asghaier76** [comment]
I have the same issue on mobile since the x button is not in display at all
