### ISSUE TITLE
Add deployedBytecode to contract-artifacts

### ISSUE THREAD

**Issue by xianny** [0xProject/0x-monorepo#2173]
In #2108 we added the ability to use a local EVM to execute pure Solidity functions in `@0x/abi-gen-wrappers`, e.g. in `DevUtilsContract`, `ExchangeContract`, etc.

However, it's dependent on an eth call to `eth_getCode`. 

We would like to use pure methods in `DevUtilsContract` to replace `@0x/order-utils`. At the moment, using `DevUtilsContract` introduces a dependency on RPC calls, ganache tooling (in tests), whereas `@0x/order-utils` only uses local typescript code. 

Adding `deployedBytecode` to `@0x/contract-artifacts` will enable devs to execute the pure Solidity functions without any external calls.

**Comment by fabioberger** [comment]
@xianny isn't another part of this issue actually _using_ the `deployedBytecode` or do we have a separate issue for that?

**Comment by xianny** [comment]
Yup! There's a separate PR to *use* the deployed bytecode and it's merged here: https://github.com/0xProject/0x-monorepo/pull/2198
