### ISSUE TITLE
[sol-compiler] hangs when creating solc_bin on Windows 10

### ISSUE THREAD

**Issue by HenryNguyen5** [0xProject/0x-monorepo#2318]
## Expected Behavior
The compiler should successfully create directories and proceed to download the required solc version along with compiling the files.

## Current Behavior
Indefinite hang when creating `@0x\sol-compiler\lib\solc_bin...`. The directory is created, but no progress is made after that. Restarting the script results in a hang with no output as the directory has been created.

## Possible Solution
I think it might be related to https://github.com/substack/node-mkdirp/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+windows, not sure though

## Steps to Reproduce (for bugs)
https://github.com/smartcontractkit/sol-compiler-freeze-windows

**Comment by coventry** [comment]
bump.
