### ISSUE TITLE
0x-instant feature request

### ISSUE THREAD

**Issue by pointtoken** [0xProject/0x-monorepo#2351]
Are there any plans for 0x instant (and the forwarding contract) to support currencies/tokens other than ETH? This would be great to have the 0x instant UX but for orders denominated in other currencies...

**Comment by dekz** [comment]
It's currently not possible with ERC20 as it requires an allowance set to the Forwarder (to move your DAI). But sending ETH as part of the transaction is what enables the current Forwarder/Instant to buy tokens with ETH.

That being said, a simple Instant UI ontop of trading directly with the Exchange contract (and a UI to set the required allowance) would is a feature we've got on our backlog.
