### ISSUE TITLE
@0x/migrations@4.4.0-beta.3 breaks Coordinator client

### ISSUE THREAD

**Issue by xianny** [0xProject/0x-monorepo#2360]
## Context
Coordinator Client is a handwritten "wrapper" around the `abi-gen`erated wrapper for the Coordinator Contract. It reproduces the interface of the generated wrapper for the Exchange contract and effaces the process of looking up coordinator operator endpoints and obtaining approval signatures.

We deactivated it while refactoring for V3 and revived it near the end of the refactor. However, updating from `@0x/migrations@4.4.0-beta.2` -> `@0x/migrations@4.4.0-beta.3`, causes tests to fail. The same errors occurred when we bumped `0x/migrations` version in [0x-coordinator-server](https://github.com/0xProject/0x-coordinator-server).

## Current behaviour
With `@0x/migrations@4.4.0-beta.3`:
`fillOrder` fails with `InvalidApprovalSignatureError`

Coordinator Server is reverting on this call: https://github.com/0xProject/0x-coordinator-server/blob/master/ts/src/handlers.ts#L475-L477 

## Expected Behavior

Tests in `0x-monorepo/contracts/integrations/coordinator/.../client_test.ts` pass
Tests in `0x-coordinator-server` pass

## Possible Solution

Downgrading to @0x/migrations@4.4.0-beta.2 works.
Inferring that the breaking changes were introduced somewhere in one of these PRs:
![Screen Shot 2019-11-20 at 6 53 44 PM](https://user-images.githubusercontent.com/8582774/69367680-8dd84f00-0c4d-11ea-8e0d-2c650bac19f8.png)

## Steps to Reproduce (for bugs)
In `contracts/integrations/package.json`, set `@0x/migrations` version to `^4.4.0-beta.3`, run `yarn install && yarn test`. 

Same for 0x-coordinator-server.

## Your Environment

| Package | Version |
| ------: | :------ |

| Network |
| ------- |
| NAME    |

**Comment by hysz** [comment]
Migrations PR from `@0x/migrations@4.4.0-beta.2 → @0x/migrations@4.4.0-beta.3` is [here](https://github.com/0xProject/0x-monorepo/pull/2349/files).

Commit that broke coordinator server is [here](https://github.com/0xProject/0x-coordinator-server/commit/340b51f41161276f6fd372795b07bc3862baede2).

Commit that temporarily fixed coordinator server is [here](https://github.com/0xProject/0x-coordinator-server/commit/b160f4170c7b33699a53358e45ca3ba0c58a5f1e).

**Comment by hysz** [comment]
The bug manifests in a couple of ways (on the coordinator server):
1. For `fillOrder` the call to `Coordinator` reverts with `InvalidApprovalSignatureError()`
2. For batch filling, there is a revert in the server when it calls `devUtils..getOrderRelevantStates(signedOrders, signatures)`.

**Comment by xianny** [comment]
This is fixed now, thanks @dekz
