### ISSUE TITLE
General: Multiple Affiliate Fee Addresses in Forwarder

### ISSUE THREAD

**Issue by satosheth** [0xProject/0x-monorepo#2379]
This is a feature request to have multiple affiliate fee addresses when using the forwarder. An array of addresses would allow for more payment customization, but two affiliate fee addresses would likely  be sufficient for the majority of use cases. Each of these fee addresses would also need its corresponding fee amount. This would be a major driver in drawing new traffic to 0x relayers, especially in ERC721 and other unique asset exchanges.

Problem:
Currently, it is only possible to specify a single affiliate fee address when using the v2 forwarder. This single fee address is usually used by the relayer itself to collect fees on orders. Most users/third-parties want to earn some revenue from sharing links to listings on an exchange, but the current single fee address system does not allow for an easy way of paying them. 0x v3 will also not solve this issue because relayers will still want to collect fees from listings they obtain from other relayers, which must be done using the current single affiliate fee.

**Comment by abandeali1** [comment]
@satosheth this is actually mostly implemented in #2377 . Would you prefer multiple fee amounts that correspond to each fee recipient or a single fee that gets evenly split among each fee recipient?

**Comment by satosheth** [comment]
O great, I missed that. I would definitely prefer customizable fees per affiliate. That would be more important than having more than two affiliate fee addresses in my book.
