### ISSUE TITLE
order-utils : Could not decode ERC20 Proxy Data. Expected length of encoded data to be at least 74. Got 2

### ISSUE THREAD

**Issue by SvenMeyer** [0xProject/0x-monorepo#2419]
Setup 0x-launch-kit as described here:
https://asciinema.org/a/auhibPEAp9Q30veu4BanYUeXX

## Expected Behavior

I can create an order and it will show up in the "Orders" list.

## Current Behavior
nothing happens, order is not created
get an error message in Chrome console

```
Uncaught (in promise) Error: Could not decode ERC20 Proxy Data. Expected length of encoded data to be at least 74. Got 2
    at Object.assertIsERC20AssetData (asset_data_utils.js:303)
    at Object.decodeERC20AssetData (asset_data_utils.js:41)
    at kr (steps_modals_generation.ts:47)
    at actions.ts:173
    at f (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.forEach.e.<computed> [as next] (runtime.js:98)
    at n (asyncToGenerator.js:3)
    at c (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
```

## Possible Solution

no idea ...

## Steps to Reproduce (for bugs)

Currently running here:
http://34.231.171.135:3001

Setup 0x-launch-kit as described here:
https://asciinema.org/a/auhibPEAp9Q30veu4BanYUeXX

## Your Environment
Chromium 79
Metamask 7.7.1
network : Kovan

**Comment by dekz** [comment]
When the fee unit amount is set but there is no fee asset data. 

Moving to 0x-launch-kit repo, https://github.com/0xProject/0x-launch-kit/issues/30
