### ISSUE TITLE
[asset-swapper] Race condition between fetching a quote and fetching gas price

### ISSUE THREAD

**Issue by coopermaruyama** [0xProject/0x-monorepo#2424]
When asset-swapper's swap quoter is first instantiated, it begins polling gas prices from ethgasstation.info.

However, if you immediately get a quote after instantiating it, the gas price will be set to 0 in the quote due to the fact that it will execute before the first fetch of a gas price. This causes the tx to fail for obvious reasons including the protocol fee getting calculated as 0.

Here's a reproduction: https://codesandbox.io/s/asset-swapper-uniswap-bridge-repro-um6wf?fontsize=14&hidenavigation=1&theme=dark

I propose that the gas price should be set to null (or assume that a value of 0 for gasPrice means no fetch has occurred yet), and if so, should pass the `hardRefresh` option to the function that is eventually called by the quoter here: 

https://github.com/0xProject/0x-monorepo/blob/development/packages/asset-swapper/src/utils/protocol_fee_utils.ts#L25

**Comment by coopermaruyama** [comment]
#2421 has a fix for this, will close when merged

**Comment by dekz** [comment]
Merged into https://github.com/0xProject/0x-monorepo/pull/2406

**Comment by dorothy-zbornak** [comment]
#2406 merged into development.
