### ISSUE TITLE
0x.js : MultiAssetProxy Order returning as Fillable when it isn't

### ISSUE THREAD

**Issue by satosheth** [0xProject/0x-monorepo#2434]
## Expected Behavior

Calling devUtils.getOrderRelevantState() on a MAP order where one or more of the tokens in the order doesn't belong to the maker should return as Unfillable. Functions/tools that rely on order state working properly should flag this order as unfillable.

## Current Behavior

The orderstate of the order is 3 (fillable). The functions/tools that rely on the order state to be marked properly fail to report the order as unfillable (mesh, etc.).

## Steps to Reproduce (for bugs)

Example MAP order that should fail attached

## Your Environment
"0x.js": "^9.0.0",
"@0x/contract-wrappers": "^13.1.0",

**Comment by satosheth** [comment]
[failing_bundle.txt](https://github.com/0xProject/0x-monorepo/files/4043273/failing_bundle.txt)

**Comment by mzhu25** [comment]
Hi @satosheth, marking the order as Unfillable would be inconsistent with the Exchange's `getOrderInfo` method. Would it suit your needs if DevUtils instead returned `fillableTakerAssetAmount = 0` for those orders?

**Comment by satosheth** [comment]
@mzhu25 I couldn't find what different OrderStatus values there were on the v3 spec on github, but I would expect that the OrderStatus to be similar to what the old Order Watcher returned as InsufficientMakerBalance. However, the error itself doesn't really matter to me as long as 0x.js and 0x mesh can properly understand that those MAP orders are no longer fillable and then act appropriately with those orders.

**Comment by mzhu25** [comment]
@satosheth 
Right, so OrderStatus is a bit different. `devUtils.getOrderRelevantState` will return an OrderStatus of `Fillable` but `fillableTakerAssetAmount = 0` for a MAP order if the maker doesn't currently own one or more of the nested assets. 
Mesh considers the `fillableTakerAssetAmount` in its own order validator, effectively filtering out orders for which `fillableTakerAssetAmount = 0` (see https://github.com/0xProject/0x-mesh/blob/master/zeroex/ordervalidator/order_validator.go#L413). 
For 0x.js, but you should be able to do basically the same thing: 
```
const [orderInfo, fillableTakerAssetAmount, isValidSignature] = await devUtils.getOrderRelevantState(order, signature);
if (orderInfo.orderStatus != OrderStatus.Fillable || fillableTakerAssetAmount.isZero()) {
   // Order cannot be filled right now
}
```
Does that work for your use case?

**Comment by satosheth** [comment]
@mzhu25 that works!

**Comment by fabioberger** [comment]
@mzhu25 when I call `devUtils.getOrderRelevantState` on this order, I get this response:

```
[
  [{
    orderStatus: 3,
    orderHash: '0xab6853c7a0903c25446b1c29ab8a02d62de5bbe8d85c85ba4035031edf3c6652',
     orderTakerAssetFilledAmount: 0
  }],
  [ 12000000000000000 ],
  [ true ]
]
```

orderStatus `3` (Fillable), and the second return value (`fillableTakerAssetAmount`) is `12000000000000000`, not `0`. 

`fillableTakerAssetAmount` should be returned as `0` for this order, so I actually agree with @satosheth that DevUtils.sol is not working as expected.

Mind taking a deeper look?

**Comment by fabioberger** [comment]
Here is a repro: https://github.com/0xProject/debug_devutils_issue/

**Comment by mzhu25** [comment]
ok, so looks like the most recent version of DevUtils (which fixes the above issue) wasn't actually deployed 😬 
Working on a couple of minor changes to DevUtils anyway, so I'll update here once it's been redeployed

**Comment by mzhu25** [comment]
https://etherscan.io/address/0xd74ff1bfe071e4586c5ab969335a649e3bd9c518
Redeployed and verified that the example now works as expected
cc @satosheth

**Comment by fabioberger** [comment]
@mzhu25 is it working as expected on Kovan, Rinkeby and Ropsten as well? We support those networks in addition to mainnet in Mesh.

**Comment by mzhu25** [comment]
> @mzhu25 is it working as expected on Kovan, Rinkeby and Ropsten as well? We support those networks in addition to mainnet in Mesh.

Yup:
https://kovan.etherscan.io/address/0xd4690a51044db77d91d7aa8f7a3a5ad5da331af0
https://ropsten.etherscan.io/address/0x584bb48a4f6282bc62eb14d126fc3296af4c3eaa
https://rinkeby.etherscan.io/address/0x584bb48a4f6282bc62eb14d126fc3296af4c3eaa
