### ISSUE TITLE
@0x/utils: Extra space in `provider.send` varies

### ISSUE THREAD

**Issue by chpwssn** [0xProject/0x-monorepo#2556]
## Expected Behavior

When working with different versions and types of web3.js providers the `provider.send` signature should have whitespace replaced so that it matches the comparison in the `send` normalization portion of `standardizeOrThrow`.

## Current Behavior

[The current function signature check implementation](
https://github.com/0xProject/0x-monorepo/blob/development/packages/utils/src/provider_utils.ts#L77) uses `String.prototype.replace()` with a literal string: `.replace(" ", "")`. This only replaces the first space in the string meaning signatures like `function (payload, callback)` get transformed to `function(payload, callback)` rather than being transformed to `function(payload,callback)` as desired.

#2494 likely worked but as web3.js shifts, the signature differ.

## Possible Solution

Using a regular expression with a global flag `.replace(/\s+/g, "")` would replace all of the whitespaces in the provider's `send` signature with empty strings.

I can open a PR with the above change if it's acceptable.

## Steps to Reproduce (for bugs)

We're seeing this behavior and have made the change to the package in `node_modules` when working with `web3-providers-ws` (Websocket providers) and `@0x/utils@5.4.1`

## Your Environment

| Package | Version |
| ------: | :------ |
| @0x/utils | 5.4.1 |
| web3-providers-ws | {1.2.1, 1.2.4, 1.2.6}|

| Network |
| ------- |
| ganache privnet |

**Comment by adamlaska** [comment]
>
