### ISSUE TITLE
Unable to fill order via OTC

### ISSUE THREAD

**Issue by tech-somish** [0xProject/0x-monorepo#299]
Hi,
I tried creating an order via OTC and filling the same. However I am getting the following error message.
![image](https://user-images.githubusercontent.com/33712347/34356761-ddfaad6a-ea68-11e7-8e36-1f044d6fcd61.png)

 **JSON of the generated order**  : 
{"maker":{"address":"0x7266c50f1f461d2748e675b907ef22987f6b5358","token":{"name":"MLN","symbol":"MLN","decimals":18,"address":"0x323b5d4c32345ced77393b3530b1eed0f346429d"},"amount":"1850000000000000000","feeAmount":"0"},"taker":{"address":"","token":{"name":"ETH","symbol":"ETH","decimals":18,"address":"0xd0a1e359811322d97991e03f863a0c30c2cf029c"},"amount":"320000000000000000","feeAmount":"0"},"expiration":"1514347479","feeRecipient":"0x0000000000000000000000000000000000000000","salt":"99033804502856343259430181946001007533635816863503102978577997033734866165564","signature":{"v":27,"r":"0x3d175dc82add08503a083ee791d75e06caaf86664cf9d4ba76f99246ff282e00","s":"0x3a602580593d51845e7ac667d633e06a3fbbe5ba17687866932fc0c64c0a10a8","hash":"0xd434ea708aee8decf8facd747a3955d9f2e6ef834d9b91102ec775a2eae0b138"},"exchangeContract":"0x90fe2af704b34e0224bf2299c838e04d4dcf1364","networkId":42}

Kindly Help.

**Comment by fabioberger** [comment]
Thanks for the submission, this is indeed a bug. We will debug ASAP.
