### ISSUE TITLE
yarn install fails on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by pelsasser** [0xProject/0x-monorepo#343]
Looks like node-hid is the probably cause of the failure
This is a clean ubuntu install, is anyone else having similar issues?

```

error /home/pelsasser/0x.js/node_modules/node-hid: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/pelsasser/0x.js/node_modules/node-hid
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@8.9.4 | linux | x64
node-pre-gyp info check checked for "/home/pelsasser/0x.js/node_modules/node-hid/build/Release/HID.node" (not found)
node-pre-gyp http GET https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.4 and node@8.9.4 (node-v57 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pelsasser/0x.js/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pelsasser/.node-gyp/8.9.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pelsasser/.node-gyp/8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pelsasser/.node-gyp/8.9.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pelsasser/0x.js/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pelsasser/0x.js/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
compilation terminated.
hidapi.target.mk:97: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: Leaving directory '/home/pelsasser/0x.js/node_modules/node-hid/build'
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.10.0-28-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pelsasser/0x.js/node_modules/node-hid/build/Release/HID.node" "--module_name=HID" "--module_path=/home/pelsasser/0x.js/node_modules/node-hid/build/Release"
gyp ERR! cwd /home/pelsasser/0x.js/node_modules/node-hid
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pelsasser/0x.js/node_modules/node-hid/build/Release/HID.node --module_name=HID --module_path=/home/pelsasser/0x.js/node_modules/node-hid/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pelsasser/0x.js/node_modules/node-hid/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.10.0-28-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/pelsasser/0x.js/node_modules/node-hid/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pelsasser/0x.js/node_modules/node-hid
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 

```

**Comment by jawknee530** [comment]
I just attempted to npm install @0xproject/subproviders and got a similar issue due to node-hid

```
jallen@be-970:~/ZeroExTrading$ npm install @0xproject/subproviders

> node-hid@0.5.4 install /home/jallen/ZeroExTrading/node_modules/node-hid
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/bin/node',
node-pre-gyp verb cli   '/home/jallen/ZeroExTrading/node_modules/node-hid/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@8.9.4 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/home/jallen/ZeroExTrading/node_modules/node-hid/build/Release/HID.node" (not found)
node-pre-gyp http GET https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.4 and node@8.9.4 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
make: Entering directory '/home/jallen/ZeroExTrading/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c: In function ‘hid_read_timeout’:
../hidapi/libusb/hid.c:1078:6: warning: variable ‘bytes_read’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
  int bytes_read = -1;
      ^
  AR(target) Release/obj.target/hidapi.a
  COPY Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc: In member function ‘void HID::readResultsToJSCallbackArguments(HID::ReceiveIOCB*, v8::Local<v8::Value>*)’:
../src/HID.cc:209:74: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     Local<Object> buf = nodeBufConstructor->NewInstance(1, nodeBufferArgs);
                                                                          ^
In file included from /home/jallen/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from ../src/HID.cc:30:
/home/jallen/.node-gyp/8.9.4/include/node/v8.h:3832:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/jallen/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/HID.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE HID::readTimeout(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/HID.cc:296:41: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   const int timeout = info[0]->ToUint32()->Value();
                                         ^
In file included from ../src/HID.cc:30:0:
/home/jallen/.node-gyp/8.9.4/include/node/v8.h:9737:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/HID.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE HID::getFeatureReport(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/HID.cc:316:28: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       || info[1]->ToUint32()->Value() == 0) {
                            ^
In file included from ../src/HID.cc:30:0:
/home/jallen/.node-gyp/8.9.4/include/node/v8.h:9737:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/HID.cc:320:46: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   const uint8_t reportId = info[0]->ToUint32()->Value();
                                              ^
In file included from ../src/HID.cc:30:0:
/home/jallen/.node-gyp/8.9.4/include/node/v8.h:9737:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
../src/HID.cc:322:41: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   const int bufSize = info[1]->ToUint32()->Value();
                                         ^
In file included from ../src/HID.cc:30:0:
/home/jallen/.node-gyp/8.9.4/include/node/v8.h:9737:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
  SOLINK_MODULE(target) Release/obj.target/HID.node
  COPY Release/HID.node
make: Leaving directory '/home/jallen/ZeroExTrading/node_modules/node-hid/build'
node-pre-gyp info ok
npm notice save @0xproject/subproviders is being moved from dependencies to devDependencies
+ @0xproject/subproviders@0.3.2
added 123 packages in 13.231s
```

**Comment by pelsasser** [comment]
thanks @abandeali1

**Comment by fabioberger** [comment]
@pelsasser @jawknee530 this is a bit of a hack, but if you add the following environment variable, it should work: `CIRCLE_CI=true`. We ran into this issue on CircleCi and so conditionally omit importing `node_hid` when this flag is set to true. 

Not sure if you can use the LedgerSubprovider in a node context without importing `node_hid`. Are you trying to use it in a browser context?

**Comment by sunnycn2013** [comment]
11

**Comment by sunnycn2013** [comment]
@fabioberger   Hello fabioberger , I found a problem, after download 0x's reponsitory, I perform under MAC 'yarn install' everything is ok, but  I perform 'yarn install'  under centos 64 - bit systems is above error. I found under centos execution `yarn install` to pull library node - hid Linux version of the library (404 https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz, this link is invalid, so will the install error),

Under the MAC will also go to pull `node-hid` the MAC version of the library, this time everything is normal, not an error, the error will only on Linux system error.

**Comment by pelsasser** [comment]
@fabioberger - didn't seem to work

I got the same errors with node-hid even with the environment variable set. 

```
~/0x.js$ echo $CIRCLE_CI 
true
```

**Comment by dekz** [comment]
At the moment we're using the a ledgerco package which requires node-hid as a dependency. Looks like some of those prebuilts aren't built against latest node versions (since node-hid has moved on).

You should be able to build from source if you have the right developer packages installed.

On centos you can find what is missing from running: 
`yum provides */libusb.h`

Then install the package mentioned above, for example:
`yum install libusb1-devel`

For ubuntu try:
`apt-get install -y libhidapi-dev libusb-1.0-0-dev`

We will update the ledger package soon to be the latest (they've re-organised and we can now drop node-hid)

**Comment by dekz** [comment]
Ledger Subprovider has been updated. Node-hid transport is now an optional package and shouldn't cause the whole install to fail if the package cannot be compiled.

@pelsasser @sunnycn2013 @jawknee530 any chance you can try pulling the latest and trying again?

**Comment by sunnycn2013** [comment]
@dekz  `node-pre-gyp http GET https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz` has solved, very very good !!!

But when I run `yarn run dev` on  '0x.js/packages/website ', I have got a new error left:

`
localhost:website ccguo$ yarn run dev
yarn run v1.3.2
$ webpack-dev-server --content-base public --https
Project is running at https://localhost:3572/
webpack output is served from /
Content not from webpack is served from /Users/ccguo/Documents/ETH/0x.js/packages/website/public
404s will fallback to /index.html

[at-loader] Using typescript@2.7.1 from typescript and "tsconfig.json" from /Users/ccguo/Documents/ETH/0x.js/packages/website/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 1.107 sec.
Hash: edb2b3fe54ec3a157c33
Version: webpack 3.11.0
Time: 27897ms
                          Asset     Size  Chunks                    Chunk Names
               bundle-portal.js   7.1 MB       0  [emitted]  [big]  portal
           bundle-zeroExDocs.js   217 kB       1  [emitted]         zeroExDocs
          bundle-connectDocs.js   211 kB       2  [emitted]         connectDocs
    bundle-smartContractDocs.js   211 kB       3  [emitted]         smartContractDocs
                      bundle.js  7.25 MB       4  [emitted]  [big]  main
           bundle-portal.js.map  8.67 MB       0  [emitted]         portal
       bundle-zeroExDocs.js.map   314 kB       1  [emitted]         zeroExDocs
      bundle-connectDocs.js.map   305 kB       2  [emitted]         connectDocs
bundle-smartContractDocs.js.map   304 kB       3  [emitted]         smartContractDocs
                  bundle.js.map   8.9 MB       4  [emitted]         main
  [29] /Users/ccguo/Documents/ETH/0x.js/node_modules/react-dom/index.js 59 bytes {4} [built]
  [33] ./ts/types.ts 11.5 kB {4} [built]
 [614] multi (webpack)-dev-server/client?https://localhost:3572 ./ts/index.tsx 40 bytes {4} [built]
 [615] (webpack)-dev-server/client?https://localhost:3572 7.93 kB {4} [built]
 [634] ./ts/index.tsx 7.48 kB {4} [built]
 [848] ./ts/containers/about.ts 541 bytes {4} [built]
[1474] ./ts/containers/wiki.ts 535 bytes {4} [built]
[1477] ./ts/lazy_component.tsx 6.31 kB {4} [built]
[1478] ./ts/redux/reducer.ts 8.31 kB {4} [built]
[1489] ./ts/utils/mui_theme.ts 1.46 kB {4} [built]
[1490] /Users/ccguo/Documents/ETH/0x.js/node_modules/whatwg-fetch/fetch.js 12.7 kB {4} [built]
[1491] /Users/ccguo/Documents/ETH/0x.js/node_modules/basscss/css/basscss.css 865 bytes {4} [built]
[1493] ./less/all.less 1.05 kB {4} [built]
[1495] ./ts/containers/portal.ts 2.86 kB {0} [built]
[1496] ./ts/containers/zero_ex_js_documentation.ts 7.93 kB {1} [built]
    + 2289 hidden modules

WARNING in /Users/ccguo/Documents/ETH/0x.js/node_modules/ethereumjs-vm/lib/runJit.js
13:16-23 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ethereumjs-vm/lib/runJit.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ethereumjs-vm/lib/index.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ethereumjs-vm/index.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/statemanager.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/subproviders/geth_api_double.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/provider.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/index.js
 @ ../subproviders/lib/src/subproviders/ganache.js
 @ ../subproviders/lib/src/index.js
 @ ./ts/blockchain.ts
 @ ./ts/components/portal.tsx
 @ ./ts/containers/portal.ts
 @ ./ts/index.tsx
 @ multi (webpack)-dev-server/client?https://localhost:3572 ./ts/index.tsx

ERROR in /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/database/filedown.js
Module not found: Error: Can't resolve 'fs' in '/Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/database'
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/database/filedown.js 4:9-22
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/database.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/blockchain_double.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/statemanager.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/subproviders/geth_api_double.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/provider.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/index.js
 @ ../subproviders/lib/src/subproviders/ganache.js
 @ ../subproviders/lib/src/index.js
 @ ./ts/blockchain.ts
 @ ./ts/components/portal.tsx
 @ ./ts/containers/portal.ts
 @ ./ts/index.tsx
 @ multi (webpack)-dev-server/client?https://localhost:3572 ./ts/index.tsx

ERROR in /Users/ccguo/Documents/ETH/0x.js/node_modules/rustbn.js/lib/index.asm.js
Module not found: Error: Can't resolve 'fs' in '/Users/ccguo/Documents/ETH/0x.js/node_modules/rustbn.js/lib'
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/rustbn.js/lib/index.asm.js 1:1297-1310 1:150825-150838
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/rustbn.js/index.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ethereumjs-vm/lib/precompiled/06-ecadd.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ethereumjs-vm/lib/index.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ethereumjs-vm/index.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/statemanager.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/subproviders/geth_api_double.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/provider.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/index.js
 @ ../subproviders/lib/src/subproviders/ganache.js
 @ ../subproviders/lib/src/index.js
 @ ./ts/blockchain.ts
 @ ./ts/components/portal.tsx
 @ ./ts/containers/portal.ts
 @ ./ts/index.tsx
 @ multi (webpack)-dev-server/client?https://localhost:3572 ./ts/index.tsx

ERROR in /Users/ccguo/Documents/ETH/0x.js/node_modules/tmp/lib/tmp.js
Module not found: Error: Can't resolve 'fs' in '/Users/ccguo/Documents/ETH/0x.js/node_modules/tmp/lib'
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/tmp/lib/tmp.js 13:11-24
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/database.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/blockchain_double.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/statemanager.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/subproviders/geth_api_double.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/lib/provider.js
 @ /Users/ccguo/Documents/ETH/0x.js/node_modules/ganache-core/index.js
 @ ../subproviders/lib/src/subproviders/ganache.js
 @ ../subproviders/lib/src/index.js
 @ ./ts/blockchain.ts
 @ ./ts/components/portal.tsx
 @ ./ts/containers/portal.ts
 @ ./ts/index.tsx
 @ multi (webpack)-dev-server/client?https://localhost:3572 ./ts/index.tsx
webpack: Failed to compile.


`

**Comment by fabioberger** [comment]
@sunnycn2013 thanks for the heads up. Please try pulling the latest from master and trying again. Fix is here: https://github.com/0xProject/0x-monorepo/commit/0225d34b742072fb846fa2047cb4b0559069dfe8

Also, please open a new issue in the future. This was not related to this issue.

**Comment by sunnycn2013** [comment]
OK

**Comment by jawknee530** [comment]
I'm still having this issue on ubuntu 16.04 when installing with npm install 0x.js. Is the npm version up to date?

**Comment by dekz** [comment]
@jawknee530 I was able to fully build the latest development from a git clone, and an `npm install 0x.js` inside a Node Docker container. What error are you seeing in particular (there are a few here)?
