### ISSUE TITLE
Torrent like Netwok Request

### ISSUE THREAD

**Issue by mikailcetinkaya** [0xProject/0x-monorepo#380]
Hello ;

Binance is intentionally down , many traders locked there .
When 0x will implement peer to peer ; torrent like network ?
This is cited in your whitepaper.

For such a development what do you require?
How may i help you?
I am a crypto trader + Software Developer.

Best Regards , 
Thank you.

**Comment by LogvinovLeon** [comment]
It's not planned in the near future.
For now we're focused on the architecture where the order book is maintained by relayers, which are non-custodial. You can try any of them. Below is the list of those that are already live.

https://app.radarrelay.com/
https://app.paradex.io
https://idex.market/
https://ddex.io/
https://ercdex.com/
https://decent.exchange/

**Comment by fabioberger** [comment]
@mikailcetinkaya since 0x protocol does not specify the way in which orders are relayed between traders, anyone can build a peer-to-peer, torrent-like Relayer on top of it. Feel free to make it happen!
