### ISSUE TITLE
cli.js missing in deployer 0.3.2

### ISSUE THREAD

**Issue by adklempner** [0xProject/0x-monorepo#463]
## Expected Behavior

Running `0x-deployer compile` in a project with `@0xproject/deployer` installed should should run the compiler defined in `compiler.js`

## Current Behavior

Returns error:
`/bin/sh: 0x-deployer: command not found`

## Possible Solution

Publish `lib/src/cli.js` in the package

## Steps to Reproduce (for bugs)

```
1. yarn add @0xproject/deployer
2. yarn prebuild
 0x-deployer compile --contracts ${npm_package_config_contracts} --contracts-dir src/contracts --artifacts-dir src/artifacts
```

## Your Environment

Running in [https://github.com/adklempner/typescript-web3-boilerplate](https://github.com/adklempner/typescript-web3-boilerplate/tree/c29e6f1b365f2af9dbbc119b06474a394f9860a3)

**Comment by fabioberger** [comment]
Fixed in 0.3.3.
