### ISSUE TITLE
wrong declaration of FilterResult.get() in index.d.ts

### ISSUE THREAD

**Issue by thorstenhirsch** [0xProject/0x-monorepo#471]
## Expected Behavior

All callbacks are declared more or less like this:
`callback: (err: Error, result: string)`

Except for FilterResult.get(), which is declared like this:
`get(callback: () => void): void;`

But that's wrong as you can see in the web3 docs (https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter):
```
// get all past logs again.
var myResults = filter.get(function(error, logs){ ... });
```

Please fix in index.d.tx

**Comment by thorstenhirsch** [comment]
Okay, I think this is the correct fix:
`callback: (err: Error, logs: string[])`
But let me test it first. Maybe I need to add "| null" or "| undefined". I will come back to you next week.

**Comment by fabioberger** [comment]
Any update on this @thorstenhirsch?

**Comment by thorstenhirsch** [comment]
Sorry, I totally forgot that one.
Please stay tuned, I will send you a PR within the next days.

2018-04-17 12:00 GMT+02:00 Fabio Berger <notifications@github.com>:
