### ISSUE TITLE
isBigNumber assertion expects old version of BN.js library

### ISSUE THREAD

**Issue by jwvictor** [0xProject/0x-monorepo#513]
## Expected Behavior

BigNumber objects should pass this assertion with all versions of the library.

## Current Behavior

Fails with newer versions of the BN.js library in which `BigNumber.isBigNumber(x)` is correct (as opposed to the current `value.isBigNumber`).

## Possible Solution

Replace `value.isBigNumber` with `BigNumber.isBigNumber(value)`

## Steps to Reproduce (for bugs)

Try to call `fillOrder` with newest version of BN.js (^6.0.0).

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.35.0  |
| `Exchange Contract` | ?      |

| Network |
| ------- |
| Mainnet    |

**Comment by jwvictor** [comment]
Also requires changing `lessThan` to `isLessThan`:

```        var isNegative = value.isLessThan(0);```

**Comment by jwvictor** [comment]
@fabioberger Awesome I'll try that, thank you.

Do you have a recommended stack I should develop on? I'm currently on Node v9 and I've noticed that the generated `fillOrderAsync` just yields after the assertions and never does anything. Is it possible I need Babel or something setup to use 0x.js?

I figured this may be the case since the current version of Node only supports `import` statements on an experimental basis.

TIA!

**Comment by jwvictor** [comment]
@fabioberger May have found the culprit. I've been using `web3 ^1.0.0-beta.30` in my code whereas the tutorial code has `^0.20.0`. Is this a known issue?

**Comment by jwvictor** [comment]
The central issue seems to be incompatibility between the old and new versions of `web3.js`. At one point I had at least the `signOrderHash` capability working but now can't even seem to get that going. Should I go ahead and abstract out my 0x code into a separate microservice until lib support catches up? Is there any way to make 0x.js work with `web3 1.0-beta`?

**Comment by fabioberger** [comment]
@jwvictor 0x.js should work with web3 1.0.X, can you paste a minimal repro?

**Comment by fabioberger** [comment]
@jwvictor 0x.js should work with web3 1.0.X, can you paste a minimal repro?

**Comment by fabioberger** [comment]
PS: The codebase is in Typescript, and so are the examples in the wiki. I'd highly recommend taking the time to learn TS (https://github.com/basarat/typescript-book), it's well worth the learning curve.

That being said, you can use 0x.js in Node, and I use it with v9.8.0. You might just need to adjust the code examples from the tutorials.

**Comment by fabioberger** [comment]
Closing for now, feel free to re-open if necessary.
