### ISSUE TITLE
@0xproject/typescripts-typings mixes external types with internal additions

### ISSUE THREAD

**Issue by ritave** [0xProject/0x-monorepo#529]
@0xproject/typescript-typings provides additional types for projects that have no such types, such as web3 0.*, and thus is an important source of tooling for other open-source projects. We have been using web3-typescript-typings for a few months now.

But now, due to change to type_roots, stuff that shouldn't be exposed is intermixed with stuff that's internal to 0x project.

For example - https://github.com/0xProject/0x-monorepo/blob/development/packages/typescript-typings/types/chai/index.d.ts#L119
If I want to use whole type roots, I have to not only include web3, but also your chai overloads that adds chai-as-promised assertions, which are not there by default, thus breaking typescript's type safety for projects no using chai-as-promised.

Separate external types with what 0xproject is using internally.

**Comment by dekz** [comment]
Can you not selectively choose the ones you wish to use in your `tsconfig.json`? For example:

```
"typeRoots": [
  "node_modules/@0xproject/typescript-typings/types/web3/index.d.ts", 
  "node_modules/@types"
],
```

**Comment by LogvinovLeon** [comment]
@dekz That's not true. We've decided that we will move out types to DT and leave only the ones that are different for us (chai)
