### ISSUE TITLE
Including 0x.js

### ISSUE THREAD

**Issue by leoplct** [0xProject/0x-monorepo#587]
Sorry for newbie question.
I downloaded the UMD module from releases page, but I cannot find the 0x.js file to be included in my html page. 
How it suppose to work?

```
UMD:
Install

Download the UMD module from our releases page and add it to your project.

Import

<script type="text/javascript" src="0x.js"></script>
```

**Comment by fabioberger** [comment]
@leoplct 

1. Visit https://github.com/0xProject/0x-monorepo/releases/tag/0x.js%400.37.2
2. Download `index.min.js`
3. Move it to your project and reference it via directory path in `script` `src`.

**Comment by dorijan** [comment]
Thx, this is what I was looking for too...

**Comment by fabioberger** [comment]
Np!

**Comment by outprog** [comment]
@fabioberger How can I get 0x.js@9.1.6 index.min.js.
I download source, yarn build it, report:
```
FetchError: response timeout at https://contracts/zero-ex/ethereum.github.io/solc-bin/bin/soljson-v0.6.12+commit.27d51765.js over limit: 20000
```
I don't konw why url append `contracts/zero-ex`, make yarn build not work.
