### ISSUE TITLE
Register my own ERC20 tokens for 0x, right now we can not do this by ourselves?

### ISSUE THREAD

**Issue by tantao9323** [0xProject/0x-monorepo#591]
When we are testing 0x on local testrpc, we are trying to transfer our own defined token "SimpleToken" to be exchange by WETH, by we always got INSUFFICIENT_MAKER_BALANCE. After a short research, we noticed that our token "SimpleToken" has not been registered in blockchain. Here is the actual tradable tokens we found in local testrpc:
[ { address: '0x1d7022f5b17d2f8b695918fb48fa1089c9f85401',
    name: '0x Protocol Token',
    symbol: 'ZRX',
    decimals: 18 },
  { address: '0x871dd7c2b4b25e1aa18728e9d5f2af4c4e431f5c',
    name: 'Ether Token',
    symbol: 'WETH',
    decimals: 18 },
  { address: '0x07f96aa816c1f244cbc6ef114bb2b023ba54a2eb',
    name: 'Augur Reputation Token',
    symbol: 'REP',
    decimals: 18 },
  { address: '0x6dfff22588be9b3ef8cf0ad6dc9b84796f9fb45f',
    name: 'Digix DAO Token',
    symbol: 'DGD',
    decimals: 18 },
  { address: '0xf22469f31527adc53284441bae1665a7b9214dba',
    name: 'Golem Network Token',
    symbol: 'GNT',
    decimals: 18 },
  { address: '0x8d61158a366019ac78db4149d75fff9dda51160d',
    name: 'MakerDAO',
    symbol: 'MKR',
    decimals: 18 },
  { address: '0xb69e673309512a9d726f87304c6984054f87a93b',
    name: 'Melon Token',
    symbol: 'MLN',
    decimals: 18 } ]
But, we can not find any way to submit or register our own defined token to this token registry. How can we do that?

BTW, our environment:
0x 0.37.2
web3 0.20.6
node 8.11.0
truffle 4.1.8

Thanks for your guys great work!

**Comment by fabioberger** [comment]
@tantao9323 your token does not need to be registered in the TokenRegistry in order to be tradeable with 0x. Your issue is not what you think it is.

`INSUFFICIENT_MAKER_BALANCE` typically means that the account creating the order does not have a sufficient balance of your time.

**Comment by tantao9323** [comment]
@fabioberger Thanks for your reply, I had found the reason.
