### ISSUE TITLE
Only taker pay for the transaction's fee?

### ISSUE THREAD

**Issue by tantao9323** [0xProject/0x-monorepo#631]
we are testing tokens' exchange proccess, and we found it seems only taker can pay the fee of transaction for relayer even if we explicitly set the makerFee in our order. Is there a fixed setting in the 0x protocol ? The following is our codes snippet:
 
**this is order definition:**
const order = {
maker: sorteOrders[0].maker_address,
taker: sorteOrders[0].taker_address,
makerTokenAddress: makerTokenInfo.address,
takerTokenAddress: takerTokenInfo.address,
exchangeContractAddress: exchangeAddress,
salt: ZeroEx.generatePseudoRandomSalt(),
makerFee: ZeroEx.toBaseUnitAmount(new BigNumber(sorteOrders[0].handle_fee), decimals), // handle_fee=1.0,decimals=18
takerFee: ZeroEx.toBaseUnitAmount(new BigNumber(sorteOrders[0].handle_fee), decimals), // handle_fee=1.0,decimals=18
feeRecipient: '0x91c987bf62d25945db517bdaa840a6c661374402',
makerTokenAmount: ZeroEx.toBaseUnitAmount(new BigNumber(sorteOrders[0].maker_token), decimals),
takerTokenAmount: ZeroEx.toBaseUnitAmount(new BigNumber(sorteOrders[0].taker_token), decimals),
expirationUnixTimestampSec: new BigNumber(sorteOrders[0].deadline * 1000)
}; 

**this is transaction handle by relayer:**
const orderHash = ZeroEx.getOrderHashHex(order);
const shouldAddPersonalMessagePrefix = false;
const ecSignature = await zeroEx.signOrderHashAsync(orderHash, sorteOrders[0].maker_address, shouldAddPersonalMessagePrefix);
const signedOrder = {
...order,
ecSignature,
};
await zeroEx.exchange.validateOrderFillableOrThrowAsync(signedOrder);
const shouldThrowOnInsufficientBalanceOrAllowance = true;
const fillTakerTokenAmount = ZeroEx.toBaseUnitAmount(new BigNumber(sorteOrders[0].taker_address), decimals);
const txHash = await zeroEx.exchange.fillOrderAsync(signedOrder, fillTakerTokenAmount, shouldThrowOnInsufficientBalanceOrAllowance, sorteOrders[0].taker_address);
const txReceipt = await zeroEx.awaitTransactionMinedAsync(txHash); 

**this is balance before transaction:**
makerZRXBalance before 999999703866666666666666658
makerASIMBalance before 9996999000000000000000
takerZRXBalance before 266119999999999999970
takerASIMBalance before 933333333333334
feeRecipientZRXBalance before 30000000000000000040
feeRecipientASIMBalance before 0
 
**this is balance after transaction:**
makerZRXBalance after 999999704866666666666666658
makerASIMBalance after 9995999000000000000000
takerZRXBalance after 263119999999999999970
takerASIMBalance after 1000933333333333334
feeRecipientZRXBalance after 32000000000000000040
feeRecipientASIMBalance after 0
 
 
Is there something wrong in our code?
 
Thank you

**Comment by fabioberger** [comment]
@tantao9323 I cannot help without knowing the values of `makerTokenInfo`, `takerTokenInfo`, `sorteOrders[0].maker_token` and `sorteOrders[0].taker_token`.

**Comment by tantao9323** [comment]
@fabioberger  thanks for your reply. `makerTokenInfo` and `takerTokenInfo` are just objects I defined, they all have the property `address` represent tokenContractAddress. `sorteOrders[0].maker_token` is `1.0` and `sorteOrders[0].taker_token`  is `2.0`.

**Comment by tantao9323** [comment]
@fabioberger I read the exchangeContract's code, it seems that makerFee and takerFee only be ZRX?

**Comment by fabioberger** [comment]
@tantao9323 yes, only ZRX.
