### ISSUE TITLE
Error: Specified ownerAddress isn't a vailable through the supplied web3 provider

### ISSUE THREAD

**Issue by ksfz2011** [0xProject/0x-monorepo#634]
## Expected Behavior

With the code mentioned in the comments below, I plan to transfer between WETH --> ETH and other ERC20 based tokens.

## Current Behavior

I am getting error as below:
Error: Specified ownerAddress 0x1268ccbb5b10bfc43365a1e6c4db9db1d3411915 isn't available through the supplied web3 provider
    at Object.assert (D:\Installations\nodejs_npm\0x\0x-starter-project\node_modules\@0xproject\assert\lib\src\index.js:73:19)
    at Object.<anonymous> (D:\Installations\nodejs_npm\0x\0x-starter-project\node_modules\0x.js\lib\src\utils\assert.js:63:41)
    at step (D:\Installations\nodejs_npm\0x\0x-starter-project\node_modules\0x.js\lib\src\utils\assert.js:40:23)
    at Object.next (D:\Installations\nodejs_npm\0x\0x-starter-project\node_modules\0x.js\lib\src\utils\assert.js:21:53)
    at fulfilled (D:\Installations\nodejs_npm\0x\0x-starter-project\node_modules\0x.js\lib\src\utils\assert.js:12:58)
    at <anonymous>    at process._tickCallback (internal/process/next_tick.js:182:7)

## Possible Solution

NA

## Steps to Reproduce (for bugs)

I started with [Create, Validate, Fill Order](https://github.com/0xProject/wiki/blob/master/tutorials/Create%2C-Validate%2C-Fill-Order.md)
successful with TestRPC and now I am trying to extend it so that I can do transactions on test network Kovan.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.36.3 |
|           `web3` | 0.6.4   |
| `@0xproject/web3-wrapper` | 0.6.4      |
| `bignumber.js` | 0.17.0-alpha  |

| Network |
| ------- |
| Kovan   |

**Comment by ksfz2011** [comment]
var Web3Wrapper =  require ('@0xproject/web3-wrapper');
var ZeroEx = require ('0x.js').ZeroEx;
var BigNumber = require ('bignumber.js');
var Web3 = require('web3');


const KOVAN_NETWORK_ID = 42;
const KOVAN_ENDPOINT = 'https://kovan.infura.io/';


const configs = {
    networkId: KOVAN_NETWORK_ID,
};


// Number of decimals to use (for ETH and ZRX)
const DECIMALS = 18;

const mainAsync = async () => {

	const provider = new Web3.providers.HttpProvider(KOVAN_ENDPOINT);
	const zeroEx = new ZeroEx(provider, configs);

    // Addresses
    const WETH_ADDRESS = zeroEx.etherToken.getContractAddressIfExists(); // The wrapped ETH token contract
    const ZRX_ADDRESS = zeroEx.exchange.getZRXTokenAddress(); // The ZRX token contract
    // The Exchange.sol address (0x exchange smart contract)
    const EXCHANGE_ADDRESS = zeroEx.exchange.getContractAddress();

    // Getting list of accounts
    const accounts = await zeroEx.getAvailableAddressesAsync();
    //console.log('accounts: ', accounts);

    // Set our addresses
	
	var makerAddress = '0x1268CcBB5b10bFC43365A1e6C4Db9dB1d3411915';
	var takerAddress = '0x0A1cE1dFffcfd07f6b34DB848441cb5Cc48CF39f';
	
	makerAddress = makerAddress.toLowerCase();
	takerAddress = takerAddress.toLowerCase();

    const setMakerAllowTxHash = await zeroEx.token.setUnlimitedProxyAllowanceAsync(ZRX_ADDRESS, makerAddress);
    await zeroEx.awaitTransactionMinedAsync(setMakerAllowTxHash);

    const setTakerAllowTxHash = await zeroEx.token.setUnlimitedProxyAllowanceAsync(WETH_ADDRESS, takerAddress);
    await zeroEx.awaitTransactionMinedAsync(setTakerAllowTxHash);
    console.log('Taker allowance mined...');

    // Deposit WETH
    const ethAmount = new BigNumber(1);
    const ethToConvert = ZeroEx.toBaseUnitAmount(ethAmount, DECIMALS); // Number of ETH to convert to WETH

    const convertEthTxHash = await zeroEx.etherToken.depositAsync(WETH_ADDRESS, ethToConvert, takerAddress);
    await zeroEx.awaitTransactionMinedAsync(convertEthTxHash);
    console.log(`${ethAmount} ETH -> WETH conversion mined...`);

    // Generate order
    const order = {
        maker: makerAddress,
        taker: ZeroEx.NULL_ADDRESS,
        feeRecipient: ZeroEx.NULL_ADDRESS,
        makerTokenAddress: ZRX_ADDRESS,
        takerTokenAddress: WETH_ADDRESS,
        exchangeContractAddress: EXCHANGE_ADDRESS,
        salt: ZeroEx.generatePseudoRandomSalt(),
        makerFee: new BigNumber(0),
        takerFee: new BigNumber(0),
        makerTokenAmount: ZeroEx.toBaseUnitAmount(new BigNumber(0.2), DECIMALS), // Base 18 decimals
        takerTokenAmount: ZeroEx.toBaseUnitAmount(new BigNumber(0.3), DECIMALS), // Base 18 decimals
        expirationUnixTimestampSec: new BigNumber(Date.now() + 3600000), // Valid for up to an hour
    };

    // Create orderHash
    const orderHash = ZeroEx.getOrderHashHex(order);

    // Signing orderHash -> ecSignature
    const shouldAddPersonalMessagePrefix = false;
    const ecSignature = await zeroEx.signOrderHashAsync(orderHash, makerAddress, shouldAddPersonalMessagePrefix);

    // Appending signature to order
    const signedOrder = {
        ...order,
        ecSignature,
    };

    // Verify that order is fillable
    await zeroEx.exchange.validateOrderFillableOrThrowAsync(signedOrder);

    // Try to fill order
    const shouldThrowOnInsufficientBalanceOrAllowance = true;
    const fillTakerTokenAmount = ZeroEx.toBaseUnitAmount(new BigNumber(0.1), DECIMALS);

    // Filling order
    const txHash = await zeroEx.exchange.fillOrderAsync(
        signedOrder,
        fillTakerTokenAmount,
        shouldThrowOnInsufficientBalanceOrAllowance,
        takerAddress,
    );

    // Transaction receipt
    const txReceipt = await zeroEx.awaitTransactionMinedAsync(txHash);
    console.log('FillOrder transaction receipt: ', txReceipt);
};

mainAsync().catch(console.error);

**Comment by fabioberger** [comment]
@ksfz2011 The issue is that you are sending the signing requests to Infura, and it cannot sign things on your behalf. 

Instead, you need to bifurcate account requests from network requests using a `web3-provider-engine` setup that includes a signer subprovider. 

Please see:
- https://0xproject.com/wiki#Web3-Provider-Explained
- https://0xproject.com/wiki#Web3-Provider-Examples

If you want to sign your orders with a specific privateKey or mnemonic, you can do something similar to our Test Faucet (https://github.com/0xProject/0x-monorepo/blob/v2-prototype/packages/testnet-faucets/src/ts/handler.ts#L47).

Does this answer your question?

**Comment by LogvinovLeon** [comment]
Closing for housekeeping reasons. Feel free to reopen if you have any additional questions.
