### ISSUE TITLE
[Contract] shouldThrowOnInsufficientBalanceOrAllowance set to false, when use WETH to buy DGX, but eth_estimateGas failed

### ISSUE THREAD

**Issue by Xaber20110202** [0xProject/0x-monorepo#645]
## Expected Behavior

`eth_estimateGas` response a appropriate value. (Maybe it could not send transaction correct too. I didn't test send Tx with `shouldThrowOnInsufficientBalanceOrAllowance` false.)
## Current Behavior

There is the order
```
const signedOrder = {
  exchangeContractAddress: '0x12459c951127e0c374ff9105dda097662a027093',
  maker: '0x8cccfa7b9ec9076b76041940d7835bc0a4488c6e',
  taker: '0x0000000000000000000000000000000000000000',
  makerTokenAddress: '0x4f3afec4e5a3f2a6a1a411def7d7dfe50ee057bf',
  takerTokenAddress: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
  feeRecipient: '0x6f7ae872e995f98fcd2a7d3ba17b7ddfb884305f',
  makerTokenAmount: '10000000',
  takerTokenAmount: '2354410000000000',
  makerFee: '0',
  takerFee: '0',
  expirationUnixTimestampSec: '1559282656',
  salt: '40765824492753417000000000000000000000000000000000000000000000000000000000000',
  ecSignature: {
    v: 27,
    r: '0xf985ce60d027277516525b35afd41ac401ecfb3ead4ce0cc8eece76d12b5f3a8',
    s: '0x1b0f91a3a398c32c1ffa3da4aac898b064022cbad7141c567b697087ab1a79af',
  },
}
```

When I want to fill this order, and set `shouldThrowOnInsufficientBalanceOrAllowance` to false, that 
`eth_estimateGas` will got error.

The params is
```
{
    "jsonrpc": "2.0",
    "id": 96,
    "method": "eth_estimateGas",
    "params": [
        {
            "from": "0xe269e891a2ec8585a378882ffa531141205e92e9",
            "to": "0x12459c951127e0c374ff9105dda097662a027093",
            "value": "0x0",
            "data": "0xbc61394a0000000000000000000000008cccfa7b9ec9076b76041940d7835bc0a4488c6e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000004f3afec4e5a3f2a6a1a411def7d7dfe50ee057bf000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000006f7ae872e995f98fcd2a7d3ba17b7ddfb884305f000000000000000000000000000000000000000000000000000000000098968000000000000000000000000000000000000000000000000000085d52cbb4a40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005cf0c3e05a20a39576b1b425eef86a8dc2a52315506dcc957536f6c190000000000000000000000000000000000000000000000000000000000000000000d621e12baa000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001bf985ce60d027277516525b35afd41ac401ecfb3ead4ce0cc8eece76d12b5f3a81b0f91a3a398c32c1ffa3da4aac898b064022cbad7141c567b697087ab1a79af"
        }
    ]
}
```

The response is (using https://mainnet.infura.io)
```
{
    "jsonrpc": "2.0",
    "id": 96,
    "error": {
        "code": -32000,
        "message": "gas required exceeds allowance or always failing transaction"
    }
}
```

Or (Using other web3 node)
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32015,
        "message": "Transaction execution error.",
        "data": "Internal(\"Requires higher than upper limit of 80078010\")"
    },
    "id": 96
}
```

But if I set `shouldThrowOnInsufficientBalanceOrAllowance` to true, it response correct.

The params is
```
{
    "jsonrpc": "2.0",
    "id": 96,
    "method": "eth_estimateGas",
    "params": [
        {
            "from": "0xe269e891a2ec8585a378882ffa531141205e92e9",
            "to": "0x12459c951127e0c374ff9105dda097662a027093",
            "value": "0x0",
            "data": "0xbc61394a0000000000000000000000008cccfa7b9ec9076b76041940d7835bc0a4488c6e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000004f3afec4e5a3f2a6a1a411def7d7dfe50ee057bf000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000006f7ae872e995f98fcd2a7d3ba17b7ddfb884305f000000000000000000000000000000000000000000000000000000000098968000000000000000000000000000000000000000000000000000085d52cbb4a40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005cf0c3e05a20a39576b1b425eef86a8dc2a52315506dcc957536f6c190000000000000000000000000000000000000000000000000000000000000000000d621e12baa000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001bf985ce60d027277516525b35afd41ac401ecfb3ead4ce0cc8eece76d12b5f3a81b0f91a3a398c32c1ffa3da4aac898b064022cbad7141c567b697087ab1a79af"
        }
    ]
}
```

The reponse is 
```
{
    "jsonrpc": "2.0",
    "id": 96,
    "result": "0x4fbc8"
}
```

## Possible Solution

And I saw some 0x contract code, that is
```
if (!shouldThrowOnInsufficientBalanceOrAllowance && !isTransferable(order, filledTakerTokenAmount)) {
            LogError(uint8(Errors.INSUFFICIENT_BALANCE_OR_ALLOWANCE), order.orderHash);
            return 0;
        }
```

You called `isTransferable`, and called `getBalance`, `getAllowance`, `getPartialAmount` within `isTransferable`. Maybe there is a compatibility problem with DGX token contract.

## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.25.0  |
| `Exchange Contract` | v1      |

| Network |
| ------- |
| mainnet    |

**Comment by tantao9323** [comment]
I have the similar problem. When we send a transcation on rinkeby, it always throw error ''gas required exceeds allowance or always failing transaction'' whether `shouldThrowOnInsufficientBalanceOrAllowance` is `true` or `false`. But it doesn't have this problem in your 0x-starter-project's testnet.

**Comment by fabioberger** [comment]
Please make sure you have properly set allowances from the two transacting account to the 0x proxy. Also ensure that both parties have sufficient funds to fill the order. 

Since the gas estimation step is failing, this usually means the contract is throwing at some point. Since setting `shouldThrowOnInsufficientBalanceOrAllowance` to true is working, this makes me believe that either the balance or allowance is insufficient to fill the order. Setting this to `false` means that no prior balance/allowance checks are done, and upon attempting the transfer, it throws.

**Comment by tantao9323** [comment]
I think I have properly set allowances, because I use `eth_sendtransaction` to `approve` and `transfer` to each other, it works well.

**Comment by Xaber20110202** [comment]
@fabioberger  Hi, you can check the order above. I use address `0xfba2ff8436171ddd3653cd2ca1c5595046144d7f` with `shouldThrowOnInsufficientBalanceOrAllowance = true` to fill the order, it filled successed. You can see the transaction https://etherscan.io/tx/0x18984aaabf8acc62a205c391c96fb5ac141ea04d0755ee4da9f0dd15192d29ae.

But if I set `shouldThrowOnInsufficientBalanceOrAllowance` to `false`, `eth_estimateGas` failed just like the error above, so that I not tried to fill.

**Comment by Xaber20110202** [comment]
@fabioberger 

I think maybe DGX contract address has some different features, https://gist.github.com/mrenoon/2582fba7b4d457d80f7d37520aabbc08.

Because that I wanted to fill 0.001 DGX, but only got 0.0009987, and another 0.0000013 was sent to `0x00a55973720245819ec59c716b7537dac5ed4617`

**Comment by fabioberger** [comment]
@Xaber20110202 one thing that sticks out to me is that it only has 8 decimal places so you are much more likely to hit a rounding error issue. Can you try plugging those numbers into https://0xproject.com/docs/0x.js#exchange-isRoundingErrorAsync?

**Comment by Xaber20110202** [comment]
Thanks for your apply, I tried, and the result is that.

```
const res = await zeroEx.exchange.isRoundingErrorAsync(
    toBN(235441000000000),
    toBN(2354410000000000),
    toBN(10000000),
)

// res is false
```

I think its not this problem, you can see this transaction https://etherscan.io/tx/0x18984aaabf8acc62a205c391c96fb5ac141ea04d0755ee4da9f0dd15192d29ae, I set `shouldThrowOnInsufficientBalanceOrAllowance` to true, the order filled successed.

And the order above still can fill, you can try to fill too.
```
const signedOrder = {
  exchangeContractAddress: '0x12459c951127e0c374ff9105dda097662a027093',
  maker: '0x8cccfa7b9ec9076b76041940d7835bc0a4488c6e',
  taker: '0x0000000000000000000000000000000000000000',
  makerTokenAddress: '0x4f3afec4e5a3f2a6a1a411def7d7dfe50ee057bf',
  takerTokenAddress: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
  feeRecipient: '0x6f7ae872e995f98fcd2a7d3ba17b7ddfb884305f',
  makerTokenAmount: '10000000',
  takerTokenAmount: '2354410000000000',
  makerFee: '0',
  takerFee: '0',
  expirationUnixTimestampSec: '1559282656',
  salt: '40765824492753417000000000000000000000000000000000000000000000000000000000000',
  ecSignature: {
    v: 27,
    r: '0xf985ce60d027277516525b35afd41ac401ecfb3ead4ce0cc8eece76d12b5f3a8',
    s: '0x1b0f91a3a398c32c1ffa3da4aac898b064022cbad7141c567b697087ab1a79af',
  },
}
```

**Comment by dekz** [comment]
It looks like DGX balanceOf and allowance functions query another contract. Given our stipend of 4999 gas this may not be enough gas to query multiple contracts to retrieve this information on-chain.

As you've found, by setting `shouldThrowOnInsufficientBalanceOrAllowance` to `true` this is skipped.

**Comment by fabioberger** [comment]
This was addressed in 0x protocol V2.
