### ISSUE TITLE
Web3Wrapper.getNetworkIdAsync results in error "Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by koirikivi** [0xProject/0x-monorepo#654]
## Expected Behavior

I have code like this:

```
import { Web3Wrapper } from '@0xproject/web3-wrapper';
const web3Wrapper = new Web3Wrapper(window.web3.currentProvider);
we3Wrapper.getNetworkIdAsync().then(console.log);
```

I would expect it to log the network id (1).

## Current Behavior

Instead, I get the following error in the javascript console:

```
MetaMask - RPC Error: TypeError: Cannot read property '0' of undefined
```

## Possible Solution

Since I get the error also with this call:

```web3Wrapper._sendRawPayloadAsync({ method: 'net_version' });```

But not with this:

```web3Wrapper._sendRawPayloadAsync({ method: 'net_version', params: [] });```

I suspect this is because the code here doesn't set the `params` key of the `payload` to an empty array (`[]`):

https://github.com/0xProject/0x-monorepo/blob/b8a267370d6538a6460625e283d7b1873066758a/packages/web3-wrapper/src/web3_wrapper.ts#L149-L153

And this code doesn't enforce it either:

https://github.com/0xProject/0x-monorepo/blob/b8a267370d6538a6460625e283d7b1873066758a/packages/web3-wrapper/src/web3_wrapper.ts#L406-L411

So I would recommend always setting `params` in `_sendRawPayloadAsync`.

If you look at the implementation of `web3.version.network` (or other things that use the `RequestManager` construct), it always calls `Jsonrpc.toPayload` which sets the `params` to `[]` if they are not explicitly given. It also sets other required jsonrpc stuff.

https://github.com/ethereum/web3.js/blob/v0.20.6/lib/web3/requestmanager.js#L79-L80

https://github.com/ethereum/web3.js/blob/v0.20.6/lib/web3/jsonrpc.js#L37-L50

## Steps to Reproduce (for bugs)

See above.

## Context

I can't get the network id using the web3 wrapper

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0xproject/web3-wrapper` | 0.6.4  |
| `MetaMask` | 4.7.2      |

| Network |
| ------- |
| mainnet    |

**Comment by LogvinovLeon** [comment]
This is the same issue as https://github.com/0xProject/0x-monorepo/issues/646
We've already fixed that here for id https://github.com/0xProject/0x-monorepo/commit/fd9b3e0dcfcbfb15bdadd4c97d05e93a50b2a434
I'll add a fix for params and publish. Thanks for reporting.

**Comment by LogvinovLeon** [comment]
Should be fixed with the @0xproject/web3-wrapper@0.7.0 release.

**Comment by koirikivi** [comment]
Wow, quick work. Thanks!

**Comment by fabioberger** [comment]
Thanks for the bug report @koirikivi! Really appreciate the help :)
