### ISSUE TITLE
awaitTransactionMinedAsync has no response

### ISSUE THREAD

**Issue by tantao9323** [0xProject/0x-monorepo#663]
Is it neccessary using `awaitTransactionMinedAsync` to check the result after `setUnlimitedProxyAllowanceAsync`? But `awaitTransactionMinedAsync` has no response for a long time. And I use the `setUnlimitedProxyAllowanceAsync` 's response to check the transaction on etherscan.io,  it's successful. By the way, I use the rinkeby testnet. Is there ant wrong? Thank you.

**Comment by fabioberger** [comment]
@tantao9323 what backing node are you using? It's possible that Etherscan's node receives the tx before your backing node. All `awaitTransactionMinedAsync` does under-the-hood is poll `web3.eth.getTransactionReceipt` on an interval until to returns the transactionReceipt.

**Comment by tantao9323** [comment]
@fabioberger Thanks for your reply, I use geth to init a local rinkeby node, I will try  more times.

**Comment by tantao9323** [comment]
@fabioberger It seems that I only need to `setUnlimitedProxyAllowanceAsync`  once for the same token and address?

**Comment by fabioberger** [comment]
Yes, that is correct.

**Comment by LogvinovLeon** [comment]
Is this resolved? Can I close it? @tantao9323

**Comment by tantao9323** [comment]
@LogvinovLeon Thank you, it resolved.
