### ISSUE TITLE
Uncaught (in promise) TypeError: value.toLowerCase is not a function     at TokenRegistryContract../node_modules/@0xproject/base-contract/lib/src/index.js.BaseContract._lowercaseAddress

### ISSUE THREAD

**Issue by rhrahul** [0xProject/0x-monorepo#710]
Hey, I am using this method.
`await zeroEx.tokenRegistry.getTokensAsync()`

## Expected Behavior

I think it should return all tokens, Although I am not sure.

## Current Behavior

It's throwing error, 
![0x-1](https://user-images.githubusercontent.com/35340981/41488260-5a3aa804-7109-11e8-8020-55f1e6f50862.png)

## Context

I wanted to get all tokens registered with contract.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.25.0  |
| `Exchange Contract` | v1      |

| Network |
| ------- |
| kovan    |

**Comment by rhrahul** [comment]
Any suggestions ??

**Comment by LogvinovLeon** [comment]
Could you check with the latest version of 0x.js. I've just tried to repro and it works for me.

**Comment by LogvinovLeon** [comment]
Please reopen if it's still present in the last version.

**Comment by rhrahul** [comment]
Ok, thanks for support.
It did work :)

One more thing,
How can we add custom tokens ?
Can you suggest me method for that ?

Thanks again

**Comment by fabioberger** [comment]
If you mean to the TokenRegistry, only 0x can do this until we deploy the TCR (token curated registry). We are currently in the process of adding many more tokens to the registry.
