### ISSUE TITLE
DAI contract in tokenRegistry

### ISSUE THREAD

**Issue by leoplct** [0xProject/0x-monorepo#715]
Why I didn't found the DAI token in the Token Registry? I am use Paradex was using it.

`zeroEx.tokenRegistry.getTokensAsync().then(tokens` => console.log(tokens))

## Expected Behavior

DAI contract address into the list

## Current Behavior

{address: "0xe41d2489571d322189246dafa5ebde1f4699f498", name: "0x Protocol Token", symbol: "ZRX", decimals: 18}
{address: "0x4156d3342d5c385a87d264f90653733592000581", name: "Salt", symbol: "SALT", decimals: 8}

{address: "0xe94327d07fc17907b4db788e5adf2ed424addff6", name: "Augur Reputation Token", symbol: "REP", decimals: 18}
3
:
{address: "0xe0b7927c4af23765cb51314a0e0521a9645f0e2a", name: "Digix DAO Token", symbol: "DGD", decimals: 9}
4
:
{address: "0xfa05a73ffe78ef8f1a739473e462c54bae6567d9", name: "Lunyr", symbol: "LUN", decimals: 18}
5
:
{address: "0xc66ea802717bfb9833400264dd12c2bceaa34a6d", name: "MakerDAO", symbol: "MKR", decimals: 18}
6
:
{address: "0xbeb9ef514a379b997e0798fdcc901ee474b6d9a1", name: "Melon Token", symbol: "MLN", decimals: 18}
7
:
{address: "0x9a642d6b3368ddc662ca244badf32cda716005bc", name: "Qtum", symbol: "QTUM", decimals: 18}
8
:
{address: "0xd26114cd6ee289accf82350c8d8487fedb8a0c07", name: "OmiseGO", symbol: "OMG", decimals: 18}
9
:
{address: "0xb97048628db6b661d4c2aa833e95dbe1a905b280", name: "TenXPay", symbol: "PAY", decimals: 18}
10
:
{address: "0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0", name: "Eos", symbol: "EOS", decimals: 18}
11
:
{address: "0x888666ca69e0f178ded6d75b5726cee99a87d698", name: "Iconomi", symbol: "ICN", decimals: 18}
12
:
{address: "0x744d70fdbe2ba4cf95131626614a1763df805b9e", name: "StatusNetwork", symbol: "SNT", decimals: 18}
13
:
{address: "0x6810e776880c02933d47db1b9fc05908e5386b96", name: "Gnosis", symbol: "GNO", decimals: 18}
14
:
{address: "0x0d8775f648430679a709e98d2b0cb6250d2887ef", name: "Basic Attention Token", symbol: "BAT", decimals: 18}
15
:
{address: "0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac", name: "Storj", symbol: "STORJ", decimals: 8}
16
:
{address: "0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c", name: "Bancor", symbol: "BNT", decimals: 18}
17
:
{address: "0x960b236a07cf122663c4303350609a66a7b288c0", name: "Aragon", symbol: "ANT", decimals: 18}
18
:
{address: "0x0abdace70d3790235af448c88547603b945604ea", name: "district0x", symbol: "DNT", decimals: 18}
19
:
{address: "0xaec2e87e0a235266d9c5adc9deb4b2e29b54d009", name: "SingularDTV", symbol: "SNGLS", decimals: 0}
20
:
{address: "0x419d0d8bdd9af5e606ae2232ed285aff190e711b", name: "FunFair", symbol: "FUN", decimals: 8}
21
:
{address: "0xaf30d2a7e90d7dc361c8c4585e9bb7d2f6f15bc7", name: "FirstBlood", symbol: "1ST", decimals: 18}
22
:
{address: "0x08711d3b02c8758f2fb3ab4e80228418a7f8e39c", name: "Edgeless", symbol: "EDG", decimals: 0}
23
:
{address: "0x5af2be193a6abca9c8817001f45744777db30756", name: "Bitquence", symbol: "BQX", decimals: 8}
24
:
{address: "0x607f4c5bb672230e8672085532f7e901544a7375", name: "iExec", symbol: "RLC", decimals: 9}
25
:
{address: "0x667088b212ce3d06a1b553a7221e1fd19000d9af", name: "Wings", symbol: "WINGS", decimals: 18}
26
:
{address: "0x41e5560054824ea6b0732e656e3ad64e20e94e45", name: "Civic", symbol: "CVC", decimals: 8}
27
:
{address: "0xb63b606ac810a52cca15e44bb630fd42d8d1d83d", name: "Monaco", symbol: "MCO", decimals: 8}
28
:
{address: "0xf433089366899d83a9f26a773d59ec7ecf30355e", name: "Metal", symbol: "MTL", decimals: 8}
29
:
{address: "0x12fef5e57bf45873cd9b62e9dbd7bfb99e32d73e", name: "Cofoundit", symbol: "CFI", decimals: 18}
30
:
{address: "0xaaaf91d9b90df800df4f55c205fd6989c977e73a", name: "Monolith TKN", symbol: "TKN", decimals: 8}
31
:
{address: "0xe7775a6e9bcf904eb39da2b68c5efb4f9360e08c", name: "Token-as-a-Service", symbol: "TAAS", decimals: 6}
32
:
{address: "0x2e071d2966aa7d8decb1005885ba1977d6038a65", name: "DICE", symbol: "ROL", decimals: 16}
33
:
{address: "0xcb94be6f13a1182e4a4b6140cb7bf2025d28e41b", name: "Trustcoin", symbol: "TRST", decimals: 6}
34
:
{address: "0x1776e1f26f98b1a5df9cd347953a26dd3cb46671", name: "Numeraire", symbol: "NMR", decimals: 18}
35
:
{address: "0x7c5a0ce9267ed19b22f8cae653f198e3e8daf098", name: "Santiment Network Token", symbol: "SAN", decimals: 18}
36
:
{address: "0xdd974d5c2e2928dea5f71b9825b8b646686bd200", name: "Kyber Network Crystal", symbol: "KNC", decimals: 18}
37
:
{address: "0x01afc37f4f85babc47c0e2d0eababc7fb49793c8", name: "Wrapped Golem Network Token", symbol: "WGNT", decimals: 18}
38
:
{address: "0xd0d6d6c5fe4a677d343cc433536bb717bae167dd", name: "adToken", symbol: "ADT", decimals: 9}
39
:
{address: "0xab16e0d25c06cb376259cc18c1de4aca57605589", name: "FinallyUsableCryptoKarma", symbol: "FUCK", decimals: 4}
40
:
{address: "0x701c244b988a513c945973defa05de933b23fe1d", name: "openANX", symbol: "OAX", decimals: 18}
41
:
{address: "0x514910771af9ca656af840dff83e8264ecf986ca", name: "ChainLink", symbol: "LINK", decimals: 18}
42
:
{address: "0x8f8221afbb33998d8584a2b05749ba73c37a938a", name: "Request Network", symbol: "REQ", decimals: 18}
43
:
{address: "0x27054b13b1b798b345b591a4d22e6562d47ea75a", name: "AirSwap", symbol: "AST", decimals: 4}
44
:
{address: "0xf0ee6b27b759c9893ce4f094b49ad28fd15a23e4", name: "Enigma", symbol: "ENG", decimals: 8}
45
:
{address: "0x818fc6c2ec5986bc6e2cbf00939d90556ab12ce5", name: "Kin", symbol: "KIN", decimals: 18}
46
:
{address: "0x27dce1ec4d3f72c3e457cc50354f1f975ddef488", name: "AirToken", symbol: "AIR", decimals: 8}
47
:
{address: "0x12480e24eb5bec1a9d4369cab6a80cad3c0a377a", name: "Substratum", symbol: "SUB", decimals: 2}
48
:
{address: "0xb7cb1c96db6b22b0d3d9536e0108d062bd488f74", name: "Walton", symbol: "WTC", decimals: 18}
49
:
{address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2", name: "Wrapped Ether", symbol: "WETH", decimals: 18}
50
:
{address: "0x42d6622dece394b54999fbd73d108123806f6a18", name: "SpankChain", symbol: "SPANK", decimals: 18}

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.38.3  |
| `Exchange Contract` | v1      |

| Network |
| ------- |
| NAME   Mainnet |

**Comment by LogvinovLeon** [comment]
Token registry contract is deprecated. We can't keep up to date with the growing number of tokens. While I agree that DAI one is extremely important - it was deployed after the last update to the token registry and I doubt we plan another update ever.

**Comment by BMillman19** [comment]
@leoplct it is actually in there now
