### ISSUE TITLE
How to integrate 0x.js with Ruby on Rails?

### ISSUE THREAD

**Issue by wenfengliu322** [0xProject/0x-monorepo#719]
I want to integrate this library with my ruby on rails server.
How can I integrate this with Ruby on Rails?
Thank you in advance.

**Comment by LogvinovLeon** [comment]
I don't think you can. You'll either need to write some glue JS/TS call into it from your Ruby app, or write the parts of 0x.js you need in Ruby. The second one is probably easier. You already have a web3 library in ruby, so you can call the contracts directly. The thing 0x.js adds on top of that is a bunch of utility methods and validations.

**Comment by wenfengliu322** [comment]
I tried to build UMD release and got bundle. I integrated that with Ruby on Rails.
But it says that "ZeroEX is not a constructor" in following line.
`const zeroEx = new ZeroEX(provider, config);`
How can I solve this?

**Comment by LogvinovLeon** [comment]
Depends on your import.
If you do it like that:
`import { ZeroEx } from '0x.js';`
then it should work. Just use the lower-case letter x at the end. ZeroEx.
If you do it like that:
`const ZeroEx = require('0x.js');`
that you should actually do:
`const ZeroEx = require('0x.js').ZeroEx;`

The ZeroEx library exports an object that has a field ZeroEx which is a constructor

**Comment by wenfengliu322** [comment]
I think that I don't need require().
My folder structure is same as following.
![library structure](https://user-images.githubusercontent.com/33848298/41588805-f252ed6a-73dc-11e8-9e77-d713d89a0b4a.png)

Also, I have integrated this library in application.js file like this.
![lib_integration](https://user-images.githubusercontent.com/33848298/41588902-3b0933ac-73dd-11e8-8842-2e55f81d6c8c.png)

My new js file is 0x-trading.js file.
![new_jsfile](https://user-images.githubusercontent.com/33848298/41588983-7b66d8b4-73dd-11e8-843c-df03f56d6600.png)

Here is my 0x-trading.js file code.
const TESTRPC_NETWORK_ID = 50;

// Provider pointing to local TestRPC on default port 8545
const provider = new Web3.providers.HttpProvider('http://localhost:8545');

// Instantiate 0x.js instance
const configs = {
    networkId: TESTRPC_NETWORK_ID,
};

const zeroEx = new ZeroEx(provider, configs);

// Number of decimals to use (for ETH and ZRX)
const DECIMALS = 18;

const mainAsync = async () => {
    // Addresses
    const WETH_ADDRESS = zeroEx.etherToken.getContractAddressIfExists(); // The wrapped ETH token contract
    const ZRX_ADDRESS = zeroEx.exchange.getZRXTokenAddress(); // The ZRX token contract
    // The Exchange.sol address (0x exchange smart contract)
    const EXCHANGE_ADDRESS = zeroEx.exchange.getContractAddress();

    // Getting list of accounts
    const accounts = await zeroEx.getAvailableAddressesAsync();
    console.log('accounts: ', accounts);

    // Set our addresses
    const [makerAddress, takerAddress] = accounts;

    // Unlimited allowances to 0x proxy contract for maker and taker
    const setMakerAllowTxHash = await zeroEx.token.setUnlimitedProxyAllowanceAsync(ZRX_ADDRESS, makerAddress);
    await zeroEx.awaitTransactionMinedAsync(setMakerAllowTxHash);

    const setTakerAllowTxHash = await zeroEx.token.setUnlimitedProxyAllowanceAsync(WETH_ADDRESS, takerAddress);
    await zeroEx.awaitTransactionMinedAsync(setTakerAllowTxHash);
    console.log('Taker allowance mined...');

    // Deposit WETH
    const ethAmount = new BigNumber(1);
    const ethToConvert = ZeroEx.toBaseUnitAmount(ethAmount, DECIMALS); // Number of ETH to convert to WETH

    const convertEthTxHash = await zeroEx.etherToken.depositAsync(WETH_ADDRESS, ethToConvert, takerAddress);
    await zeroEx.awaitTransactionMinedAsync(convertEthTxHash);
    console.log(`${ethAmount} ETH -> WETH conversion mined...`);

    // Generate order
    const order = {
        maker: makerAddress,
        taker: ZeroEx.NULL_ADDRESS,
        feeRecipient: ZeroEx.NULL_ADDRESS,
        makerTokenAddress: ZRX_ADDRESS,
        takerTokenAddress: WETH_ADDRESS,
        exchangeContractAddress: EXCHANGE_ADDRESS,
        salt: ZeroEx.generatePseudoRandomSalt(),
        makerFee: new BigNumber(0),
        takerFee: new BigNumber(0),
        makerTokenAmount: ZeroEx.toBaseUnitAmount(new BigNumber(0.2), DECIMALS), // Base 18 decimals
        takerTokenAmount: ZeroEx.toBaseUnitAmount(new BigNumber(0.3), DECIMALS), // Base 18 decimals
        expirationUnixTimestampSec: new BigNumber(Date.now() + 3600000), // Valid for up to an hour
    };

    // Create orderHash
    const orderHash = ZeroEx.getOrderHashHex(order);

    // Signing orderHash -> ecSignature
    const shouldAddPersonalMessagePrefix = false;
    const ecSignature = await zeroEx.signOrderHashAsync(orderHash, makerAddress, shouldAddPersonalMessagePrefix);

    // Appending signature to order
    const signedOrder = {
        ...order,
        ecSignature,
    };

    // Verify that order is fillable
    await zeroEx.exchange.validateOrderFillableOrThrowAsync(signedOrder);

    // Try to fill order
    const shouldThrowOnInsufficientBalanceOrAllowance = true;
    const fillTakerTokenAmount = ZeroEx.toBaseUnitAmount(new BigNumber(0.1), DECIMALS);

    // Filling order
    const txHash = await zeroEx.exchange.fillOrderAsync(
        signedOrder,
        fillTakerTokenAmount,
        shouldThrowOnInsufficientBalanceOrAllowance,
        takerAddress,
    );

    // Transaction receipt
    const txReceipt = await zeroEx.awaitTransactionMinedAsync(txHash);
    console.log('FillOrder transaction receipt: ', txReceipt);
};

mainAsync().catch(console.error);

This code is throwing "ZeroEx is not a constructor" as I wrote above.
In browser, 0x library index file is loaded.

**Comment by LogvinovLeon** [comment]
can you try using `ZeroEx.ZeroEx`?

**Comment by wenfengliu322** [comment]
If you are available in teamviewer, can you help me?

**Comment by wenfengliu322** [comment]
I will try ZeroEx.ZeroEx.

**Comment by LogvinovLeon** [comment]
https://appear.in/0x-debugging%20session

**Comment by LogvinovLeon** [comment]
Did it help?

**Comment by wenfengliu322** [comment]
Thank you.
You solved my issue perfectly.

**Comment by LogvinovLeon** [comment]
Happy hacking!

**Comment by noydarly** [comment]
Hi,  you there?
I want to connect subproviders package for ledger wallet in ruby project.
I build it with yarn,so I get subprovider lib and 0x bundle.
but I got error to using Subprovider class.
Can you help me?
thanks and best regards!
