### ISSUE TITLE
[Contract] Wrong WETH Contract Address returned

### ISSUE THREAD

**Issue by Vvkmnn** [0xProject/0x-monorepo#720]
The `zeroEx.etherToken.getContractAddressIfExists()` method returns the wrong address on Kovan.

## Expected Behavior
To wrap Ether for trading, the [documentation](https://github.com/0xProject/wiki/blob/master/tutorials/Create%2C-Validate%2C-Fill-Order.md) recommends calling the Wrapped Ether contract address via

```typescript
const WETH_ADDRESS = zeroEx.etherToken.getContractAddressIfExists() as string; // The wrapped ETH token contract
```

## Current Behavior

In our testing, we found that this is pointing to the [wrong contract address](https://kovan.etherscan.io/address/0x653e49e301e508a13237c0ddc98ae7d4cd2667a1) on the Kovan network (as provided by [Infura](https://infura.io/docs)). 

```typescript
const WETH_ADDRESS = zeroEx.etherToken.getContractAddressIfExists() as string; // => '0x653e49e301e508a13237c0ddc98ae7d4cd2667a1'
```

## Possible Solution

Luckily, the [public contract addresses](https://0xproject.com/wiki#Deployed-Addresses) allowed us to hardcode the right [contract address](https://kovan.etherscan.io/address/0xd0a1e359811322d97991e03f863a0c30c2cf029c) right into the function: `0xd0a1e359811322d97991e03f863a0c30c2cf029c`.

For example:

```typescript
/**
 * Converts Ethereum (ETH) to Wrapped Ethereum (WETH)
 * @param takerAddress
 * @param amount
 * Since ETH is not ERC-20 compliant, we need to convert a taker's eth amount to WETH (Wrapped ether).
 */
const depositEth = async (takerAddress: string, amount: number) => {
    // Wrap ETH to WETH
    const depositHash = zeroEx.etherToken.depositAsync('0xd0a1e359811322d97991e03f863a0c30c2cf029c',
                                                       ZeroEx.toBaseUnitAmount(new BigNumber(1), 18),
                                                       takerAddress)

    // Mine Transaction
    let mineTransaction = await zeroEx.awaitTransactionMinedAsync(depositHash)
}
```

## Steps to Reproduce (for bugs)

On the Kovan Network on Infura 

```typescript
// Web3
const provider = new Web3.providers.HttpProvider('https://kovan.infura.io')

// 0x
const zeroExConfig: ZeroExConfig = { networkId: 42 }
const zeroEx = new ZeroEx(provider, zeroExConfig)

// WETH Address
const WETH_ADDRESS = zeroEx.etherToken.getContractAddressIfExists() as string; // => '0x653e49e301e508a13237c0ddc98ae7d4cd2667a1'
```

## Context

We are building a Relay, and ran into this error while trying to make/take orders, since we need WETH, not ETH. Took us a while before we doubted your code (thanks for making such resilient functions. xD) 

## Your Environment

Package: 0x.js `0.38.3`
OS: macOS `10.13.5`

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.38.3  |

| Network |
| ------- |
| kovan    |

**Comment by LogvinovLeon** [comment]
Actually - kovan has multiple instance of WETH contracts deployed. They have the same code.
As you can see - the canonical one is exactly the same https://kovan.etherscan.io/address/0xd0a1e359811322d97991e03f863a0c30c2cf029c#code
So this shouldn't be any problem for you. You would just use the less popular one. But I agree that this should be fixed. It's an easy one, but we're currently working on redoing our publishing flow so might take a couple of days before we actually publish the fix.

**Comment by Vvkmnn** [comment]
Sure thing, thanks for the quick follow up. 

We could easily deposit, our issue was the contract never returning any WETH despite [multiple block confirmations](https://kovan.etherscan.io/tx/0x773e828c1c385d04d857f6824ef5f15e5b232172bd9baf0602f9e4c13a3c6b11), and we weren't sure what was happening. Luckily the other address worked a treat.

✌️
