### ISSUE TITLE
Upgrade to web3 1.0 once released

### ISSUE THREAD

**Issue by LogvinovLeon** [0xProject/0x-monorepo#74]

**Comment by goktugyil** [comment]
Whats this issue about?

**Comment by LogvinovLeon** [comment]
The issue is about us planning to upgrade to using web3@1.0 internally as soon as it's production quality. For now it's still in beta and there was no stable release. Also types are sometimes wrong and incomplete

**Comment by fabioberger** [comment]
It's looking like we might never do this. [Ethers.js](https://github.com/ethers-io/ethers.js/) is moving to TypeScript and supports ABIv2 and other features we want. In addition, we are using fewer and fewer Web3.js endpoints.

**Comment by crosstec** [comment]
...let's say you skip web3 altogether, will 0x still be able to use metamask (or its successor) as provider?

Thanks!

**Comment by fabioberger** [comment]
@crosstec we've removed web3 entirely from our codebase but still use the `Provider` interface defined by it. We are therefore still compliant with Metamask.

**Comment by crosstec** [comment]
thanks!
