### ISSUE TITLE
Using Web3ProviderEngine in Ruy on Rails

### ISSUE THREAD

**Issue by Edison4mobile** [0xProject/0x-monorepo#753]
I have trouble using 0x library in Ruby on Rails.
I will be happy if anyone guide me regarding this.
Thanks so much.

**Comment by LogvinovLeon** [comment]
Last time someone asked about that the solution was to use:
```typescript
const ZeroEx = require('0x.js').ZeroEx;
const zeroEx = new ZeroEx();
```
instead of:
```typescript
const ZeroEx = require('0x.js');
// this throws that ZeroEx is not a constructor.
const zeroEx = new ZeroEx();
```

https://github.com/0xProject/0x-monorepo/issues/719

Let me know if your issue is different. Also - more info will help.

**Comment by LogvinovLeon** [comment]
I assume it's solved because of no response in a week

**Comment by noydarly** [comment]
Hi, I integrate 0x js and web provider in ruby on rails.
But I can't integrate subproviders for ledger wallet.
Can you tell me about this in ruby on rails?
Best regards
