### ISSUE TITLE
Want to add new token and also need some guidance on creating relayer

### ISSUE THREAD

**Issue by rhrahul** [0xProject/0x-monorepo#779]
Hey, so I wanted to add new custom tokens, how can I do that ?
And also I need some guidance to create 0x relayer.
I've already read this one,
https://github.com/0xProject/standard-relayer-api
I need more details like how to handle everything on API side.

Thanks

## Current Behavior
Can't add custom token to contract.

## Possible Solution
Suggest me how can I add more tokens.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.25.0  |
| `Exchange Contract` | v1      |

| Network |
| ------- |
| kovan |

**Comment by rhrahul** [comment]
Hello,
Any suggestions please ??

**Comment by fabioberger** [comment]
@rhrahul please clarify what you mean by "add new custom token". Are you talking about 0x Portal?

The way you implement your API is completely up to you. The Standard Relayer API should tell you what interface traders are expecting.

**Comment by rhrahul** [comment]
Ok, Thanks 👍
