### ISSUE TITLE
[sol-cov] compiler optimizes away duplicate functions w/ different names

### ISSUE THREAD

**Issue by perissology** [0xProject/0x-monorepo#784]
## Expected Behavior

Correct code is marked as covered

## Current Behavior

The code coverage report may not be correct in the following case, due to the optimizer removing 1 function.

This is an extract of my implementation of an interface that I needed to implement.
```
    /// @notice Notifies the controller about a token transfer allowing the
    ///  controller to react if desired
    /// @param _from The origin of the transfer
    /// @param _to The destination of the transfer
    /// @param _amount The amount of the transfer
    /// @return False if the controller does not authorize the transfer
    function onTransfer(address _from, address _to, uint _amount) public returns(bool) {
        return true;
    }

    /// @notice Notifies the controller about an approval allowing the
    ///  controller to react if desired
    /// @param _owner The address that calls `approve()`
    /// @param _spender The spender in the `approve()` call
    /// @param _amount The amount in the `approve()` call
    /// @return False if the controller does not authorize the approval
    function onApprove(address _owner, address _spender, uint _amount) public returns(bool) {
        return true;
    }
```

The `onTransfer` and `onApprove` are essentially the same except for the name. When the optimizer is enabled, `onApprove` is optimized away and that function signature points to the code location of `onTransfer`.

Thus if I call `onApprove`, `onTransfer` is marked as covered.

## Possible Solution

I'm not sure if the optimizer puts any metadata in the bytecode when run. If so, we can emit a warning if the optimizer was enabled.

Could also detect this via the ast, marking the possible "duplicates", then when collecting traces we would need to check the function sig of a CALL to determine which function actually got covered.

**Comment by LogvinovLeon** [comment]
Hmm. Do I get it right that the function signature itself is marked as covered and just the line with `return true` isn't?
In that case, this doesn't seem like anything we can handle gracefully. It's the problem with the approach we've taken and our report is by some notion correct. The code generated by that line (empty code) was never executed. Actually - any statement about every line of empty code is correct ;)

I see that happening a lot later when contracts are required to implement some interface/callback.
For now - I'd prefer smth like `/* sol-cov covered next */` or `/* sol-cov ignore next */` proposed in one of your earlier PRs.

Solidity compiler does put some metadata at the end of bytecode marking the compiler version and settings. We might be able to parse that and emit a warning.

**Comment by fabioberger** [comment]
Closed due to inactivity.
