### ISSUE TITLE
Uncaught (in promise) Error: TOKEN_CONTRACT_DOES_NOT_EXIST

### ISSUE THREAD

**Issue by rhrahul** [0xProject/0x-monorepo#790]
Hi,
I am using 0x960b236a07cf122663c4303350609a66a7b288c0 contract
and it says TOKEN_CONTRACT_DOES_NOT_EXIST

## Expected Behavior
How can I other tokens in 0x, please suggest me, where to make changes.

## Current Behavior
can't use other tokens, and also can't connect with other token contract address.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.25.0  |
| `Exchange Contract` | v1      |

| Network |
| ------- |
| mainnet |

Please suggest me where to change ?
Do I have to add ABI and all that ?

Thanks

**Comment by LogvinovLeon** [comment]
Please make sure that the provider you're passing is connected to main net and you specify `networkId` as `1` in 0x.js config. You might be connected to a test network

**Comment by rhrahul** [comment]
Ok, thanks.
But what if I want to add more tokens ?
How to do that ?
If you can assist me , it would be great ?

**Comment by rhrahul** [comment]
Do I have to make my own tokenregistery contract and use that ?

**Comment by LogvinovLeon** [comment]
`TokenRegistry` is being deprecated. At the moment only us can add tokens to it and we don't add any additional tokens. At the same time - nothing stops you from operating on tokens not in token registry. You can create/fill/cancel orders with any token.

**Comment by rhrahul** [comment]
Ok, cool
Thanks for your quick response.
:)

**Comment by rhrahul** [comment]
So, I can use other token address and use it as token_pairs, right ??

**Comment by LogvinovLeon** [comment]
Yes. We just check that there is actually some code under this address. If you pass a private-key controlled user address in place of token address - it'll throw

**Comment by rhrahul** [comment]
Ok, sorry if I was not clear.
But I am trying to make new relayer same as radar relay, openrelay, etc..
so I was taking advice regarding that.

**Comment by LogvinovLeon** [comment]
I'll recommend taking a look at 0x starter project and tutorials:
https://0xproject.com/wiki#Create,-Validate,-Fill-Order
https://github.com/0xProject/0x-starter-project
Feel free to ask any more questions. Also - join our [rocket.chat](https://chat.0xproject.com/)
#dev channel there is a good place to ask your questions

**Comment by rhrahul** [comment]
Ok, thanks.
I already been through 0x starter project and tutorials :)

**Comment by rhrahul** [comment]
Hey, do you have any idea about this,
https://github.com/0xProject/standard-relayer-api/issues/27
