### ISSUE TITLE
TypeError: takerTokenAmount.eq is not a function

### ISSUE THREAD

**Issue by leoplct** [0xProject/0x-monorepo#798]
## Current Behavior

Uncaught (in promise) TypeError: takerTokenAmount.eq is not a function
    at Function.OrderValidationUtils._validateRemainingFillAmountNotZeroOrThrow (order_validation_utils.js:87)
    at OrderValidationUtils.eval (order_validation_utils.js:144)

## Steps to Reproduce (for bugs)

           const DECIMALS = 18;
            const zeroEx = this.get('zero').zeroEx
            const takerAddress = this.get('zero').my_address
            const shouldThrowOnInsufficientBalanceOrAllowance = false
            const fillTakerTokenAmount = this.get('zero').ZeroEx.toBaseUnitAmount(new BigNumber(0.1), DECIMALS)

            const txHash = await zeroEx.exchange.fillOrderAsync(
                order,
                fillTakerTokenAmount,
                shouldThrowOnInsufficientBalanceOrAllowance,
                takerAddress
            );
            console.log(txHash);

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.38.3  |
| `Exchange Contract` | v1      |

**Comment by LogvinovLeon** [comment]
Please check that the `fillTakerTokenAmount` you're passing is a proper `BigNumber` and has an `eq` method on it.

**Comment by fabioberger** [comment]
This is most likely happening because the order you are passing in has amounts as type `string` instead of type `BigNumber`.

**Comment by leoplct** [comment]
Ok but I defined it using the toBaseUnitAmiunt  method 

const fillTakerTokenAmount = this.get('zero').ZeroEx.toBaseUnitAmount(new BigNumber(0.1), DECIMALS)

**Comment by LogvinovLeon** [comment]
My bad. Misread the name. I think @fabioberger comment is actually the cause

**Comment by leoplct** [comment]
Thank you.
I tried to re-convert the `order` object saved on databased back to BigNumber, but now i get "INVALID SIGNATURE".


[            let fillOrder = {
            	ecSignature: order.get('ecSignature'),
            	exchangeContractAddress: order.get('exchangeContractAddress'),
            	expirationUnixTimestampSec: new BigNumber(order.get('expirationUnixTimestampSec')) ,
            	feeRecipient: order.get('feeRecipient'),
            	maker: order.get('maker'),
            	makerFee: new BigNumber(order.get('makerFee')),
            	makerTokenAddress: order.get('makerTokenAddress'),
            	makerTokenAmount: order.get('makerTokenAmount'),
            	salt: new BigNumber(order.get('salt')),
            	taker: order.get('taker'),
            	takerFee: new BigNumber(order.get('takerFee')),
            	takerTokenAddress: order.get('takerTokenAddress'),
            	takerTokenAmount: new BigNumber(order.get('taker')),
            }

const txHash = await zeroEx.exchange.fillOrderAsync(
                fillOrder,
                fillTakerTokenAmount,
                shouldThrowOnInsufficientBalanceOrAllowance,
                takerAddress
            );](url)

**INVALID SIGNATURE**

**Comment by fabioberger** [comment]
@leoplct can you make sure `ECSignature` looks like:

```
{
	r: string,
	s: string,
	v: number,
}
```
