### ISSUE TITLE
Intermittent failure of @0xproject/subproviders test

### ISSUE THREAD

**Issue by feuGeneA** [0xProject/0x-monorepo#809]
## Expected Behavior

@0xproject/subproviders test should consistently pass.

## Current Behavior

Test consistently fails on my machine with message:
```
  1) RedundantSubprovider
       succeeds when supplied at least one healthy endpoint:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
Full output at https://gist.github.com/feuGeneA/1b606ccfd44cb29c9d32a614d2ce8428

I tried adding a bunch of `console.log()` entries to try to understand what was going on, and interestingly at a certain point (a certain number of `console.log()`s), the test starts passing!  But then a re-run of the same code will fail again, like maybe the code path is getting cached.  Then if I add more `console.log()`s it will fail again, but then pass on re-run, and on and on.

It feels like my computer's too fast for it's own good.  :)  (Core i7-6820HQ, Quad Core 2.70GHz, 3.60GHz Turbo, 8MB cache; 32GB RAM, SSD-only)

It feels like the connection failure result (expected in this test) isn't coming back fast enough, and the code just marches on and doesn't recognize the failure.  (Speculating...)

A little extra info I gleaned: When the test does pass, the error is emitted from [here](https://github.com/MetaMask/provider-engine/blob/master/subproviders/rpc.js#L34), and caught [here](https://github.com/0xProject/0x-monorepo/blob/300c9f09b9ee129791a1f62881da0ee3c34ee0b5/packages/subproviders/src/subproviders/redundant_subprovider.ts#L26)

## Steps to Reproduce (for bugs)

Run the test on a fast computer?

## Context

This is a pretty big annoyance for me.  I want to be able to do clean test runs for everything in the monorepo in my local environment, but I'm continually having to hack an `--exclude @0xproject/subproviders` into the `test` script in my `0x-monorepo/package.json`.

## Your Environment

Core i7-6820HQ, Quad Core 2.70GHz, 3.60GHz Turbo, 8MB cache; 32GB RAM, SSD-only

$ uname -a
Linux precision5510 4.4.0-128-generic #154~14.04.1-Ubuntu SMP Fri May 25 14:58:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fabioberger** [comment]
Going off of the test that is failing, it seems to me that the solution here is to increase the Mocha timeout limit. 

The test that is failing looks like this:

```
...
const nonExistentSubprovider = new RpcSubprovider({
   rpcUrl: 'http://does-not-exist:3000',
});
const subproviders = [nonExistentSubprovider as Subprovider, ganacheSubprovider];
const redundantSubprovider = new RedundantSubprovider(subproviders);
provider.addProvider(redundantSubprovider);
provider.start();
...
provider.sendAsync(payload, callback);
```

The first request is attempted to a non-existent endpoint. How different machines attempt to make this connection, as well as the developers internet connectivity, could influence how long this request takes. E.g Things like the DNS lookup could take a variable amount of time.

I think the only sane thing to do is to increase the timeout limit for this mocha test.

This can be done as follows:

```
it('succeeds when supplied at least one healthy endpoint', function(done: DoneCallback) {
    // HACK: Since we are making an HTTP request to a non-existent endpoint, the network
    // latency of this request might vary depending on who runs it. To avoid intermittent failures
    // we increase the timeout for this test.
    const mochaTestTimeoutMs = 20000;
    this.timeout(mochaTestTimeoutMs);
});
```

Note the purposeful omission of arrow syntax use (necessary scoping so that we have access to `this.timeout()`). Not sure what the ideal timeout would be here.

**Comment by feuGeneA** [comment]
@fabioberger When I first saw the test fail due to a timeout, my first instinct was to increase the timeout as well.  I did at the time, and it didn't seem to change anything, so I plowed on with the investigation anyways.  Just now I tried with 10x the original timeout, and still got `Error: Timeout of 100000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`

But, I'm adjusting the timeout differently than you advised.  I'm adjusting the `--timeout` value in the `run_mocha_unit` script command in `subproviders/package.json`.  Does that not have the same effect as what you suggested?

Also, another clue:  When the test does pass on my machine (when I've just added more `console.log()` statements (see OP)), it completes quickly, even immediately, subjectively speaking.  There is no time spent waiting for that connection initiation to fail, certainly not enough to even come anywhere close to the timeout value.

**Comment by fabioberger** [comment]
Thanks for the detailed reply @feuGeneA. Another approach we can take is to stub the subprovider's `handleRequest` method and eliminate the network connection unknowns entirely. 

I've implemented the above. Can you try running this on your setup? https://github.com/0xProject/0x-monorepo/pull/818

**Comment by feuGeneA** [comment]
@fabioberger Test passes consistently for me with your that change in place.

**Comment by fabioberger** [comment]
Awesome! Will merge and close then!
