### ISSUE TITLE
Rendered wiki missing section headers in a few key places

### ISSUE THREAD

**Issue by feuGeneA** [0xProject/0x-monorepo#832]
## Expected Behavior
* When reading straight through the wiki (top to bottom), I expect to see section headings in-line, so that I realize when I'm transitioning from one section to another.
* When browsing titles in the menu, I expect to see section headings just like in the sidebar, so that I can differentiate between one section and another.

## Current Behavior
There are no section headings in either the main 

## Context
I was reading the wiki from top to bottom, and the thing that really confused me was when I got to the "Matching" article.  "Matching?" I thought, "that doesn't sound like a top-level heading, what are we talking about here?"  I guessed that it was delving into Relayer Strategies, but wasn't sure, so I decided to check the Table of Contents.  At the time I was on a mobile device, so there was no sidebar visible, so I checked the menu.  There too there was a lack of section headings!  So while reading on my mobile device I had no way to know what section I was in.  Later when I was back on my PC I confirmed my guess by looking at the sidebar.

## Your Environment

Chrome 67.0.3396.87 on Android 8.0.0.  Confirmed same behavior on Chrome 67.0.3396.87 (Official Build) (64-bit) on my Ubuntu desktop.

**Comment by fabioberger** [comment]
This is a known issue. Hope to fix after V2 refactors are done.

**Comment by fabioberger** [comment]
Fixed.
