### ISSUE TITLE
[SoHoAudit] Externally supplied variable salt can lead to lack of transaction hash uniqueness within methods hashZeroExTransaction and executeTransaction  in  MixinTransactions.sol#53,88

### ISSUE THREAD

**Issue by JonHaas** [0xProject/0x-monorepo#852]
As transactions within `MixinTransactions.sol` rely upon `salt` in order to ascertain a level of transaction hash uniqueness, allowing an individual to supply their own value of salt does not ensure this assertion of randomness is upheld. [While much debate](https://ethereum.stackexchange.com/questions/191/how-can-i-securely-generate-a-random-number-in-my-smart-contract) exists as to random number generation within Solidity and the constraints of the EVM, the minimization of user influence over randomness exists as a general best practice. 

While the [0x Project specification](https://github.com/0xProject/0x-protocol-specification/blob/9d623a8798f4310a6544e975a7f4f06d6e9564ae/v2/v2-specification.md#optimizing-salt) for denotes a potential strategy for generating the `salt` value (utilizing a timestamp), this value should not be provided by the user and should instead be generated within the context of the function.

**Comment by abandeali1** [comment]
If the salt is generated within the contracts, then the order or transaction cannot be signed in advance (since the hash isn't known). Realistically, it is also very easy to check if a hash is unique before signing it, at which point a user can simply adjust the salt accordingly.
