### ISSUE TITLE
[SoHoAudit] Combined taker fees exceeding MAX_INT will revert execution rather than successfully process MixinMatchOrders.sol#281-284:

### ISSUE THREAD

**Issue by JonHaas** [0xProject/0x-monorepo#853]
While unlikely to occur, if an order is to be fulfilled in which the properly owed taker fees paid out to a singular party exceed MAX_INT, the process will revert rather than establish a secondary methodology by which to pay relevant taker fees to the according address. 

Despite the likeliness of occurrence, this behavior should be noted and presented accordingly. Usage of `require` is suggested in order to provide justification as to why the transaction failed to complete.

**Comment by abandeali1** [comment]
This should actually never happen since the total supply of ZRX is only 10^27 :)
