### ISSUE TITLE
[SoHoAudit] Suggested usage of transfer in place of call.value() on line AssetProxyOwner.sol#91

### ISSUE THREAD

**Issue by JonHaas** [0xProject/0x-monorepo#854]
Usage of `transfer` is suggested due to [re-entrancy concerns](http://solidity.readthedocs.io/en/v0.4.21/security-considerations.html). While `addr.call.value(x)()` effectively works the same as `addr.transfer(x)`, it forwards all remaining gas and opens up the ability for the recipient to perform more expensive actions (and it only returns a failure code and does not automatically propagate the error). This might include calling back into the sending contract (re-entrancy) or other state changes. As transfer does not exist in Solidity version 0.4.10, upgrade of the contract version is _required_ for this change.

**Comment by abandeali1** [comment]
We do actually rely on sending data via `.call.value()` here, so it couldn't be completely replaced by `transfer`. The fact that `tx.executed` is set to `true` before the call also limits any potential reentrancy attacks (i.e you couldn't call the same tx twice).
