### ISSUE TITLE
How to get Account's Ether Balance ?

### ISSUE THREAD

**Issue by rhrahul** [0xProject/0x-monorepo#864]
Hey, so I wanted to know, how can we get Account's Ether Balance ?
I couldn't find that anywhere.

## Expected Behavior

Just want to know user's wallet Balance (Ether)

## Current Behavior

If I am missing something or I am not sure, But I can not find any method for getting user's Ether Balance in documentation.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.25.0  |
| `Exchange Contract` | v1      |

| Network |
| -------- |
| mainnet|

**Comment by BMillman19** [comment]
@rhrahul https://0xproject.com/docs/web3-wrapper#web3Wrapper-getBalanceInWeiAsync

**Comment by rhrahul** [comment]
Ok thanks.
I've tried it, Is there anything to convert in to ether ?
Like web3.eth.fromWei(amount, "ether");

**Comment by rhrahul** [comment]
Nevermind,
I've done it something like this,

```
ZeroEx.toUnitAmount(
      await web3Wrapper.getBalanceInWeiAsync(account),
      18
).toNumber(8);
```
