### ISSUE TITLE
zeroEx.signOrderHashAsync() giving INVALID_SIGNATURE Error

### ISSUE THREAD

**Issue by rhrahul** [0xProject/0x-monorepo#878]
## Problem Description

Hello, so I was using this function,
```
await zeroEx.signOrderHashAsync(
   orderHash, 
   makerAddress,
   false
);
```
and I am keep getting this Error,
`INVALID_SIGNATURE`

and it is not returning proper Signature.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.25.0  |
| `Exchange Contract` | v1      |

| Network |
| ------- |
| mainnet |

**Comment by rhrahul** [comment]
Any suggestions Please ?
And also How to check if allowance is set or not ?

**Comment by fabioberger** [comment]
@rhrahul did you try passing `true` as the last parameter?

**Comment by rhrahul** [comment]
Yes, I tried with true and it worked.
I am using metamask as provider.
so what is that true/false about ?

**Comment by fabioberger** [comment]
It's the `shouldAddPersonalMessagePrefix` param. [There is a description in the docs](https://0xproject.com/docs/0x.js#zeroEx-signOrderHashAsync).

**Comment by rhrahul** [comment]
Ok, Thanks !

**Comment by rhrahul** [comment]
Also one more question,
how can we check if allowance is set or not from relayer ?
