### ISSUE TITLE
[Portal] Adding support for WalletConnect

### ISSUE THREAD

**Issue by ricburton** [0xProject/0x-monorepo#890]
It would be great to make this happen when WalletConnect is stable. That should be soon.

@pedrouid & @dekz, you two should get on a call when you can 👍

**Comment by BMillman19** [comment]
<img width="626" alt="screen shot 2018-07-24 at 1 41 05 pm" src="https://user-images.githubusercontent.com/1141340/43119017-46a5414e-8f47-11e8-81ea-8da9da74afdc.png">

**Comment by LogvinovLeon** [comment]
@BMillman19 Do we still want to do that?

**Comment by pedrouid** [comment]
@BMillman19 let me know if would like me to help with the integration 👍 
you can also check out the Getting Started section on our README: https://github.com/WalletConnect/walletconnect-monorepo#walletconnect
