### ISSUE TITLE
FYI, ethers.js is releasing their TypeScript port soon (v4)

### ISSUE THREAD

**Issue by pkieltyka** [0xProject/0x-monorepo#900]
It's great to see that 0x v2 uses ethers.js, its such a great library to work with, very lean and well maintained.

Just a heads up, you might be interested to know that the author (Ricmoo) ported the entire library to TypeScript and will be releasing it as v4 of ethers, see https://github.com/ethers-io/ethers.js/pull/99#issuecomment-406077504 and the branch: https://github.com/ethers-io/ethers.js/tree/typescript

Also, it'd be great to see the web3-wrapper and other web3 clients also removed from 0x packages at some point (IMHO), as its a bloated dependency and much nicer to standardize on Ethers :) especially for other DEX writers building on 0x

thank you again for all the awesome work, keep it up and good luck

**Comment by pkieltyka** [comment]
@fabioberger ethers.js has pushed "4.0.0-beta.1" to npm, which is the TS port / version with native declaration files. 

Ah, and yes I know web3-wrapper is very lightweight, I meant "web3" + other stuff that is heavy that'd be wonderful to go away, and then web3-wrapper wouldn't need to exist

**Comment by dekz** [comment]
We have updated to `~4.0.4`
