### ISSUE TITLE
Standard Relayer API inconsistant with 0x-connect

### ISSUE THREAD

**Issue by PhABC** [0xProject/0x-monorepo#907]
## Context

In Standard Relayer API (SRA) for 0x V1 (not V0), endpoint for obtaining an pair of asset should be `/asset_pairs` according to the [v1.md](https://github.com/0xProject/standard-relayer-api/blob/update/v1/http/v1.md#get-v1asset_pairs) file, but the typescript [http_client.ts](https://github.com/0xProject/0x-monorepo/blob/a05b14e4d9659be1cc495ee33fd8962ce773f87f/packages/connect/src/http_client.ts#L80) file uses `/token_pairs` instead, which I believe is a relic of the V0 SRA. 

## Your Environment

`0x connect` commit : `855b6b1dc5597f360451232ff6dfc91beb3a9f50`
`HTTP REST API Specification V1`  commit : `74a348467e15898f6f83d97a613cb773f2c16249`

**Comment by BMillman19** [comment]
The most up to date version of connect is still using the v0 spec, we'll be updating it sometime within the next month or so. Check out https://github.com/0xProject/standard-relayer-api/pull/26 for the most up to date discussion on the spec
