### ISSUE TITLE
Disallow user to pass a string when a BigNumber is expected

### ISSUE THREAD

**Issue by LogvinovLeon** [0xProject/0x-monorepo#92]

**Comment by BMillman19** [comment]
Can we close this? Or do the asserts not take care of this?

**Comment by fabioberger** [comment]
@LogvinovLeon can we close?

**Comment by fabioberger** [comment]
This actually still an outstanding issue. If a user passes an order retrieved via the Standard Relayer API and passes it onwards to 0x.js without converting amounts to BigNumbers, 0x.js throws unhelpful error messages such as:

```
TypeError: takerTokenAmount.eq is not a function
```

Since `takerTokenAmount` is a string, not a BigNumber.

**Comment by BMillman19** [comment]
this is the root of the problem: https://github.com/0xProject/0x-monorepo/blob/development/packages/json-schemas/src/schema_validator.ts#L29

**Comment by fabioberger** [comment]
@BMillman19 yes, but I think we just need to add specific validation for BigNumber properties in objects. This way we can throw a more sensible error.

**Comment by Vilayhong** [comment]
Hi

**Comment by Vilayhong** [comment]
I can't solve this issue.
Can you tell me detail steps?
thanks

**Comment by LogvinovLeon** [comment]
You need to pass a `BigNumber` (not just a string) in places where `BigNumber` is expected.

**Comment by Vilayhong** [comment]
thanks for your kindly response.
I placed BigNumber in there.
but have some issue.
please help me

**Comment by Vilayhong** [comment]
this is my sample code.
// Number of decimals to use (for ETH and ZRX)
const DECIMALS = 18;

// Addresses
const WETH_ADDRESS = zeroEx.etherToken.getContractAddressIfExists() as string; // The wrapped ETH token contract
const ZRX_ADDRESS = zeroEx.exchange.getZRXTokenAddress(); // The ZRX token contract
// The Exchange.sol address (0x exchange smart contract)
const EXCHANGE_ADDRESS = zeroEx.exchange.getContractAddress();
const accounts = await zeroEx.getAvailableAddressesAsync();
console.log('accounts: ', accounts);
const [makerAddress, takerAddress] = accounts[0];

const ethAmount = new BigNumber(1);
const ethToConvert = ZeroEx.toBaseUnitAmount(ethAmount, DECIMALS); // Number of ETH to convert to WETH

const convertEthTxHash = await zeroEx.etherToken.depositAsync(WETH_ADDRESS, ethToConvert, takerAddress);
await zeroEx.awaitTransactionMinedAsync(convertEthTxHash);

// Generate order
const order = {
    maker: makerAddress,
    taker: ZeroEx.NULL_ADDRESS,
    feeRecipient: ZeroEx.NULL_ADDRESS,
    makerTokenAddress: ZRX_ADDRESS,
    takerTokenAddress: WETH_ADDRESS,
    exchangeContractAddress: EXCHANGE_ADDRESS,
    salt: ZeroEx.generatePseudoRandomSalt(),
    makerFee: new BigNumber(0),
    takerFee: new BigNumber(0),
    makerTokenAmount: ZeroEx.toBaseUnitAmount(new BigNumber(0.2), DECIMALS), // Base 18 decimals
    takerTokenAmount: ZeroEx.toBaseUnitAmount(new BigNumber(0.3), DECIMALS), // Base 18 decimals
    expirationUnixTimestampSec: new BigNumber(Date.now() + 3600000), // Valid for up to an hour
};

const orderHash = ZeroEx.getOrderHashHex(order);

// Signing orderHash -> ecSignature
const shouldAddPersonalMessagePrefix = false;
const ecSignature = await zeroEx.signOrderHashAsync(orderHash, makerAddress, shouldAddPersonalMessagePrefix);

// Append signature to order
const signedOrder = {
    ...order,
    ecSignature,
};

await zeroEx.exchange.validateOrderFillableOrThrowAsync(signedOrder);

const shouldThrowOnInsufficientBalanceOrAllowance = true;
const fillTakerTokenAmount = ZeroEx.toBaseUnitAmount(new BigNumber(0.1), DECIMALS);

const txHash = await zeroEx.exchange.fillOrderAsync(
    signedOrder,
    fillTakerTokenAmount,
    shouldThrowOnInsufficientBalanceOrAllowance,
    takerAddress,
);

const txReceipt = await zeroEx.awaitTransactionMinedAsync(txHash);
console.log('FillOrder transaction receipt: ', txReceipt);

**Comment by Vilayhong** [comment]
Until signedOrder, this is correct.
but in here await zeroEx.exchange.validateOrderFillableOrThrowAsync(signedOrder);
I got issue like this:
TypeError: takerTokenAmount.eq is not a function
    at Function.OrderValidationUtils._validateRemainingFillAmountNotZeroOrThrow (order_validation_utils.js:87)
    at OrderValidationUtils.<anonymous> (order_validation_utils.js:114)
    at step (order_validation_utils.js:32)
    at Object.next (order_validation_utils.js:13)
    at fulfilled (order_validation_utils.js:4)

**Comment by Vilayhong** [comment]
Could you tell me about this error?
thanks for your time.
best regards

**Comment by Vilayhong** [comment]
this is sample code from https://github.com/0xProject/wiki/blob/master/tutorials/Create%2C-Validate%2C-Fill-Order.md and my net work is Ropsten Test Network.
Can you give me correct sample code? :)

**Comment by fabioberger** [comment]
Thanks for the detailed information @Vilayhong, I have investigated and there seems to be a bug on our end. Will look into fixing this ASAP.

**Comment by fabioberger** [comment]
@Vilayhong there doesn't seem to be anything wrong with the script you pasted above. Can you print the following right before `await zeroEx.exchange.validateOrderFillableOrThrowAsync(signedOrder);`:

```
console.log('TypeOf takerTokenAmount', typeof signedOrder.takerTokenAmount);
```

**Comment by haidoan** [comment]
@Vilayhong make sure that signedOrder.takerTokenAmount is a big Number object.

**Comment by fabioberger** [comment]
@noydarly you should use the BigNumber from `@0xproject/utils`:

```
import { BigNumber } from '@0xproject/utils'; 
```

Or configure your BigNumber to avoid scientific notation: https://github.com/0xProject/0x-monorepo/blob/development/packages/utils/src/configured_bignumber.ts#L6
