### ISSUE TITLE
0x.js with Nethereum or C#

### ISSUE THREAD

**Issue by senzacionale** [0xProject/0x-monorepo#923]
Do you maybe have wrapper for c# or Nethereum? 

I would like to use your 0x.js library in .net. 

Thank you

**Comment by fabioberger** [comment]
@senzacionale we do not, however, you might be able to auto-generate the 0x contract wrappers using [ABI-gen](https://github.com/0xProject/0x-monorepo/tree/development/packages/abi-gen). Currently the templates are written to generate TypeScript wrappers, but you could write handlebar templates that generate .net wrappers.

Want to give that a try?

**Comment by senzacionale** [comment]
Hi @fabioberger. Thank you for a quick response.

Yes I can try :)

**Comment by juanfranblanco** [comment]
https://github.com/Nethereum/Nethereum/issues/393
