### ISSUE TITLE
OrderState in Detail

### ISSUE THREAD

**Issue by rhrahul** [0xProject/0x-monorepo#942]
Hi,
Is there any way we can get more details about specific order,
I mean who filled how much of order ?

Please let me know, if you already have something like this.

Thanks in Advance :)

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.38.6  |
| `Exchange Contract` | v1      |

| Network |
| ------- |
| mainnet    |

**Comment by rhrahul** [comment]
Any suggestions ? Anyone ?

**Comment by fabioberger** [comment]
@rhrahul in order to do this, you need to subscribe to the LogFill, LogCancel events on the Exchange contract.

**Comment by rhrahul** [comment]
Yes, Thanks.
I tried it, But what if we want past data, this is for live data, right ??

I also tried `getLogsAsync`,
But I am confused with it, I am not sure what to pass in BlockRange, Can you give me one sample code snippet for `getLogsAsync` and `subscribe` methods ?
That would be appreciated.

Thanks :)

**Comment by fabioberger** [comment]
Yes, you must use `getLogs`. Here is an example from the 0x Portal: https://github.com/0xProject/0x-monorepo/blob/development/packages/website/ts/blockchain.ts#L735

It depends what time range you want to search within for events.

**Comment by rhrahul** [comment]
Thanks @fabioberger  👍

**Comment by rhrahul** [comment]
can you explain me this code in less complex way please ?

`const fromBlock = tradeHistoryStorage.getFillsLatestBlock(this._userAddressIfExists, this.networkId);`

**Comment by rhrahul** [comment]
I mean what is fromBlock value in end, 
latest or pending ?

because when I tried latest, it shows empty array
and when I tried pending , it's not returning anything

**Comment by dekz** [comment]
`fromBlock` would represent the last block number which was synced. Assuming blockNumber was `10` we would search from `10->latest`. Then store the latest block number for the next polling cycle. 

If you're searching only `latest->latest` you would only get events which are occurring in the current block (according to the node you're communicating with). Pending would return transactions in the current pending block.

**Comment by rhrahul** [comment]
Ok, Thanks @dekz
