### ISSUE TITLE
Allowing to specify which artifacts to adapt with artifact_adapters

### ISSUE THREAD

**Issue by PhABC** [0xProject/0x-monorepo#971]
Currently, the [TruffleArtifactAdapter](https://github.com/0xProject/0x-monorepo/blob/development/packages/sol-cov/src/artifact_adapters/truffle_artifact_adapter.ts#L28) will adapt all contracts in the predetermined folder `contracts` (see [here](https://github.com/0xProject/0x-monorepo/blob/f9f232f5d9527926cd64027f69491b0bc6e58894/packages/sol-cov/src/artifact_adapters/truffle_artifact_adapter.ts#L28)). It would be great if there was a way to specify specifically which artifact we want to adapt. I personally have a lot of artifacts and do not need all of them to be adapted to he 0x artifact format. I even ran into a `JavaScript heap out of memory` as the amount of artifacts being converted was too large.

**Comment by LogvinovLeon** [comment]
@PhABC Will be happy to see a PR for that
