### ISSUE TITLE
Create order issues.

### ISSUE THREAD

**Issue by noydarly** [0xProject/0x-monorepo#983]
## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.25.0  |
| `Exchange Contract` | v1      |

| Network |
| ------- |
| NAME    |

**Comment by noydarly** [comment]
Hi, everyone.
Create order function works well.
but in this case i got  this issues.
token decimal is 17
taker amount is 1000000
my issue is follow.
Error: Expected order to conform to schema /Order
Encountered: {
	"maker": "0x7303e947c566a3998ece653fb26352f4bd77f32e",
	"taker": "0x0000000000000000000000000000000000000000",
	"feeRecipient": "0x0000000000000000000000000000000000000000",
	"makerTokenAddress": "0xc778417e063141139fce010982780140aa0cd5ab",
	"takerTokenAddress": "0x5eba21470cf683fe91b594afe7106039e38f3312",
	"exchangeContractAddress": "0x479cc461fecd078f766ecc58533d6f69580cf3ac",
	"salt": "16273166644072415963801569223886910971263829708131511706697806093624169494674",
	"makerFee": "0",
	"takerFee": "0",
	"makerTokenAmount": "12000000000000000",
	"takerTokenAmount": "1e+23",
	"expirationUnixTimestampSec": "1539685309000"
}
Validation errors: instance.takerTokenAmount does not match pattern "^\\d+(\\.\\d+)?$"
    at Object.assert (index.js:76)
    at Object.doesConformToSchema (index.js:64)
    at Object.getOrderHashHex (order_hash.js:28)
    at Function.ZeroEx.getOrderHashHex (0x.ts:86)
    at gen_order_with_ETH ((index):2212)

**Comment by abandeali1** [comment]
Make sure you are passing in `BigNumber` instances for the last 6 fields. It appears that you are passing in strings.
